### PR TITLE
Participate in Governance: Add CIP Wiki as reference

### PR DESCRIPTION
**Pull request by rphair**
This adds an admonition at the end of the CIP/CPS introduction to visit the [CIP Wiki](https://github.com/cardano-foundation/CIPs/wiki) posted last month.

Resolves https://github.com/cardano-foundation/developer-portal/issues/1223#issuecomment-1983879642.

---

On a related note (though perhaps only for a future PR):

Considering the placement of the CIP/CPS process in the Governance documentation, I believe it would help to add some material about CIPs being used as official references for governance proposals.  But I don't know the official / consensus position on how or when that's expected to happen.

I would like to have a better understanding myself of how that will work... perhaps @Ryun1 @thenic95 @Hornan7 could point me to some rough explanation of this & if not premature then I would submit some writing about it here & on the Wiki.

### CODE REVIEW

**Comment by Ryun1** [comment]
Here is a run down of the governance metadata CIPs
- https://sancho.network/tools-resources/resources#governance-metadata-standards

**Review by katomm — APPROVED** [review]
🫡

**Comment by Hornan7** [comment]
The CIP-1694 in a Nutshell infographic, the IOG version by Johnny Smith.
[Here](https://github.com/Hornan7/Infographics/blob/main/CIP-1694_In_a_Nutshell/CIP-1694%20IOG%20infographic%20(Update%202023-07-04).pdf)

The protocol parameters from the Governance group (as mentionned in the CIP-1694)
[Here](https://github.com/Hornan7/Infographics/blob/main/Protocol%20Parameters%20Infographics/Governance%20Protocol%20parameters%20series%20map.png)

**Comment by rphair** [comment]
It was kind of bizarre what I had to do this time to remove `yarn.lock` from this branch & can't be sure how it ended up in the diff in the first place.  Lots of dependency updates in the meantime since this was submitted, perhaps... I don't recall a `yarn.lock` being in this PR when it was created.

@rdlrt @gufmar @fill-the-fill if you could verify this is OK & merge before the next `yarn.lock` update somewhere else it would be a relief. 😅

**Review by katomm — APPROVED** [review]

**Comment by rphair** [comment]
@rdlrt @os11k @gufmar @fill-the-fill - can anyone think of a reason why the CIP Wiki should _not_ be added to the documentation section on CIPs?

**Comment by katomm** [comment]
@rphair I believe this is connected to reviews generally take longer at the moment and we often do not reach 3 required reviews or need longer.

**Review by os11k — APPROVED** [review]

**Review by fill-the-fill — APPROVED** [review]

**Pull request merged**
