### PR TITLE
Prepare revamp-stake-pool-course for merging with staging

### PR DESCRIPTION
**Pull request by katomm**
- basic restructuring and preparing the branch revamp-stake-pool-course for merging with staging 
- handling redirects
- naming convention and small fixes
- adding governance section for on-chain-poll

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
OK @katomm based on https://github.com/cardano-foundation/developer-portal/issues/737#issuecomment-1544551685, and a quick check in local build ✔️ ... the couple items reported as warning "broken links" appear resolved correctly in the build process... so let's go 🚀

**Review by rphair — APPROVED** [review]

**Comment by rphair** [comment]
(these are the ones I think are harmless; I'll see if I can fix `CIP-0057` upstream)

```
[WARNING] Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /docs/governance/cardano-improvement-proposals/CIP-0057:
   -> linking to aiken-lang.org/ (resolved as: /docs/governance/cardano-improvement-proposals/aiken-lang.org/)

- On source page path = /docs/operate-a-stake-pool/:
   -> linking to ../stake-pool-course/ (resolved as: /docs/stake-pool-course/)

- On source page path = /docs/operate-a-stake-pool/node-installation-process:
   -> linking to stake-pool-basics#understanding-consensus (resolved as: /docs/operate-a-stake-pool/stake-pool-basics)
```

**Review by rdlrt — APPROVED** [review]

**Comment by katomm** [comment]
Thanks @rphair, I was aware of the, I will fix the last two before doing a PR against staging. From just looking at the error message of the first it seems that the portal wants to resolve aiken-lang.org as a file :-/

**Comment by fill-the-fill** [comment]
> (these are the ones I think are harmless; I'll see if I can fix `CIP-0057` upstream)
> 
> ```
> [WARNING] Docusaurus found broken links!
> 
> Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
> Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
> 
> Exhaustive list of all broken links found:
> 
> - On source page path = /docs/governance/cardano-improvement-proposals/CIP-0057:
>    -> linking to aiken-lang.org/ (resolved as: /docs/governance/cardano-improvement-proposals/aiken-lang.org/)
> 
> - On source page path = /docs/operate-a-stake-pool/:
>    -> linking to ../stake-pool-course/ (resolved as: /docs/stake-pool-course/)
> 
> - On source page path = /docs/operate-a-stake-pool/node-installation-process:
>    -> linking to stake-pool-basics#understanding-consensus (resolved as: /docs/operate-a-stake-pool/stake-pool-basics)
> ```

Seems like the CIP one is miss-documented in CIP repo. Missing `https://` for Aiken. 

Screenshot 2023-05-12 at 09 26 49

**Pull request merged**
