### PR TITLE
Add DCOne ecosystem view to Showcase

### PR DESCRIPTION
**Pull request by DCOneCrypto**
### **Checklist**

☑️ View cardano ecosystem interface map showing all projects and dapps on the Cardano blockchain (ADA) ([click here](https://dconecrypto.finance/ecosystem-map.html))
☑️ Add a new project at the `Add a project `menu ([click here](https://dconecrypto.finance/DC_ProjectLists))

### **Builder**

- Name: **DCOne Crypto**
- Description: Explore projects and dApps built on Cardano. From now on, project owners, #Cardano developers, please add projects and update information with us to reach out to the community in a better way.
- Link: [click here](https://dconecrypto.finance/ecosystem-map.html)
- Tags: `ecosystem` , `cardano ecosystem`

### CODE REVIEW

**Comment by fill-the-fill** [comment]
I would say this is more of a showcase in my opinion. Check section of showcases with 'Ecosystem' tag. I assume that's what you would like as well.

**Comment by fill-the-fill** [comment]
> I would say this is more of a showcase in my opinion. Check section of showcases with 'Ecosystem' tag. I assume that's what you would like as well.
> 
> Also please use only existing tags, look through the list and see what fits your project the most. It looks like you didn't build the project on local machine after making the changes, otherwise you would see the conflicts :(

**Comment by rphair** [comment]
Also @DCOneCrypto please rebase your PR branch upon the current `staging` branch in the upstream repository... there are some changes that have happened in the meantime (https://github.com/cardano-foundation/developer-portal/pull/897) which are causing a merge conflict & it's proper for you to take care of these on your end if possible.

**Comment by DCOneCrypto** [comment]
> Also @DCOneCrypto please rebase your PR branch upon the current `staging` branch in the upstream repository... there are some changes that have happened in the meantime (#897) which are causing a merge conflict & it's proper for you to take care of these on your end if possible (even though, as @fill-the-fill says, you should be modifying the Showcase file instead).

I handled the conflict. Please check again

**Review by rphair — CHANGES_REQUESTED** [review]
@DCOneCrypto thanks for refactoring vs. the merge conflict but with respect to the above discussion you have modifed the wrong file and this should be submitted as a Showcase item rather than a Builder Tool.  Please move your modifications into the `showcases.js` file instead and then I'll tag this as a Showcase item.  

Also note the tags are case-sensitive (`ecosystem` is not capitalised)... if you would follow the suggestions from @fill-the-fill and the portal itself, a local build of the Portal web site (listed as a requirement for submission!) would let you know if any of the tags were invalid.

It will also show you how your featured image looks in the screen of Showcase thumnails.  Based on my understanding of how images are cropped vertically into the >2:1 aspect ratio box, you'll get a narrow band of your logo with the D but not the arrow.  I would suggest adding some pillarbox transparent padding to the image.

**Review by rphair — DISMISSED** [review]
The project entry has been added to `src/data/showcases.js` but it hasn't been removed from `src/data/builder-tools.js`. 😖

**Comment by rphair** [comment]
(p.s. to review) by the same token, the previously submitted logo needs to be removed from the pull request branch (BTW the new logo fits the thumbnail aspect ratio much better).

**Review by rphair — COMMENTED** [review]
I appreciate that the submission is now in proper order (and builds the portal ✔️ which could & should have been check by the submitter in the first place) but as with #902 I don't think this tool is complete: e.g. all projects show "Chart: coming soon" whether there is a token or not (as well as a blank Policy ID field).

Like with the other submission I'm not going to shoot it down in case there are improvements on the way but I can't approve it as-is either, especially since even if fixing the current UI/UX problems fixed it still doesn't seem like it offers as complete a view of the Cardano ecosystem than the [currently listed ecosystem tools](https://developers.cardano.org/showcase?tags=ecosystem).

**Comment by DCOneCrypto** [comment]
> I appreciate that the submission is now in proper order (and builds the portal ✔️ which could & should have been checked by the submitter in the first place) but as with #902 I don't think this tool is complete: e.g. all projects show "Chart: coming soon" whether there is a token or not (as well as a blank Policy ID field).
> 
> Like with the other submission I'm not going to shoot it down in case there are improvements on the way but I can't approve it as-is either, especially since even if fixing the current UI/UX problems it still doesn't seem like it offers as complete a view of the Cardano ecosystem than the [currently listed ecosystem tools](https://developers.cardano.org/showcase?tags=ecosystem).

- Thank you for your review. Policy ID depending on the project may or may not (**Minswap, Indigo, Ray Network...**)? And I agree with you Chart: "coming soon" but it is a function we add to the projects ourselves.
- Currently we have completed providing an **overview of the ecosystem and can add projects** as I described in the Checklist section above. All websites have a lot of functions and even build tools =). Thank you

**Comment by rphair** [comment]
@DCOneCrypto **_warning_**: since your did this PR from your own fork's `staging` branch, when I resolved the last merge conflict it has made your own `staging` different from the upstream `staging`.  Please keep this in mind if creating any more PRs from your fork!  (This problem usually doesn't happen because PR submitters first create branches off their master branch and do/submit the work from there.)

**Review by rphair — APPROVED** [review]
Just received request from contributor that this be re-reviewed.  Indeed the web site has been filled out since my last review several weeks ago & the features I identified as missing are now working properly in the cases that I checked.

One unique feature of this ecosystem view: I'd be interested to see how the crypto projects' "Comment community" tabs develop... especially in how the administrators might address moderation issues 😁

**Comment by DCOneCrypto** [comment]
> Just received request from contributor that this be re-reviewed. Indeed it has been filled out since my last review several weeks ago & the features I identified as missing are now working properly in the cases that I checked.
> 
> One unique feature of this ecosystem view: I'd be interested to see how the crypto projects' "Comment community" tabs develop... especially in how the administrators might address moderation issues 😁

Currently Comment community it is an open comment for the community to interact without the project owner modifying it or manipulating the results. But don't worry at fund 10 we have developed a community comment voting feature, if it is voted for with a higher rate of disapproval than accepted, it will not be displayed. Can you tell me if our project is approved to show showcase at this stage 😊

**Comment by rphair** [comment]
It requires 2 more approvals before it can be merged into the web site data... if that happens, it will be included in the next merge of this project's `staging` branch into the `main` branch that produces the web site.  So next step is for other editors to review (again).

**Comment by DCOneCrypto** [comment]
> It requires 2 more approvals before it can be merged into the web site data... if that happens, it will be included in the next merge of this project's `staging` branch into the `main` branch that produces the web site. So next step is for other editors to review (again).

Oke. Thanks you very much

**Comment by DCOneCrypto** [comment]
> @DCOneCrypto you will have to back out or reverse your last commit [4ed39b0](https://github.com/cardano-foundation/developer-portal/commit/4ed39b03468624d9db63f45f00cfa212d40953ac) from this PR, which I've approved based on your submission to the Showcase... the unrelated material you've just added effectively disqualifies your request. If you want to add a different tool to Builder Tools you will need a separate PR.



> @DCOneCrypto you will have to back out or reverse your last commit [4ed39b0](https://github.com/cardano-foundation/developer-portal/commit/4ed39b03468624d9db63f45f00cfa212d40953ac) from this PR, which I've approved based on your submission to the Showcase... the unrelated material you've just added effectively disqualifies your request. If you want to add a different tool to Builder Tools you will need a separate PR.

Thank you for the reminder. I will create another tool in the Tool Builder

**Comment by DCOneCrypto** [comment]
> Thank you for your contribution and for building on Cardano. This PR has been open for quite a while and was not able to get 3 reviewer approvals. I'm closing it now for not gaining enough "traction". 
> 
> This is not a judgment on the project and we are glad that you are building on Cardano. Suggestion: you can add your project to https://github.com/input-output-hk/essential-cardano

Thank you for the suggestion. We are already on essentialcardano with tag "ecosystem". We can know why people don't review so we can fix it for reference and maybe modify it. Thanks you!

**Pull request closed without merging**
