### PR TITLE
Add Guild Ops Suite as Operator tool

### PR DESCRIPTION
**Pull request by rdlrt**
## Operator Tool addition

* Name: Guild Operator Suite
* Description: A collection of tools and scripts for easy interaction with blockchain
* Link:  https://cardano-community.github.io/guild-operators
* Source: https://github.com/cardano-community/guild-operators

#### Description of the change

- Add `Guild Operators Suite` to getting-started page.
- Rename cntools reference to guild-ops-suite as superset.
- Fix logical error (AND to NAND, and instanceOf -> typeOf) in `checkOperatorTool` function in `builder-tools.js`

### CODE REVIEW

**Review by gufmar — APPROVED** [review]
Lgtm

**Review by katomm — APPROVED** [review]
Very nice, thank you for the contribution. Small note: I think the notebox with the "disclaimer" has a tab in which results into a code box within the note box.

**Comment by rdlrt** [comment]
> Very nice, thank you for the contribution. Small note: I think the notebox with the "disclaimer" has a tab in which results into a code box within the note box.

Ah - I think I fixed it with the next [squashed] commit before marking it ready (y)

**Review by Scitz0 — APPROVED** [review]
👌

**Pull request merged**
