### PR TITLE
Update showcases.js

### PR DESCRIPTION
**Pull request by frogdesk**
👋👋 Hello there! Welcome. Please follow the steps below to tell us about your contribution.

1. Select **one of the templates below** that fits your contribution
2. Remove this text as well as the other templates
3. Fill in all sections of the template
4. Summon a reviewr using @mentions (optional)
5. Click "Create pull request"

---

## Showcase addition

* Name: *Project name*
* Description: *Describe your project* (See [Showcase guidelines](CONTRIBUTING/#showcase))
* Link:   <link_to_project>
* Source: <link_to_source_code>
* Tags:
  * `analytics`
  * `explorer`
  * `educational`
  * `game`
  * `gateway`
  * `opensource`
  * `pooltool`
  * `metadata`
  * `nativetoken`
  * `nft`
  * `wallet`

 

---

#### Issue

Fixes #issueId

#### Description of the change

---

## Bugfix

Fixes #issueId

#### Description

 

---

### CODE REVIEW

**Comment by rdlrt** [comment]
1. Please read the showcase guidelines as indicated in PR template.
2. Please update the description of PR.
3. Ensure your PR build does not run into errors

**Comment by happypus** [comment]
Name: Happypus
Description: Inspired by Charles Hoskinson's own Happy Octopus mascot.
Link: https://happypus.fun/
Source: null
Tags: nft

**Comment by rdlrt** [comment]
Closing due to no response after no attention to read instructions

**Comment by frogdesk** [comment]
I did actually read them and attempted to follow to the best of my ability. I've been very busy and unable to get back to this. We'll pass on being part of the directory given your attitude.

**Pull request closed without merging**
