### PR TITLE
Fix broken link to Testnet Faucet

### PR DESCRIPTION
**Pull request by fill-the-fill**
## Bugfix

Fix broken link mentioned in #628

### CODE REVIEW

**Review by katomm — COMMENTED** [review]
I doubt this fixes the problem in #628 as .md is optional.

**Comment by rdlrt** [comment]
I am unclear what are we fixing, the mentioned page [here](https://staging-dev-portal.netlify.app/docs/transaction-metadata/how-to-create-a-metadata-transaction-cli) seems to have correct hyperlink which takes you to [faucet page](https://staging-dev-portal.netlify.app/docs/integrate-cardano/testnet-faucet)

**Comment by fill-the-fill** [comment]
> I am unclear what are we fixing, the mentioned page [here](https://staging-dev-portal.netlify.app/docs/transaction-metadata/how-to-create-a-metadata-transaction-cli) seems to have correct hyperlink which takes you to [faucet page](https://staging-dev-portal.netlify.app/docs/integrate-cardano/testnet-faucet)

I believe the current link is broken, but I fixed it

**Comment by katomm** [comment]
I believe it is again this issue #312 it is a problem when using relative links.

**Comment by rdlrt** [comment]
> I believe it is again this issue #312 it is a problem when using relative links, it seems the only good way to rule this out is to write /docs/something 
> 
> cc: @rdlrt @fill-the-fill @BharatAtEMURGOIO 

Ah gotcha, explains why I wasn't able to replicate when checking hyperlinks :+1:

**Comment by katomm** [comment]
Any update on this?

**Review by mallapurbharat — APPROVED** [review]
Yes, this seems to work fine now. Thanks!

**Comment by mallapurbharat** [comment]
Yes, it does seem to fix the issue.

**Comment by katomm** [comment]
> Yes, this seems to work fine now. Thanks!

Great, see you at Emurgo Academy!

**Pull request merged**
