### PR TITLE
Add Chainspect to Showcase

### PR DESCRIPTION
**Pull request by fromaline**
👋 Hello there! Welcome. Please follow the steps below to tell us about your contribution.

1. Please complete a Checklist
2. Fill in all sections of the template
3. Click "Create pull request"

## Checklist
- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have read the [Showcase Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/showcases.js)
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Showcase addition
* Title: Chainspect
* Description: Chainspect is an independent blockchain analytics platform focused on tracking technical metrics for the most widely used blockchains, including Cardano. We track Real-Time TPS, Max Recorded TPS, Max Theoretical TPS, Block Time, TTF, Governance Model, and Launch Date for 40+ chains, including Cardano.
* Website: https://chainspect.app/
* Source: N/A
* Tags:
  * `analytics`

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
I don't think this project illustrates anything about Cardano from either a development or a user perspective.  The home page refers to Ethereum, Bitcoin, Solana, Polygon, Avalanche, Algorand, and Fantom (with particular emphasis on Ethereum) without the word Cardano appearing even once, even in the images.

**Comment by fromaline** [comment]
Hey @rphair,
Thank you for your feedback and for taking the time to explore our platform. I’d like to address your concerns:

> I don't think this project illustrates anything about Cardano from either a development or a user perspective.

Chainspect is an analytics platform that does not emphasize any particular blockchain. We track over 40 blockchains, allowing users to compare them easily. By including Cardano, we offer valuable insights into how it performs against other major blockchains in metrics such as TPS, Block Time, TTF, etc. I believe this comparative analysis is beneficial for the Cardano community.

> The home page refers to Ethereum, Bitcoin, Solana, Polygon, Avalanche, Algorand, and Fantom (with particular emphasis on Ethereum) without the word Cardano appearing even once, even in the images.

That's true! We mention Ethereum, Bitcoin, and Solana on our chain page as the biggest players in the field while using Ethereum as a neutral example. However, Cardano has a dedicated chain page on Chainspect (https://chainspect.app/chain/cardano) and multiple comparison pages (e.g., https://chainspect.app/compare/cardano-vs-ethereum, https://chainspect.app/compare/cardano-vs-bitcoin).

But I understand your concerns! To better showcase Cardano, I propose the following changes in `src/data/showcases.js`:
1. Change the website link from https://chainspect.app to https://chainspect.app/chain/cardano. It'll lead directly to the Cardano chain page.
2. Use a screenshot of the Cardano chain page as a preview image to focus on Cardano rather than other networks.

Additionally, we have recently added Cardano to the "Proudly Collaborating With" section on our landing page, ensuring it gets mentioned prominently.

What do you think of these changes? I look forward to your response! Thank you again for your time and consideration 🙏

**Comment by rphair** [comment]
@fromaline first note that my lack of approval doesn't disqualify your project from being included in the portfolio.  There are several other reviewers and only 3 affirmative responses would be necessary in order to confirm the proposed listing.

Since you've pressed for more detail I have to say how unhelpful I think these "blockchain comparative" sites are in general.  Metrics like TPS and TVL so far have mainly been used to promote industry media favourites, which pushes the crypto world onto a path towards centralisation and chauvinism.

I would happily support a link to the `/cardano` page if you had any way — apparently not possible with your model which includes only mainstream features — if it went into any detail about information density in transaction flow, smart contract efficiency, and features & design possibilities of Cardano's uncommon eUTxO model resulting from transaction determinism.

You are comparing Cardano to the world on terms that only serve its entrenched competitors... while the purpose of this site is to emphasise Cardano's distinctive features and teach the community of users and developers to use & contribute to that uniqueness.  If you could find a convincing way of doing that, according to the details above, then you would have my full support.

**Comment by fromaline** [comment]
@rphair, thanks for sharing your thoughts — I understand your points and where they come from!

To be honest, we are getting similar requests for almost every blockchain we integrate into Chainspect 😅
But we are always forced to respectfully disagree and keep our metrics standardized. Otherwise, we end up with a bunch of erroneous data, which can't be understood by an average blockchain user.

In other words, there is always a tradeoff between standardization and creating custom, blockchain-specific metrics, which are not comparable to one another.

Hope it makes sense 🙏

**Review by katomm — COMMENTED** [review]
I am glad that you have integrated Cardano, but as a showcase in a developer portal it is simply not enough for me to be accepted. I take the liberty of closing the PR for the reason that this is completely different from the entries you would expect to see in the "Analytics" category.

It would also be a precedent for even sites like Coinmarketcap, Coingeko and the like to end up as a showcase.

**Pull request closed without merging**
