### PR TITLE
Upgrade to Docusaurus 3

### PR DESCRIPTION
**Pull request by fill-the-fill**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 
- [x] I have not committed any changes to `yarn.lock` (or have [removed these changes](https://developers.cardano.org/docs/portal-contribute/#i-committed-yarnlock-to-my-pr-branch-what-do-i-do)).

## Updating documentation or Bugfix

Hey 😎 

I finally got some time to play around and update Docusaurus 3+.

I've made quite a few changes, and everything seems to be working now, including the previously broken Changelog.

The main issue was with pulling markdown files such as CIPS and others. Some of the files didn’t follow the correct formatting, which caused breaks on our side. Creating a special case for each file would have been a nightmare since every file that was pulled had its own missing comma or bracket that was really hard to track.

Since the biggest issue with upgrading to Docusaurus 3.0 was the transition to MDX, one of the biggest game-changers that helped was [Experimental Commonmark](https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability). That quickly took care of the issue.

I added the following code to `docusaurus.config.js`:

```
  markdown: {
    format: "detect"
  },
```

However, this ended up breaking some of our markdown files, specifically those using the `<Tabs>` element. The solution I came up with was to transition those files from `.md` format to `.mdx`. I've decided to leave the decision of transitioning all the files to `.mdx` up to everyone else.

Please feel free to test it out locally and check if I've missed anything, thank you!

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
@fill-the-fill - this is very welcome and I would be inclined to merge it rather than remain on the obsolescent version of Docusaurus (FYI for group: this builds `v3.5.2`).

It builds a working site locally that I can't find any UI/content problems with, but the diagnostic warnings generated by the `yarn build` are huge... enough to overwhelm any messages about legitimate problems or things to clean up.  This includes reported broken links and missing anchors on pages that appear to be working correctly on the built site.

> The main issue was with pulling markdown files such as CIPS and others. Some of the files didn’t follow the correct formatting, which caused breaks on our side.

I don't know what to make of this, since I can personally guarantee the CIP editors have been rigorous about following Markdown formatting conventions, and have been fixing linking & other formatting issues that caused things to break on the Dev Portal for the 2+ years I've been involved in both projects.  Any real breach of Markdown rules would have been identified on the previous version of Docusaurus.

It seems likely that CIP formatting problems would be in how the files are translated after downloading from GitHub... e.g. there are references to these "broken anchors" on many CIPs, for anchors that don't exist in the source material:
```
- Broken anchor on source page path = /docs/governance/cardano-improvement-proposals/CIP-0014:
   -> linking to CIP-0001#cip-format-and-structure (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0001#cip-format-and-structure)
   -> linking to CIP-0001#cip-workflow (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0001#cip-workflow)
```
Likewise there are reported problems on the documentation pages, in some cases broken links to autogenerated content like the section headings in the article sidebar.... though these were working normally for the pages I checked.

So I can approve this if this is the best we can get for now, but I do think it would first be worth a look at what generates this huge trail of debugging output & solve those cases one by one before merging this.  If any source material on the CIPs repository is an issue then let's identify such problems here and I'll fix them upstream immediately.

**Comment by fill-the-fill** [comment]
@rphair 

> I don't know what to make of this, since I can personally guarantee the CIP editors have been rigorous about following Markdown formatting conventions, and have been fixing linking & other formatting issues that caused things to break on the Dev Portal for the 2+ years I've been involved in both projects. Any real breach of Markdown rules would have been identified on the previous version of Docusaurus.

Regarding that, I've ran `npx docusaurus-mdx-checker` (suggestion from [here](https://docusaurus.io/docs/migration/v3#troubleshooting)

**Comment by katomm** [comment]
I don't get why you cut out all the truncate comments in the blog posts, we need them for the preview. 

Also the md to mdx seems to be not necessary, what's the reasoning behind that? Thanks.

**Comment by katomm** [comment]
This PR contains too many problems, assumptions and decisions that will cause us problems in the near future. In this state it should be converted in a draft.

**Comment by fill-the-fill** [comment]
> I don't get why you cut out all the truncate comments in the blog posts, we need them for the preview. 
> 
> Also the md to mdx seems to be not necessary, what's the reasoning behind that? Thanks. 

I've stated above the reasoning behind converting certain files from .md to .mdx, you are more than welcome to test out those files in .md format and see it for yourself.

**Comment by fill-the-fill** [comment]
I've added back truncates and fixed most of the warnings. At the moment the only warnings are CIP files related.

**Comment by rphair** [comment]
> At the moment the only warnings are CIP files related.

@fill-the-fill it's true: the broken rendering of the CIP content from GitHub still generates a lot of spurious warnings.  Are you suggesting that the Markdown content of the CIPs themselves is the true reason for this?  If so, can you give an example in the actual CIP content?

**Comment by fill-the-fill** [comment]
@rphair 

For example, in `CIP-0001`, line `338` in sentence:

`Once a proposal has reached all requirements for its target status (as explained in [Statuses](#Statuses)) and has been sufficiently and faithfully discussed by community members, it is merged with its target status.`

`[Statuses](#Statuses))` should be `[Statuses](#statuses))`

I've managed to remove most of the warnings this morning by adjusting CIP and CPS scripts, but here is the list of warnings that should probably be taken care of on CIP repo instead:

```
- Broken anchor on source page path = /docs/governance/cardano-improvement-proposals/CIP-0001:
   -> linking to #Statuses (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0001#Statuses)
- Broken anchor on source page path = /docs/governance/cardano-improvement-proposals/CIP-0002:
   -> linking to #requested-output-set (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#requested-output-set)
   -> linking to #initial-utxo-set (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#initial-utxo-set)
   -> linking to #maximum-input-count (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#maximum-input-count)
   -> linking to #coin-selection (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#coin-selection)
   -> linking to #remaining-utxo-set (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#remaining-utxo-set)
   -> linking to #utxo-balance-insufficient (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#utxo-balance-insufficient)
   -> linking to #utxo-not-fragmented-enough (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#utxo-not-fragmented-enough)
   -> linking to #utxo-fully-depleted (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#utxo-fully-depleted)
   -> linking to #maximum-input-count-exceeded (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#maximum-input-count-exceeded)
   -> linking to #available-utxo-list (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#available-utxo-list)
   -> linking to #unpaid-output-list (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#unpaid-output-list)
   -> linking to #accumulated-coin-selection (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#accumulated-coin-selection)
   -> linking to #cardinality-1 (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#cardinality-1)
   -> linking to #available-utxo-set (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#available-utxo-set)
   -> linking to #accumulated-coin-selection-1 (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#accumulated-coin-selection-1)
   -> linking to #phase-1-random-selection (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#phase-1-random-selection)
   -> linking to #phase-2-improvement (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#phase-2-improvement)
   -> linking to #termination-1 (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#termination-1)
   -> linking to #rationale-how-does-this-cip-achieve-its-goals (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#rationale-how-does-this-cip-achieve-its-goals)
   -> linking to #motivating-principles (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#motivating-principles)
   -> linking to #goals (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#goals)
   -> linking to #selected-utxo-set (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#selected-utxo-set)
- Broken anchor on source page path = /docs/governance/cardano-improvement-proposals/CIP-0026:
   -> linking to #special-case--phase--1-monetary-policies (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0026#special-case--phase--1-monetary-policies)
- Broken anchor on source page path = /docs/governance/cardano-improvement-proposals/CIP-0071:
   -> linking to #Creation-of-Ballot-Without-Casting-a-Vote (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0071#Creation-of-Ballot-Without-Casting-a-Vote)
   -> linking to #Ballot-Box---Smart-Contract (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0071#Ballot-Box---Smart-Contract)
   -> linking to #Motivation (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0071#Motivation)
   -> linking to #Ballot---Plutus-Minting-Policy (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0071#Ballot---Plutus-Minting-Policy)
   -> linking to #Ballot-Counter---Authorized-Wallet (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0071#Ballot-Counter---Authorized-Wallet)
- Broken anchor on source page path = /docs/governance/cardano-improvement-proposals/CIP-0086:
   -> linking to #rationale (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0086#rationale)
- Broken anchor on source page path = /docs/governance/cardano-improvement-proposals/CIP-0088:
   -> linking to #6--cip-specific-information (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0088#6--cip-specific-information)
- Broken anchor on source page path = /docs/governance/cardano-improvement-proposals/CIP-0095:
   -> linking to #acknowledgements (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0095#acknowledgements)
- Broken anchor on source page path = /docs/governance/cardano-improvement-proposals/CIP-0108:
   -> linking to #acknowledgements (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0108#acknowledgements)
- Broken anchor on source page path = /docs/governance/cardano-improvement-proposals/CIP-0119:
   -> linking to #Acknowledgements (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0119#Acknowledgements)
   -> linking to #paymentAddress (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0119#paymentAddress)
   ```

**Comment by rphair** [comment]
thanks @fill-the-fill - I'd be ready to post an issue on the CIPs repo to decide on a standard for anchor links that will be most portable outside of GitHub, including Docusaurus.  But first I need to understand _exactly_ what this version of Docusaurus does not "like" about these links.

I thought it might be a matter of capitalisation (with all lowercase being canonical), but while that explains the first warning (CIP-0001) it's not an issue with the second (CIP-0002 first item): since the anchor Docusaurus "likes" is also used everywhere in the CIP-0002 source.

And at the end you see Docusaurus selecting "canonical" links that have initial or camel capitalisation, so it can't be as simple as that (see [here](https://github.com/rphair/CIPs/blob/master/CIP-0119/README.md#acknowledgements), where GitHub generates a lowercase link while Docusaurus says it wants initial capitalisation).

So unless you can explain the rules that links in the source documents are expected to follow, we may need more verbose information about how the warnings are being flagged... we'd need a line number and/or other precise context, not just the file that link is in.  (Could you set an option in the build script that's more verbose about where the warning is?)

Once we can put those rules into an issue on the CIPs repository then we might start making these corrections preemptively.  Authors might not be able to write their documents that way, but we've talked about adding a GitHub CI for the CIPs repo that will do some format massage & file updates when checking in pull requests & we could add something there when that is set up.

**Comment by fill-the-fill** [comment]
@rphair thanks for your reply. It seems like the issue with the example in CIP-2 is that some of the links are broken and can't be read, look at the example bellow:

gif

Here is another issue, those should be redirecting to a specific part of the page, but they're not recognized, in the example bellow you can see I'm clicking on the link, usually it goes to that part of the page, in this example nothing happens:


gif2

**Comment by fill-the-fill** [comment]
>So unless you can explain the rules that links in the source documents are expected to follow, we may need more verbose information about how the warnings are being flagged... we'd need a line number and/or other precise context, not just the file that link is in. (Could you set an option in the build script that's more verbose about where the warning is?)

In my opinion, this is not needed, but I could be wrong, for example:

` -> linking to #accumulated-coin-selection (resolved as: /docs/governance/cardano-improvement-proposals/CIP-0002#accumulated-coin-selection)`

Easily can be found by searching `#accumulated-coin-selection`. I don't believe there are any duplicates in the warnings.

**Comment by rphair** [comment]
> Easily can be found by searching #accumulated-coin-selection. I don't believe there are any duplicates in the warnings.

There are aren't duplicate warnings, but the links which generate the warnings are duplicated in individual CIP documents.  See `#requested-output-set` in CIP-0002 (as quoted in https://github.com/cardano-foundation/developer-portal/pull/1335#issuecomment-2399291533) for a good example: this anchor appears 20 times in the document, so without a line number you'd have to investigate all of them to find which was generating the warning.  😬

**Comment by fill-the-fill** [comment]
> > Easily can be found by searching #accumulated-coin-selection. I don't believe there are any duplicates in the warnings.
> 
> There are aren't duplicate warnings, but the links which generate the warnings are duplicated in individual CIP documents. See `#requested-output-set` in CIP-0002 (as quoted in [#1335 (comment)](https://github.com/cardano-foundation/developer-portal/pull/1335#issuecomment-2399291533)) for a good example: this anchor appears 20 times in the document, so without a line number you'd have to investigate all of them to find which was generating the warning. 😬

I will come back to you very soon

**Comment by rphair** [comment]
thanks @fill-the-fill - that's very helpful.  I do think eventually we should have diagnostics from `yarn build` itself about where the exact problems are, but for these I'll address them upstream after finishing some work deadlines this week or two (referring back here & marking up the outline above) and then file an issue if these problems have common elements, so that other editors & maybe authors can be aware of them (cc @Ryun1 @perturbing).

**Comment by fill-the-fill** [comment]
Ok looks like build broke again, I will check it soon

**Comment by katomm** [comment]
Thanks for the effort again @fill-the-fill and everyone that is participating here. What I'm concerned about is: the list of compromises is getting longer and longer to maintain this. We are at a point where it is questionable not to remove the CIP from the portal. cips.cardano.org has been greatly improved in the last few months, you could try to index that so that you can still search for CIP content with the Developer Portal search but then land directly on cips.cardano.org.

**Comment by aldo555** [comment]
@rphair We will very soon be updating cips.cardano.org to be automatically rebuilt once a push is made to the cips repo.

**Comment by katomm** [comment]
Unfortunately a bit offtopic but helps me to substantiate my argument above: build breaks now because of CIP-127
photo_2024-10-17_21-40-32

**Comment by rphair** [comment]
no @katomm that's a welcome comment & not really off topic because it was the basis for just referring the CIP other editors again back here in a parallel thread.  Here's the other one of the 2 with the same breakage:
```
10:matangi$ grep ^Title: */README.md | grep \`
CIP-0101/README.md:Title: Integration of `keccak256` into Plutus
CIP-0127/README.md:Title: `ripemd-160` hashing in Plutus Core
```
I'll push through a PR to fix these upstream right away & have asked the others for opinions about https://github.com/cardano-foundation/developer-portal/pull/1335#issuecomment-2419216985.

**Comment by rphair** [comment]
https://github.com/cardano-foundation/developer-portal/pull/1335#issuecomment-2420391244 fixed in https://github.com/cardano-foundation/CIPs/pull/930.

**Comment by rphair** [comment]
Builds should no longer be failing for this reason, as of https://github.com/cardano-foundation/CIPs/commit/e4c5f485c3047dda53ef8ea3ef31c42f7e3cc5d0.

**Pull request closed without merging**
