### PR TITLE
Add showcase Exodus Wallet

### PR DESCRIPTION
**Pull request by fill-the-fill**
* Name: Exodus Wallet
* Description: Send, receive, and exchange Bitcoin and 165+ cryptocurrencies with ease on the world's leading Desktop, Mobile and Hardware crypto wallets,
* Link:  https://www.exodus.com
* Tags:
  * `wallet`

### CODE REVIEW

**Review by katomm — APPROVED** [review]
👍

**Comment by rdlrt** [comment]
Strongly against non-opensource custodial wallets **IF** they're not compatible with common derivation schemes for wallets, they form a single point of failure - you dont want folks to end up in state like ethos/voyager where they need special techniques to get funds out or have them stuck relying on manual interaction with support teams.

**Comment by katomm** [comment]
Fair point. Thanks.

**Comment by katomm** [comment]
Closed because there are several concerns here.

**Pull request closed without merging**
