### PR TITLE
Added Builder Tool: Cardano Light Tools

### PR DESCRIPTION
**Pull request by orpheus-antpool**
* Name: Cardano Light Tools
* Description: A set of lightweight tools to operate and maintain a Cardano Stake Pool. Focuses on simplicity, low resource utilization (CPU, memory) and portability across platforms.
* Link: https://github.com/orpheus-antpool/cardano-light-tools
* Source: https://github.com/orpheus-antpool/cardano-light-tools
* Tags:
  * `operatortool`

### CODE REVIEW

**Comment by rdlrt** [comment]
Hi,
Just following the guidelines, the 'current status' of repo versus description seems to be off, as the repo provides atm a single tool for monitoring metrics.

**Comment by orpheus-antpool** [comment]
@rdlrt: the intent is to provide multiple mini-tools. Of course, in the beginning, we have to start with one. Would it make more sense to submit a separate request for each mini-tool?

**Comment by rdlrt** [comment]
For consistency in approvals, I would say can start by having description for current status - and edit in future once there are more?

**Review by rdlrt — APPROVED** [review]
Thanks

**Comment by orpheus-antpool** [comment]
Sounds good, I'll keep the description up to date

**Pull request merged**
