### PR TITLE
Add NFT Creator showcase

### PR DESCRIPTION
**Pull request by minolinpwork**
* Name: NFT Creator
* Description: Design your own NFT
* Link:  https://nft-creator.pics
* Source: null
* Tags:
  * `minting`
  * `nftsupport`

### CODE REVIEW

**Comment by rphair** [comment]
@minolinpwork I'm ready to test & review this... can you please update your fork with the latest commits from `staging` & post when that's done?  Some commits to the main repository in the last few days have both caused & fixed build problems, so we need to start form a clean code base.

**Comment by minolinpwork** [comment]
I've completed syncing from the staging branch

**Review by rphair — APPROVED** [review]
Merge conflict apparently resolved, and I confirm this builds OK with `staging` at this moment.

As with the Gift Card Creator the description is a little anaemic compared to other projects but it's the submitter's choice how much detail to provide here. 😎

**Comment by minolinpwork** [comment]
@rphair To add more detail to Gift Card Creator description - can I do it on this branch? or the Gift Card Creator branch (which has already been merged into staging and has conflicts), or should I create a new branch and create a new pull request?

**Comment by rphair** [comment]
> To add more detail to Gift Card Creator description - can I do it on this branch?

Yes, you should use this branch (the one you used to create this PR), for this & any other modifications that relate to the addition of the _NFT Creator_ project.

**Comment by rphair** [comment]
@minolinpwork I'm sorry if I made you feel simply as if there were not enough words in the description: your potential users will already know how an image editor works and the different purposes greeting cards can be used for 😅 ... I was hoping the additional detail could give a sentence about how your tools work _in Cardano & blockchain_.

Anyway I am happy to leave this all in the hands of the next couple of reviewers and thank you for your contribution 😎

**Review by fill-the-fill — APPROVED** [review]

**Review by katomm — APPROVED** [review]
LGTM

**Pull request merged**
