### PR TITLE
Add Do It With Lovelace to Showcase

### PR DESCRIPTION
**Pull request by jmagan**
## Checklist

- [X] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [X] I have read the [Showcase Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/showcases.js)
- [X] I have run `yarn build` after adding my changes **without getting any errors**. 

## Showcase addition

* Title: *Do It With Lovelace*
* Description: *A Cardano-based dApp platform for easy and secure donations with a focus on community impact and transparency.*
* Website:   https://app.doitwithlovelace.io
* Source: -
* Tags:
  * `ecosystem`

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
1 - the `ecosystem` tag is inappropriate because this is only for projects which explore the Cardano ecosystem itself.  You would have to choose at least one appropriate tag from the ones currently listed here (and next time please check the `showcases.js` file to make sure the definition fits your project): https://developers.cardano.org/showcase

2 - As it also says in the JS file, `// Add your project to (THE END OF) this list.` so please if continuing your submission then move your definition to the end of the array.

3 - In English usage the "little words" `it` and `with` are not capitalised even in titles.

If there isn't an appropriate category tag we might add a `charity` category but I haven't seen another such project come along in the last several months, and we try to avoid categories with only 1 member.  In any case I could agree with defining a `charity` tag if other editors note here they are in favour.

**Comment by jmagan** [comment]
Sorry @rphair, I was struggling with the tags. I didn't find any tag appropiate for my project. I was thinking in something like `funding`, what do you think about it? I think it's more general... and I'm thinking to eventually steer my project towards funding also.

2 - Shame on me! sorry! I'll change it. :upside_down_face:

**Comment by jmagan** [comment]
I commited the fixes. I broke the rule `// List of available tags. The tag and the label should be in singular. (PLEASE DO NOT ADD NEW TAGS)` adding the funding tag but I understood from our convesation that I could propose a new tag. If you don't like, I can remove it. 

Thank you in advance.

**Review by rphair — COMMENTED** [review]
other reviewers: I think it would create a good space in our ecosystem if we could create a `funding` tag (as OP suggests & I realise this is a more general case than `charity` and a more contemporary term than `fundraising`).  If this is favourably reviewed then I'll create the tag in this PR so it builds properly.

@jmagan I believe the acceptance of this submission now is dependent upon creating that category: let's see what happens.  In the meantime I also agree with what's posted on the forum ([Do It With Lovelace: A Simple Platform for Donations on Cardano](https://forum.cardano.org/t/do-it-with-lovelace-a-simple-platform-for-donations-on-cardano/117251)) and think you could improve this by responding to what I think would be common question / critique:
> Donations to who or what? At the moment, it just looks like it’s using AdaPay’s form. No receive address to confirm receipt to organisation. No method to add new organisation except through email?  Nice try. Really basic.

... and add a landing page on the web site rather than directing visitors just to the `app` page itself which doesn't have anything in the way of online help, or even what happens in the app, or any information about your organisation except for the fluff on the "About" page.

I agree with the Forum that is has potential but I think we need to see the same calibre of detail and user support as we have for other items on the Showcase before including this on the Dev Portal.

**Comment by jmagan** [comment]
Hi @rphair, thank you for your help. I've just replied in the cardano forum:

> Thank you for your time and feedback. I’ve studied ADAPay, and I believe it’s more business-oriented. Companies can register and add ADA as a payment method, and its main functionality is focused on transactions.
>
> Anyone can join and open an account on Do It With Lovelace, becoming a donor or donee. I wrote a specification for authentication as a CIP, which you can find here: [CIP-???? | Authenticated Web3 HTTP requests by jmagan · Pull Request #442 · cardano-foundation/CIPs · GitHub](https://github.com/cardano-foundation/CIPs/pull/442). Additionally, I’m contributing to the Cardano community with simple web3 standards and templates to make it easier to develop on Cardano.
> 
> From your feedback and other comments, I realized that I need a landing page with more instructions and clarifications on how it works. Thank you for bringing that to my attention!
> 
> Initially, there are three potential use cases for the current implementation:
> 
> 1. Developers, CIP editors, charity organizations, and open source projects looking to be funded, supported, and rewarded for their actions.
> 2. Use it as a tip jar for people who do requested work on forums, Reddit, etc. and help track their portfolios through reviews and comments from requesters.
> 3. SPOs who want to make their contributions more visible to the community.
>
> I started with a simple MVP because I want to make features that are community-oriented. I’m doing this in my free time, and it’s not a monetized platform because I want to provide something useful and valuable to the community. So, thank you again for your feedback. I’m going to work on creating a good landing page.

I'll be working to improve and meet all the requirements. :slightly_smiling_face:

**Comment by jmagan** [comment]
@rphair I'm happy to show you the brand new landing page :slightly_smiling_face: https://app.doitwithlovelace.io/

**Review by rphair — APPROVED** [review]
thanks @jmagan - the descriptive landing page is a good orientation.  I think it all works well together now.

Other reviewers: like I said in https://github.com/cardano-foundation/developer-portal/pull/1043#pullrequestreview-1401178402, a vote for this PR is a vote for also creating the `funding` tag which I have verified works well in a local build. ✔️

**Comment by rphair** [comment]
Last merge conflict resolution I had to remove a redundant entry for BALANCE showcase item from the end of the array.  It's still in @jmagan's branch here (so the one I removed was redundant; an artefact from this PR's age): https://github.com/jmagan/developer-portal/blob/8db49a6118cad18cac094bea857069087560625a/src/data/showcases.js#L1065

@katomm @rdlrt @fill-the-fill etc. can we please merge this so we can have a `funding` category to apply to @thenic95's issue https://github.com/cardano-foundation/developer-portal/issues/1107?

**Review by rdlrt — APPROVED** [review]

**Review by fill-the-fill — APPROVED** [review]

**Pull request merged**
