### PR TITLE
Add plu-ts to Builder Tools + Smart Contract platforms

### PR DESCRIPTION
**Pull request by michele-nuzzi**
## Builder Tool addition

* Title: *plu-ts*
* Description: *Typescript-embedded smart contract programming language and transaction creation library* 
* Website:  [pluts.harmoniclabs.tech](https://pluts.harmoniclabs.tech/docs/intro)
* Getstarted: /docs/get-started/plu-ts
* Tags:
  * `javascript`
  * `plutus`
  * `typescript`
  * `serialization`

### CODE REVIEW

**Comment by michele-nuzzi** [comment]
Fixed the build process.

Was failing due to missing `plu-ts` tag.

As mentioned in the #1027; it would be great if tag can be added.

**Comment by OlofBlomqvist** [comment]
There is a list of languages on the smart contract overview page as well where you might want to add this :)

**Comment by michele-nuzzi** [comment]
> There is a list of languages on the smart contract overview page as well where you might want to add this :)

Thank you, I missed that

**Review by rphair — COMMENTED** [review]
@michele-nuzzi I'm happy to approve this as per https://github.com/cardano-foundation/developer-portal/issues/1026#issuecomment-1509530977 but please first remove the `yarn.lock` update from this PR... don't remove the file, just revert to the mainstream version & commit: https://developers.cardano.org/docs/portal-contribute#i-committed-yarnlock-to-my-pr-branch-what-do-i-do

**Comment by michele-nuzzi** [comment]
I just noticed that `/docs/smart-contracts/plu-ts` is present and can be reached by typing manually the url however is missing in the sidebar.

Have I missed something to add the entry in the sidebar?

**Comment by rphair** [comment]
This PR still currently modifies `yarn.lock` since the version you committed in https://github.com/cardano-foundation/developer-portal/pull/1027/commits/0ceb958e194b777abc8f4cc06a34ab45a96f11f4 is missing its final newline (maybe the contents of the file were restored into an editor rather than the file itself?) which you can see in the `/files` tab of this PR.

If in doubt can you please commit the `yarn.lock` from the `staging` branch as recommended in the link above?  If possible we would like to stick with our set policy of contribution PRs not affecting the version history for this file.

Also it will help me test build your PR locally & help fix your navigation problem since I then I won't need to do a `yarn install` which is currently impossible due to my terrible Internet here. 😓

**Comment by rphair** [comment]
@michele-nuzzi now there is an _extra_ newline at the end of `yarn.lock`.  I will leave it to you as to how you make the `yarn.lock` update disappear from this page: https://github.com/cardano-foundation/developer-portal/pull/1027/files

**Comment by rphair** [comment]
p.s. to https://github.com/cardano-foundation/developer-portal/pull/1027#issuecomment-1509729843 @michele-nuzzi: we could fix this relatively easily but we have no write permission to the branch for this PR.

**Comment by michele-nuzzi** [comment]
@rphair now you should have write access, please let me know

**Comment by michele-nuzzi** [comment]
also, maybe a stupid question, but can't we add `yarn.lock` as `.gitignore` entry so that everyone keeps a local `yarn.lock` without modifying anything?

**Review by rphair — APPROVED** [review]
OK, fixed it now.  Maybe your `yarn.lock` with no newline at end of last content line caused some weird displacement I saw in the GitHub UI editor.

`yarn.lock` is already in `.gitignore`: https://github.com/cardano-foundation/developer-portal/blob/staging/.gitignore ... my guess is that some IDE's and even ordinary use of `git` can cause `yarn.lock` to get rebuilt or perhaps merged from other work.

other editors: just checked that looks & works OK in local build. ✔️

@michele-nuzzi don't forget to remind us to add a `plu-ts` tag as per https://github.com/cardano-foundation/developer-portal/issues/1026 after this is merged. 🤓

**Comment by michele-nuzzi** [comment]
Awesome thanks @rphair for all this work

**Review by rdlrt — APPROVED** [review]

**Review by os11k — APPROVED** [review]

**Pull request merged**
