### PR TITLE
Current Staging Build is broken, remove API tag from Cexplorer to fix it 

### PR DESCRIPTION
**Pull request by fill-the-fill**
- Remove API tag to fix issue on staging

### CODE REVIEW

**Review by rphair — APPROVED** [review]
I'm clearing this in honour of the URGENT request, but:

1 - I/we've submitted logos alone for most of the last several showcase additions because the result of the last conversation on the subject was that full-screen project images _are not displayed in the portal UI_.  To me it seems like common sense therefore that full screen demo pictures have no use unless the contributor doesn't feel like preparing a smaller sized image:
https://github.com/cardano-foundation/developer-portal/pull/777#issuecomment-1250023836
https://github.com/cardano-foundation/developer-portal/pull/777#issuecomment-1250030331

I posted these questions after spending about 2 hours preparing a detailed screenshot for that ("Cardano Signer") project (a composite for the command usage & examples, as you @fill-the-fill had prepared before), only to realise that the portal UI could never be made to display it... not even if opening the image directly from the showcase listing.  The only way to see the full screen image would be to clone or fork the repository, which front line users will not do.

So if this (Cexplorer) logo is now being replaced by a detailed image, can I ask again less politely but more emphatically this time... when & how does this higher resolution image ever display in the Dev Portal UI?

2 - There were 2 PR's which arranged the current Cexplorer / Adaex / Adapools material as it was at the time #800 was merged.  I personally checked both of those PR's to be sure they built properly with `staging`.  If the portal was failing to build afterward, it is likely the result of some merge conflict being resolved improperly which perhaps affected the same section of code.

3 - The decision to move Cexplorer effectively from Showcase (by removing the obsolete Adaex and the deprecated Adapools) to Builder Tools was _by consensus_ which included the tool provider:
https://github.com/cardano-foundation/developer-portal/pull/745#issuecomment-1225305259
https://github.com/cardano-foundation/developer-portal/pull/745#issuecomment-1259639075

So moving it was _not_ an error and to move it back is to invite going around in a circle... and therefore reviewing & merging this PR must revisit that consensus, hopefully including the same participants (@cexplorer @katomm @os11k @rdlrt).

**Comment by fill-the-fill** [comment]
> I'm clearing this in honour of the URGENT request, but:
> 
> 1 - I/we've submitted logos alone for most of the last several showcase additions because the result of the last conversation on the subject was that full-screen project images _are not displayed in the portal UI_. To me it seems like common sense therefore that full screen demo pictures have no use unless the contributor doesn't feel like preparing a smaller sized image: [#777 (comment)](https://github.com/cardano-foundation/developer-portal/pull/777#issuecomment-1250023836) [#777 (comment)](https://github.com/cardano-foundation/developer-portal/pull/777#issuecomment-1250030331)
> 
> I posted these questions after spending about 2 hours preparing a detailed screenshot for the project (a composite for the command usage & examples, as you @fill-the-fill had prepared before), only to realise that the portal UI could never be made to display it... not even if viewing the image directly from the showcase listing. The only way to see the full screen image would be to clone or fork the repository, which front line users will not do.
> 
> So if this (Cexplorer) logo is now being replaced by a detailed image, can I ask again less politely but more emphatically this time... when & how does this higher resolution image ever display in the Dev Portal UI?
> 
> 2 - There were 2 PR's which arranged the current Cexplorer / Adaex / Adapools material was it was at the time #800 was merged. I personally checked both of those PR's to be sure they built properly with `staging`. If the portal was failing to build it is likely the result of some merge conflict being resolved improperly which perhaps affected the same section of code.
> 
> 3 - The decision to move Cexplorer effectively from Showcase (by removing the obsolete Adaex and the deprecated Adapool) to Builder Tools was _by consensus_ which included the author: [#745 (comment)](https://github.com/cardano-foundation/developer-portal/pull/745#issuecomment-1259639075) [#745 (comment)](https://github.com/cardano-foundation/developer-portal/pull/745#issuecomment-1225305259)
> 
> So moving it was _not_ an error and to move it back is to invite going around in a circle. That reviewing & merging this PR should revisit that consensus, hopefully including the same participants (@cexplorer @katomm).

1. As I mentioned before, I usually compress images to display. The current image I'm using is 150KB. I've removed the previous image as it was taking only half of the image box.
>
2. There was a PR that removed API tag I believe that was merged before Cexplorer tag, I assume that broke staging. (Tag that Cexplorer was using)
>
3.  I believe I miss-understood the discussion, in my head it's a showcase that is in some way similar to other showcases we have with ecosystem tag

**Comment by rphair** [comment]
> There was a PR that removed API tag I believe that was merged before Cexplorer tag, I assume that broke staging. (Tag that Cexplorer was using).

thanks, that makes sense... since I was editing my last post was you were writing (to add this suggestion) I think it would be a good idea to do a yarn build with the PR `head` before merging.  It seems like the tag shuffle is only one of the things that could prevent a build even with an innocuous looking showcase item change... so it's good to check when a PR is submitted but probably more vital to check *just before merge*.  Otherwise there is a race condition to see if a breaking change can be submitted between that prior test build and after the 3rd reviewer hits the Merge button 🤣

> I believe I miss-understood the discussion, in my head it's a showcase that is in some way similar to other showcases we have with ecosystem tag.

I think it fits better in the Showcase too, so it was with some reluctance that I followed the conclusion of @cexplorer to change it into a Builder Tool.  A good rationale for this would be that "everybody already knows Cexplorer, the new Adapools) but not everybody knows about the compatibility with the new Testnets and the other dev features.  In the PR above they were pressured to choose one or the other, and unless @katomm and I have misunderstood that's the one they chose: a Builder Tool. 🧐

**Comment by fill-the-fill** [comment]
Hmm, but does it really make sense to put Cexplorer into Builder Tools, in my opinion it's a place that adds value to Cardano Developers, but I'm happy to discuss this 🖌️

**Comment by rphair** [comment]
I was actually most comfortable with the idea of having _two different_ landing pages... one suitable for SPOs and delegators (the "pool tool"), in the Showcase, and another with the information about Testnet integration & other dev features, and suggested it here but neither the tool provider or the other reviewers ran with it: https://github.com/cardano-foundation/developer-portal/pull/745#pullrequestreview-1083012494

**Comment by fill-the-fill** [comment]
> I was actually most comfortable with the idea of having _two different_ landing pages... one suitable for SPOs and delegators (the "pool tool"), in the Showcase, and another with the information about Testnet integration & other dev features, in Builder Tools, and offered that here but neither the tool provider or the other reviewers ran with it: [#745 (review)](https://github.com/cardano-foundation/developer-portal/pull/745#pullrequestreview-1083012494)

I like this idea, let's merge this a showcase and I will come up with better tags and description for the builder tool version of it.

**Comment by rphair** [comment]
> (If you believe it's a better idea to use logo as an image, I can try and adjust it)

BTW my last submitted @cexplorer image was from a screenshot of a browser zoom in on the logo... so it enlarged as a vector graphic suitable for display 640 pixels wide without loss of image quality.  And in every view I can get of the Dev Portal UI I cannot view a thumbnail with a linear dimension greater than 640p.  So there is a point at which fine writing in a screenshot will never appear as anything but a blur.

That is what I was trying to avoid by using the Cexplorer logo _and_ reluctantly having to revert our detailed work in https://github.com/cardano-foundation/developer-portal/pull/777#issuecomment-1250030331.  And regardless of file size it might actually hurt the user experience of they're shown detail which they cannot read except as a pattern of text flow. 😓

**Comment by katomm** [comment]
I share Robert's views here and I think this pull request should be two pull requests. One should fix the build problem and one should address the Cexplorer, (if this needs addressing at all) .

**Comment by fill-the-fill** [comment]
I agree with both of you, I've modified this PR to only take care of the issue that breaks current staging.

**Review by rphair — APPROVED** [review]
checked & builds with current `staging` ✔️ confirming @fill-the-fill what you said about the culprit being the tag (`api`) removed from the vocabulary in the meantime 🤓

**Review by rdlrt — APPROVED** [review]

**Comment by rphair** [comment]
help, @katomm ... it's adding extra steps to every PR review not having this merged 🙏

**Review by katomm — APPROVED** [review]

**Pull request merged**
