### PR TITLE
Update builder-tools.js

### PR DESCRIPTION
**Pull request by dynamicstrategies**
added the Cardano Rewards Calculator

### CODE REVIEW

**Comment by katomm** [comment]
Hello, please note that your PR needs to be complete in itself. If you want to fix something from another PR (#429) please do a new commit into the old PR. (this one) (otherwise, the automatic checks will fail)

**Comment by katomm** [comment]
@dynamicstrategies I think this is more an entry for the showcases instead of the builder tools. Can you confirm?

**Comment by dynamicstrategies** [comment]
Hi Tommy, sure let's put into the showcases. I will look in sending you a
new pull request later this evening.

**Comment by katomm** [comment]
I’m closing this mainly because of inactivity. Please feel free to comment in case you want this to be open again.

**Pull request closed without merging**
