### PR TITLE
Update Showcase item Haltscam, including rename to Profiler

### PR DESCRIPTION
**Pull request by HT-Moh**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Updating documentation or Bugfix

We have rebranded our project from HaltScam to Profiler to better align with our evolving mission and ambitions. As our project expands, Profiler now offers more than just crowd-sourcing risky Cardano addresses. As an advanced Cardano explorer centered on wallets, Profiler empowers users to thoroughly investigate their wallets, providing a comprehensive overview of their transactions, tokens, and NFTs, accompanied by engaging and interactive data visualizations.

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
1 - At the time of this writing the domain `haltscam.com` is having network connectivity issues from various places I tested.  The web server appears to be going in & out of accessibility.  My local connection is currently well known in the Cardano community to be poor, but I've tried through a VPN and Tor and also have the same problem.

2 - This could be the same network issue affecting asynchronous parts of the web site, but I get this content flashed for the first few seconds *every time* the front page loads (then warning messages goes away):
Screenshot from 2023-03-22 20-11-57
Both 1 & 2 could have to do with content filtering or blacklisting (I'm on a 4G connection in India: a prime target for these).  Still I would submit that either a) something called an "explorer" needs to be available to the public less exclusively or b) there may be inadvertent consequences of traffic filtering or hosting from a CDN.

I'm sure there are some measures preventing your site from being scraped or probed, but in any case it will be hard for me to do a proper assessment if I'm facing blacklisting myself.

3 - The image is too dense and too tall to display on the thumbnail page properly.

3a - thumbnails display in an aspect ratio of about 2.1:1, so ideally their width is a little more than twice their height... good for logos, not screenshots (unless anamorphic)

3b - width is about 350 px maximum in desktop view, so your text will be unreadable

4 - Your description is too long relative to other `description:` tags in the Portal: the longest currently being less than 250 characters (yours is 30% longer than that).  It would fit nicely if you included only the objective features and removed the sales oriented language.  I do a lot of this kind of editing and would be happy to trim it down to something concise & effective.

**Comment by HT-Moh** [comment]
Thanks for your detailed feedback
- Regarding haltscam.com domain is not in use anymore our new app moved to https://www.profiler.biz 
- There is no blacklisting the web app should be available everywhere
- There are already some measurements in place to prevent the website from being scraped or probed

Did you test [profiler.biz](https://www.profiler.biz)? 

I will update the description and thumbnails image for the showcase

**Comment by rphair** [comment]
ugh, you're right: I read the diff wrong & was using the old domain. 🤪  I'm not seeing any page load or asynchronous problems on the new domain... therefore it looks like only items 3 & 4 above are valid and I'll look forward to checking again after your updates. 😎

**Comment by HT-Moh** [comment]
😀, ok I pushed a new commit, I hope the thumbnails is fine now.

**Review by rphair — APPROVED** [review]
last commits to condense language in the `description:` to keep it objective & concise.

**Review by rdlrt — APPROVED** [review]
Removed yarn.lock modification in this PR

**Comment by rphair** [comment]
thanks @rdlrt - I'm still working on crippled Internet half the day so maybe my `Refresh` button on Files page didn't work... 🤔

Can you please describe what you did above where it says "force-pushed"?  It's different than what I recommended to people [here](https://developers.cardano.org/docs/portal-contribute#i-committed-yarnlock-to-my-pr-branch-what-do-i-do) and I would like to understand any other options.

**Comment by rphair** [comment]
Thanks @rdlrt but this is still not explicit enough for me to understand what you're doing.  Even after all this time, some of this language and procedure about `git` means nothing to me.  For instance I can't see any way to remove `yarn.lock` from any commit without removing it from the branch.

Maybe just this once please you could run through it all from the beginning: what you're doing locally in order to 1) modify someone else's PR _and_ then 2) delete a file from that local branch without deleting it from the repository?  I've asked both these questions on Discord and GitHub a few times each and honestly I'm still improvising when it comes to a few of these things.

**Review by os11k — APPROVED** [review]

**Comment by HT-Moh** [comment]
Is any action needed from my side?

**Pull request merged**
