### PR TITLE
Add Registering a Pool to stake pool documentation

### PR DESCRIPTION
**Pull request by sanskys**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Updating documentation or Bugfix
Replacing register-stake-pool-metadata.md with register-stake-pool.md

### CODE REVIEW

**Review by rphair — APPROVED** [review]
Good to have these additions back in the `staging` workflow... but now more people will have to review them 🤓

**Comment by os11k** [comment]
Sorry for nitpicking, but does TinyURL work okay with GitHub? Can we upload poolmetadata to GitHub and then shorten the URL with TinyURL? I thought when git.io stopped accepting new URLs, GitHub was no longer suitable for pool metadata.

**Comment by os11k** [comment]
I'm thinking to add details how to create transaction with simple copy-paste commands(query UTXOs and etc), so we don't need to calculate fees as it is now in manually:

> which in our case would be 9497237500 - 500000000 - 1000000 = 8996237500

Yes, seems tinyurl should work, as it is recommended by others...

**Review by rdlrt — APPROVED** [review]

**Comment by sanskys** [comment]
> @os11k I have no idea about the GitHub blocking the redirect URI since personally I would never use anything but a static URL for pool metadata. But I have seen it recommended in other Cardano setup guides & therefore haven't discriminated against it here. @sanskys can you verify that TinyURL in fact works with GitHub in your own testnet environment?
> 
> Also @os11k good idea to add the syntaxes in [a2bd26e](https://github.com/cardano-foundation/developer-portal/commit/a2bd26e1510bbbad86870fd7440eae980b21c516) here... I remember needing to know that in the early days & having to confirm it on the Forum so it's good to have it all in one place.

tiny url works fine. Better would be obviously to store it where the url length is small

**Review by fill-the-fill — APPROVED** [review]

**Review by fill-the-fill — APPROVED** [review]

**Comment by rphair** [comment]
@sanskys I assumed this was going into `staging` but I saw that we were missing our merge button... and in fact this PR is for merging into the `main` branch rather than staging.  Looks like it copied the target from your local fork where you were also working on `main`.  I cannot be sure the merge would be a good thing even if we were allowed to do it.

@fill-the-fill @katomm I guess that means this PR has to be re-submitted?  We have work from 3 different contributors in this PR so it would be nice if there were a way at the admin UI of flopping over the target from `main` to `staging`. 🤔

Or: I made a local copy of this @sanskys branch `HEAD` and can try making a new PR from that if @sanskys you would rather do it that way.  If it looks like it contains everybody's changes including @os11k then we can close this one.

**Comment by fill-the-fill** [comment]
> @sanskys I assumed this was going into `staging` but I saw that we were missing our merge button... and in fact this PR is for merging into the `main` branch rather than staging. Looks like it copied the target from your local fork where you were also working on `main`. I cannot be sure the merge would be a good thing even if we were allowed to do it.
> 
> @fill-the-fill @katomm I guess that means this PR has to be re-submitted? We have work from 3 different contributors in this PR so it would be nice if there were a way at the admin UI of flopping over the target from `main` to `staging`. 🤔
> 
> Or: I just made a current local copy of this @sanskys branch `HEAD` and can try making a new PR from that if @sanskys you would rather do it that way. If it looks like it contains everybody's changes including @os11k then we can close this one.

Yeah, I've missed that part too..We can't merge it into `main`. You could potentially change the branch you would like to merge changes to though.

**Comment by rphair** [comment]
> change the branch you would like to merge changes to

@sanskys as the submitter I guess it is up to you to do that, since at the contributor level I don't have this option. 🤓

**Comment by rphair** [comment]
OK, it let me do it in the heading of this pr (only submitter can change it from their own fork's UI I think). 😎

**Pull request merged**
