### PR TITLE
Smart Contracts: expand overview page

### PR DESCRIPTION
**Pull request by OlofBlomqvist**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Updating documentation or Bugfix

The current overview page contains more than a few logical & technical errors, and it also does not seem to be written with developers as the intended target audience.  At least for me, it was of little use when I got started with Cardano.

In this PR I try to make the overview more useful as a general introduction for developers getting started on Cardano, without going in to too much detail

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
Really great content here.  I still don't work with smart contracts so this has been a real pleasure to read.  Only needed some touch up edits mainly for use of English possessive (`-s` vs. `-'s`) and I offset some italicised notes as styled admonitions.

(**p.s.** words spelled 2 different acceptable ways, like `utxo's` and `utxos`, I generally left alone unless spelled 2 different ways in the same sentence)

Will double check now in local build to be sure all still looks good.  Looking forward to signing off on this as soon as you are happy taking it out of Draft review state.

**Comment by rphair** [comment]
Note @OlofBlomqvist GitHub is being slow to connect changes my edits in your branch to this PR.  Here is the latest change (https://github.com/OlofBlomqvist/developer-portal/commit/01c2ec496d5225c4244f6dafbac33064943c3e1b) which I'm still waiting more than 15 minutes to show up in the rendered document & in the diff.  Hope my editing this way has been helpful for you (I'm done for now unless you put in more sections of text).  Thanks again for the brilliant content 🤓

**Comment by OlofBlomqvist** [comment]
> Note @OlofBlomqvist GitHub is being slow to connect my edits in your branch to this PR. Here is the latest change ([OlofBlomqvist@01c2ec4](https://github.com/OlofBlomqvist/developer-portal/commit/01c2ec496d5225c4244f6dafbac33064943c3e1b)) which I'm still waiting more than 15 minutes to show up in the rendered document & in the diff. Hope my editing this way has been helpful for you (I'm done for now unless you put in more sections of text). Thanks again for the brilliant content 🤓

Much appreciated, thanks! :)

**Review by rphair — APPROVED** [review]

**Comment by rphair** [comment]
My commit still not merged with this branch after 35 minutes; so perhaps best to wait for further review until GitHub problem is fixed (my own review was based on content in my local branch): https://www.githubstatus.com
> Investigating - We are investigating reports of degraded availability for Pull Requests.
> Jun 07, 2023 - 16:45 UTC

**Comment by rphair** [comment]
should be OK to review now, along with the rest of GitHub 🤓
> This incident has been resolved. - Jun 7, 18:39 UTC

**Review by rdlrt — APPROVED** [review]

**Review by os11k — APPROVED** [review]

**Pull request merged**
