### PR TITLE
Add NOWNodes to Builder Tools 

### PR DESCRIPTION
**Pull request by AnnaNodes**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have read the [Builder Tool Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/builder-tools.js)
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Builder Tool addition

* Title: *NOWNodes*
* Description: *Get instant access to Cardano RPC nodes, indexer, and WebSocket connection. Start seamless integration on a FREE tariff plan. You can focus on growing your web3 products with us.* 
* Website: https://nownodes.io
* Getstarted: https://nownodes.io/nodes/cardano-ada
* Tags:
  * `websocket`
  * `json`
  * `hosted`

### CODE REVIEW

**Comment by rdlrt** [comment]
Free requests : 1 month only
API requests : 10000/month (~3333/day)
Endpoints:
  Blockbook: 1 (network info)

**Comment by fill-the-fill** [comment]
Agree, definitely something of a showcase

**Comment by AnnaNodes** [comment]
Dear reviewers,

We have access to a full Cardano node, Indexer, WebSocket connection, technical guides, and 24\7 support. 
The Indexer is accessible for any user. This tool has free access.

Please review the service from the utility side.

**Comment by rphair** [comment]
@AnnaNodes if you are insisting that this be reviewed for the Builder Tools section of the portal then, like the other reviewers, I wouldn't be able to proceed any further with this.  I do think it could be a good introduction to users to get acquainted with node APIs, so if this PR were modified to position your tool appropriately in the Showcase section then I would be willing to endorse it.

**Comment by rphair** [comment]
@AnnaNodes FYI it is not enough to add the additional Showcase image.  You will have to remove the Builder Tools image, revert the changes to `src/data/builder-tools.js` (so the file is unmodified), and change the Showcase JS file instead if you want to convert this to a Showcase listing.

**Pull request closed without merging**
