### PR TITLE
Added CNFT.IO the first Marketplace for NFTs on Cardano! 

### PR DESCRIPTION
**Pull request by CNFT-io**
👋👋 Hello there! Welcome. Please follow the steps below to tell us about your contribution.

1. Select **one of the templates below** that fits your contribution
2. Remove this text as well as the other templates
3. Fill in all sections of the template
4. Summon a reviewr using @mentions (optional)
5. Click "Create pull request"

---

## Showcase addition

* Name: *Project name*
* Description: *Describe your project* (See [Showcase guidelines](CONTRIBUTING/#showcase))
* Link:   <link_to_project>
* Source: <link_to_source_code>
* Tags:
  * `analytics`
  * `explorer`
  * `educational`
  * `game`
  * `gateway`
  * `opensource`
  * `pooltool`
  * `metadata`
  * `nativetoken`
  * `nft`
  * `wallet`

 

---

#### Issue

Fixes #issueId

#### Description of the change

---

## Bugfix

Fixes #issueId

#### Description

 

---

### CODE REVIEW

**Comment by CNFT-io** [comment]
h

**Comment by katomm** [comment]
I'm closing this, as there seems no effort at all. (template just pasted, all automatic checks failing, title, comment with only one letter)
Thanks for understanding.

**Comment by CNFT-io** [comment]
We will retry with more effort to ensure it is working.

**Comment by ANGELsCNFTs** [comment]
Name: ANGELsCNFTs
Description: Can you help the project with validation?
Link: https://github.com/Cardano-NFTs/policyIDs/pull/1422

**Pull request closed without merging**
