### PR TITLE
Add cnft (npm package)

### PR DESCRIPTION
**Pull request by Jack-0**
## Showcase addition

* Name: *cnft*
* Description: A library for validating metadata for the 721 metadatum property. Complies with community standards. Future plans to add more cnft utility. 
* Link:   [cnft](https://github.com/ada9000/cnft#readme)
* Source: null
* Tags:
  * `javascript`
  * `typescript`
  * `nft`

### CODE REVIEW

**Comment by Jack-0** [comment]
The tool parses NFT Metadata... here is an example of it in use


1. Nav to: https://ada9000.io/t/nft-meta 
2. Paste in some metadata
``` json
{
  "721": {
    "f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a": {
      "ada9000": {
        "augmentations": [],
        "core": {
          "handleEncoding": "utf-8",
          "og": 0,
          "prefix": "$",
          "termsofuse": "https://adahandle.com/tou",
          "version": 0
        },
        "description": "The Handle Standard",
        "image": "ipfs://QmaZ56m6ScGyzpYnGdSbp3z6jkMU7UZSuy7Azjnw8gzQMm",
        "name": "$ada9000",
        "website": "https://adahandle.com"
      }
    }
  }
}
```

**Comment by rphair** [comment]
@Jack-0 I think this is generally a good addition but your code baseline for this branch is very old and doesn't build (see instructions on front page), I think due some recent changes to the site blog & authorship structure:
```
[ERROR] Error: Blog author with key "cexplorer" not found in the authors map file. ...
    at getAuthorsMapAuthor (/home/rphair/archive/build/developer-portal/node_modules/@docusaurus/plugin-content-blog/lib/authors.js:89:23)
```

Can you please update your fork from the repo upstream and merge these changes in with your working branch, or some equivalent process?  This should also take care of the merge conflict currently reported for this PR.

**Review by rphair — COMMENTED** [review]
This is not a strict requirement, but your logo will fit better in the list of showcase thumbnails if it's in 2:1 aspect ratio... so could you simply edit your logo so the stylised letters are in this arrangement:
**CNFT**

... instead of the current arrangement?
**CN
FT**

**Comment by Jack-0** [comment]
Synced the fork on mobile and it deleted the PR (sorry) :see_no_evil:
New PR -> https://github.com/cardano-foundation/developer-portal/pull/817

**Comment by rphair** [comment]
understood; I've also heard that if you push a deleted or renamed branch it kills the PR with no way to recover 🤪

**Pull request closed without merging**
