### PR TITLE
Add Spectrum Finance project to showcase

### PR DESCRIPTION
**Pull request by yasha-black**
## Showcase addition

* Name: Spectrum Finance
* Description: Spectrum Finance is an open-source cross-chain DEX.
* Link:   https://app.spectrum.fi
* Source: https://github.com/spectrum-finance
* Tags:
  * `favorite`
  * `dex`
  * `token`

### CODE REVIEW

**Comment by fill-the-fill** [comment]
As I understand it doesn't support Mainnet for now, is that correct?

**Comment by yasha-black** [comment]
@fill-the-fill yes, it's correct

**Comment by fill-the-fill** [comment]
> @fill-the-fill yes, it's correct

I believe one of the requirement in Showcase Info section (You can find it on top in `showcase.js` file) is:
* - It has to run on Cardano mainnet.

**Comment by yasha-black** [comment]
@fill-the-fill 
Ok, gotcha. Can we keep this PR open till we release the app in the mainnet?
I will tag you here when the release occurs.

**Comment by katomm** [comment]
Best to reopen when it is live on mainnet.

**Pull request closed without merging**
