### PR TITLE
chore(get-started): updating cardano-node requirements

### PR DESCRIPTION
**Pull request by mmahut**
## Updating documentation

Updating the minimal requirements for cardano-node, they have changed since the last edit.

https://github.com/input-output-hk/cardano-node/releases/tag/1.32.1

### CODE REVIEW

**Review by katomm — APPROVED** [review]
👍

**Comment by rdlrt** [comment]
> minimal requirements for cardano-node

Is that accurate? Those requirements should be for mainnet - we can run node with other networks on much smaller instances (hence, the note after the lines being edited).

Having said that, what we have now is "minimum requirement" either. The IO documentation does not differentiate between component requirements and network

**Comment by os11k** [comment]
I tend to agree with @rdlrt , I do run pool in testnet with 8GB with no problem at all, so this will be misleading to put 12GB there.

**Comment by katomm** [comment]
Could we agree on minimum requirements for different networks?  like @rdlrt suggested. I think that would be brilliant.

|Network          |CPU Cores* |RAM  |Storage |
|:---------------:|:---------:|:---:|:------:|
|Testnet          |2          |4GB  |10GB    |
|Staging          |2          |4GB  |10GB    |
|Mainnet          |2          |12GB |30GB    |

*An Intel or AMD x86 processor with **two or more cores, at 1.6GHz or faster** (2GHz or faster for a stake pool or relay)

**Pull request merged**
