### PR TITLE
Showcase/ShowcaseCard: refactors the component 

### PR DESCRIPTION
**Pull request by will0101**
# Summary
This decouples the `ShowcaseCard` and makes it more "React-y". 

## Note
I'm not sure why other commits are showing up in this branch even though I've tried to `rebase` and `cherry-pick`. Hah, I'm probably missing something though. This is the first open-source project I've ever contributed to.

### CODE REVIEW

**Comment by rdlrt** [comment]
> ## Note
> I'm not sure why other commits are showing up in this branch even though I've tried to `rebase` and `cherry-pick`. Hah, I'm probably missing something though. This is the first open-source project I've ever contributed to.

You might want to try squashing your commit into single one created using updated staging as base 🙂

**Comment by katomm** [comment]
Technically this only looks odd, we can still merge it.

**Comment by will0101** [comment]
@rdlrt Thanks for the tip 😄. I believe it worked.

**Comment by katomm** [comment]
Awesomeness! Please consider removing [WIP] once it is ready.

**Comment by will0101** [comment]
@katomm Done!

**Review by katomm — APPROVED** [review]

**Review by rdlrt — APPROVED** [review]

**Review by Mercurial — APPROVED** [review]

**Pull request merged**
