### PR TITLE
Update showcases.js

### PR DESCRIPTION
**Pull request by TurboEgon**
@katomm

### CODE REVIEW

**Comment by katomm** [comment]
Thank you @TurboEgon for starting the discussion with this PR again as I felt that was a bold claim and so I just edited the text to "one of the first" to merge #129. For me personally, this is still a bold statement, as for example, the first "full on-chain NFT" was likely just a token with the quantity one. 

The project is cool and has my appreciation it's just about the details here. Happy to hear other opinions on this one, also around what does that even mean being a"full on-chain" NFT?

**Comment by MarcelKlammer** [comment]
I think, if the word "interactive" was added to the first sentence as well, the claim might hold true until proven otherwise.

**Comment by TurboEgon** [comment]
Hello together, thank you for commenting!
Althought it is a bold claim it is true in my opinion. Maybe you can call a token with quantity 1 and without image also an "NFT". But if you go that deep you have to proof all the other "first" claims on showcase page which are even more "bold" in that terms in my optinion. For example there is a "The first full on-chain NFT" claim there which is just not true: its not fully on-chian. What about that in terms of this discussion?

I can add "interactive" in the first sentence altought it's not the main feature though if that helps.

**Comment by katomm** [comment]
@TurboEgon I agree with the other claim in the description but it is not relevant for this discussion and btw it was already changed 20 minutes ago. https://github.com/cardano-foundation/developer-portal/commit/7e3f967b4c62caddbcea549fd5f57e0d746392d9 (however not yet merged) 
So let's focus on this one, please.

**Comment by TurboEgon** [comment]
@katomm it's difficult to argue here without using of examples.
I mean if my NFT is not the first 100% on-chain (because technically a token with quantity 1 and without image is an NFT too), then other projects in your showcase are definitly not full on-chain (because they are technicaly stored on IPFS) and not first interactive (because technically there were interactive ones before). Why are these projects not investigated on that level too but mine is? 

@MarcelKlammer: but why then not to let my claim "100% on-chain" -> until proven otherwise?

**Comment by katomm** [comment]
This is an important discussion, and as I see it, we have two options: 

1) Each project determines its description (like it should be), and we do not verify claims. We will probably end up with different projects claiming to be "the first X," and we live with it. 

2) We also review and discuss the previous projects that were mostly not added by PR from the community. (I almost added all of the initial 50 projects) Usually, I just took over the descriptions on the website if they made sense to me, but some were also slightly amended. (Just to make clear that this is not an attack on @TurboEgon)

I'd love to hear more opinions on this, maybe even other options - therefore I summon other contributors to weigh in: 
@Mercurial @tweakch @rcmorano @gufmar @ruttkowa (as well as anyone else who has an idea or opinion on this)

**Comment by TurboEgon** [comment]
Hello @katomm, thank you for pushing this discussion.
Personally I would always prefer a proper peer review process (your option 2). For establishing a level playing field for every project I therefore propose **now**: either to remove the "not added by PR from the community" projects from the showcase (and let them doing the now reviewed PR process again) or add "one of" to their claims as you did with mine or remove the "one of" again from my description, until this discussion has been finished.

**Comment by rdlrt** [comment]
> This is an important discussion, and as I see it, we have two options:
> 
> 1. Each project determines its description (like it should be), and we do not verify claims. We will probably end up with different projects claiming to be "the first X," and we live with it.
> 2. We also review and discuss the previous projects that were mostly not added by PR from the community. (I almost added all of the initial 50 projects) Usually, I just took over the descriptions on the website if they made sense to me, but some were also slightly amended. (Just to make clear that this is not an attack on @TurboEgon)
> 
> I'd love to hear more opinions on this, maybe even other options - therefore I summon other contributors to weigh in:
> @Mercurial @tweakch @rdlrt @rcmorano @gufmar @ruttkowa (as well as anyone else who has an idea or opinion on this)

IMO - showcase should not be a place for advertisement of granular details like which project was first, it's a tribal attribute known to cause rift and conflicts, projects are free to list their wordings on their sites, this probably goes for any existing projects using similar verbiage too.

**Comment by tweakch** [comment]
I'm happy to share my personal opinion.

I think we should remove claims... not because they are false or true but because the description should describe the project and not list claims. Its not always easy to draw a line, I understand, but thats why we are having this discussion. 

I just read all descriptions to get an overview and I count 1 project with the claim *largest* and 5 projects with the claim *first* (including _one of the first_) I'm on my phone, so i might have messed this up but anyways... not too many bold claims in the other 50ish projects. Generally there are pretty good summaries of what the projects are about. (Not all... but most)

I understand that NFTs have a special interest to be *first*, but to me, a description like that takes away something from the project. It reminds me of these comments on twitch where 5 guys hack *first* into the chat all at the same time and are forgotten as soon as the chat fills up.

@TurboEgon I really like your NFT and I think you under sell it by stating it is the first of its kind... in your description you could talk about gravity coded onto the blockchain, or if you used newtons laws of motion to calculate the orbits write about that awesomeness... coin the term for that next gen tech you used. Maybe it sticks. Its an awesome project and hopefully not your **last**.

**Comment by Mercurial** [comment]
> I'm happy to share my personal opinion.
> 
> I think we should remove claims... not because they are false or true but because the description should describe the project and not list claims. Its not always easy to draw a line, I understand, but thats why we are having this discussion.
> 
> I just read all descriptions to get an overview and I count 1 project with the claim _largest_ and 5 projects with the claim _first_ (including _one of the first_) I'm on my phone, so i might have messed this up but anyways... not too many bold claims in the other 50ish projects. Generally there are pretty good summaries of what the projects are about. (Not all... but most)
> 
> I understand that NFTs have a special interest to be _first_, but to me, a description like that takes away something from the project. It reminds me of these comments on twitch where 5 guys hack _first_ into the chat all at the same time and are forgotten as soon as the chat fills up.
> 
> @TurboEgon I really like your NFT and I think you under sell it by stating it is the first of its kind... in your description you could talk about gravity coded onto the blockchain, or if you used newtons laws of motion to calculate the orbits write about that awesomeness... coin the term for that next gen tech you used. Maybe it sticks. Its an awesome project and hopefully not your **last**.

this is a good opinion and sets a good example on what we can include in the guidelines for listing projects in the future, I definitely agree that anything that claims something should be auto declined.

Projects should just describe what the products do and maybe make the claims on their website / GitHub instead.

**Comment by TurboEgon** [comment]
My reason for pointing out the "First fully on-chain"-claim for Stellar Hood description was that it was a big effort to develop this technology and convince the right people to support it. It has never been done before and its a massive technical challange to fit a 3d interactive application inside 16kb tx limit. Please understand that after hundreds hours of work on this technology and finaly releasing my project its just a punch in the face to hear "Your NFT is the same as a quantity 1 token without image and thats why we changed your claim to 'one of the first' without asking".

Having said that:
@tweakch @Mercurial @rdlrt Thank you very much all for your opinion I do agree with you. Project descriptions should say what the project is about rather than making bold claims which may be difficult to proof or to falsify. Instead of wild west conditions it should be more like pointing out interesting featurs of your project. I agree to change my description completly to a narrative focus and not using claims anymore if you remove claims on the other projects also, as you proposed. Please consider that my project is currently the only one which is disadvantaged (by having added a "one of" to the description). All I am asking for is to level the conditions as soon as possible.

**Comment by katomm** [comment]
I have already written to all the projects that this affects and asked for an update, please provide yours if you have a few minutes.

Furthermore, I would like to stress that no one said "your NFT is the same as a quantity 1 token without image and thats why we changed your claim to 'one of the first' without asking" - I was nitpicking on the term “on-chain” and in no way meant to belittle your work. Thank you.

**Review by katomm — CHANGES_REQUESTED** [review]
As discussed, please provide an updated description without using claims like "the first XY".

**Review by katomm — APPROVED** [review]

**Pull request merged**
