### PR TITLE
Add eopsin to builder tools

### PR DESCRIPTION
**Pull request by nielstron**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have read the [Builder Tool Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/builder-tools.js)
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Builder Tool addition

* Title: eopsin
* Description: A simple pythonic programming language for Smart Contracts on Cardano 
* Website:   https://GitHub.com/imperatorlang/eopsin
* Getstarted: https://GitHub.com/imperatorlang/eopsin
* Tags:
  * `cli`
  * `plutus`
  * `python`

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
@nielstron according to dialogue beginning at https://github.com/cardano-foundation/developer-portal/pull/927#issuecomment-1383604076 what do you think of instead adding a page on Eopsin in the same style as Aiken was added in https://github.com/cardano-foundation/developer-portal/pull/926?  To me it makes more sense to define it that way than to add it as a Builder Tool (cc @rdlrt).

**Comment by nielstron** [comment]
I see that aiken is mentioned as a builder tool as well - does it make sense to have it added as both? I am currently working on an article anyways, will push that in a second :)

**Comment by rphair** [comment]
@nielstron thanks for pointing that out... I hadn't noticed Aiken was also listed as a Builder Tool.  Then sure, we should leave that in and I'll wait for your related article before reviewing 😎

**Review by rphair — APPROVED** [review]
OK I can see now that you've submitted the language details as a separate PR: https://github.com/cardano-foundation/developer-portal/pull/929

**Review by rdlrt — APPROVED** [review]

**Review by fill-the-fill — APPROVED** [review]

**Pull request merged**
