### PR TITLE
Modify announcement bar to be closable

### PR DESCRIPTION
**Pull request by fill-the-fill**
Modify announcement bar to be closable

### CODE REVIEW

**Review by rphair — APPROVED** [review]
Just noting @KtorZ's comment that the survey is running through the 29th (4 more days from now) (https://github.com/cardano-foundation/developer-portal/pull/704#issue-1313064636) but does not say the bar _cannot be closable_ before then; only that it should remain there. 🤔

**Comment by fill-the-fill** [comment]
> Just noting @KtorZ's comment that the survey is running through the 29th (4 more days from now) ([#704 (comment)](https://github.com/cardano-foundation/developer-portal/pull/704#issue-1313064636)) but does not say the bar _cannot be closable_ before then; only that it should remain there. 🤔

I believe in case someone already did the survey, it would be annoying to constantly see the announcement bar on top

**Comment by rphair** [comment]
> in case someone already did the survey, it would be annoying to constantly see the announcement bar

I agree & have `display: none`'d web site components in browser style sheets for less... it would be a shame for people to have to do that to the Developer Portal 💔

**Review by rdlrt — APPROVED** [review]

**Comment by KtorZ** [comment]
Note that the survey is ending tomorrow. So we might as well remove the bar 😅

**Review by katomm — APPROVED** [review]
Agree, they should always be closeable.

**Comment by katomm** [comment]
> So we might as well remove the bar

Fine to remove a closeable bar. ☝️😁

**Pull request merged**
