### PR TITLE
Update builder-tools.js

### PR DESCRIPTION
**Pull request by mcvetyty**
## Showcase addition

* Name: *Automint*
* Description: *A Python library that benefits the token & NFT communities. Scripts allow easy wallet management, automatic creation of unlocked and time-locked policy IDs, as well as the ability to quickly: build, sign, and submit transactions, and much more. Note: This library relies on wrapping cardano-cli.
* Link:   [<link_to_project>](https://github.com/creativequotient/automint)
* Source: [<link_to_source_code>](https://github.com/creativequotient/automint)
* Tags:
  * `opensource`
  * `nativetoken`
  * `nft`

### CODE REVIEW

**Comment by rdlrt** [comment]
Thanks for the PR. Minor notes:
1. Would be good to mention that python library relies on wrapping `cardano-cli`
2. The updates to repo seem to have stopped at 1.27.0 (last commit being on May 30), have the CLI changes since been monitored? There are also changes to output syntax from CLI incl. asset representation, I'm not sure if those would pass on 1.3[1-2].0?

**Comment by katomm** [comment]
Please note that all automatic checks are failing. You can reproduce this on your side by running "yarn build".

**Comment by mcvetyty** [comment]
> Please note that all automatic checks are failing. You can reproduce this on your side by running "yarn build".

Thank you both. Please forgive me as I am newer to github. I am trying to upload the preview image as I believe that is one of the failures, but when I go to:

developer-portal/src/data/builder-tools

And click "Upload File" I receive the following error:
Uploads are disabled.
File uploads require push access to this repository.

Is there an alternate way I need to add this file to /builder-tools?

**Comment by katomm** [comment]
@mcvetyty to make a good pull request you should install the developer portal on your local machine. Please see https://developers.cardano.org/docs/portal-contribute/

**Comment by katomm** [comment]
Closing this in favor of #431

**Pull request closed without merging**
