### PR TITLE
Added NFTdot.io entry as per latest requirements

### PR DESCRIPTION
**Pull request by nftdot**
Added NFTdot.io entry as per latest requirements at the end of the list with the thumbnail file. Thanks.

### CODE REVIEW

**Comment by tweakch** [comment]
Hi @nftdot, 
I saw you closed your PR and opened a new one with the requested changes. there is a much simpler way.

If a reviewer asks you to change your PR, you can 
* checkout the branch where your PR is from `git checkout staging`
* make the requested changes
* maybe they asked you to add a file (i.e. a .png) `git add <file>
* commit the requested changes `git commit -m "add image and append showcase"` 
* `git push` 

Your changes will be reflected within your PR (i.e. #182).

**Comment by nftdot** [comment]
Hi,
I was asked by a reviewer as you can probably see to place my NFTdot.io
entry at the end of the list. I wasn't aware of this rule, but had nothing
against it so I did the change and updated the pull, but since I haven't
seen a new review of the corrected  pull in a week now or maybe my resubmit
was not done correctly as per your specs, so I closed it and resubmitted it
from scratch.

Hope this time it is reviewed and approved as it is compliant with all
rules I know so far.

Thank you.

**Comment by nftdot** [comment]
Ho much time does it ussualy takes to approve an entry into the list?

**Review by katomm — APPROVED** [review]
Looks good, thank you for the contribution. 

I'd recommend to also add the "token" tag. You can just push another commit to this branch as long as the pull request is open.

**Comment by katomm** [comment]
> Ho much time does it usually takes to approve an entry into the list?

We haven't collected stats for it yet. You need 3 independent approvals.

**Comment by nftdot** [comment]
Fair enough. So now we know at least that the submission looks good and there isn't anything for me to do but wait for you and other reviewers in your forum to validate it. I think I have seen on this commit already 2 people, so now I guess we need just another one to help us and validate it.

Thank you in advance for your support.

**Review by MarcelKlammer — APPROVED** [review]

**Comment by nftdot** [comment]
@tweakch would you so kind to approve my request so it gets finally approved? Thank you.

**Review by tweakch — APPROVED** [review]

**Comment by nftdot** [comment]
I see there are 3 approvals on this change, but not sure yet on the process as it is our first commit. how does it work to get this pushed live and see the NFTdot.io entry onto the page: https://developers.cardano.org/showcase/ ?

**Comment by katomm** [comment]
Sorry, it is normal that this process takes some time. In the future, please make the PR always against staging, not against the main branch. Thank you.

**Pull request merged**
