### PR TITLE
Add Lending Pond showcase and a new Lending tag

### PR DESCRIPTION
**Pull request by fill-the-fill**
* Name: *Lending Pond*
* Description: *Provide or Receive ada through a smart contract driven P2P lending marketplace using Cardano NFTs as collateral.* 
* Link:  [Lending Pond](https://lendingpond.app)
* Tags:
  * `marketplace`
  * `nftsupport`
  * `lending`

+ Create a new tag called *Lending* for any projects related to Projects that provide lending and borrowing of ada

### CODE REVIEW

**Review by rphair — APPROVED** [review]
a new tag 😎 ... is there a guideline for choosing these colours?

**Comment by fill-the-fill** [comment]
> 

I personally just randomize a colour and make sure similar one doesn't exist yet

**Review by katomm — CHANGES_REQUESTED** [review]
Can we please avoid writing ada in capital letters? Please also [our style guide on this topic](https://developers.cardano.org/docs/portal-style-guide#editorial-style-guide).

**Comment by rphair** [comment]
@katomm my apologies for missing that detail... I know the style rule but my attention was on other parts of the submission 😖

**Comment by katomm** [comment]
Don't worry. This is practically always being done wrong somewhere. Probably that's why it jumps out at me. 🤨

**Review by katomm — APPROVED** [review]
LGTM

**Comment by rphair** [comment]
... short commit to fix merge conflict (a number of projects added to Showcase while this has been under consideration).  Checked with this commit & builds OK with current `staging` ✔️

**Review by oversize — APPROVED** [review]
Build is ok, and others agree. So i will as well.

**Pull request merged**
