### PR TITLE
Add MazzumaGPT to Builder Tools

### PR DESCRIPTION
**Pull request by StarkOsae**
## Checklist
- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have read the [Builder Tool Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/builder-tools.js)
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Builder Tool addition

* Title: MazzumaGPT
* Description: Generate Smart Contract code using AI
* Website:  https://mazzumagpt.com
* Getstarted: https://mazzumagpt.gitbook.io/mazzumagpt-docs/
* Tags:
  * `plutus`

### CODE REVIEW

**Comment by StarkOsae** [comment]
> Very interesting idea; we don't have anything like it on the Developer Portal yet.
> 
> Right now the only mention of Cardano I can find on your site is in a footnote which you have to accordion out from the FAQ on the front page, where it mentions Plutus as a second item after Solidity. Do you have anything we might include as a `getstarted:` link which documents how your system works, both generally and particularly for Cardano & Plutus?
> 
> In fact, do you have _any_ page that fulfills a documentation purpose? (The way it looks today, I have to "create an account" to see anything beyond the front page.) If so you can add it to `getstarted:`... but without it, it wouldn't feel safe to me as a user to use it, or as a reviewer to endorse it.
> 
> Also you have to remove your `yarn.lock` file from your PR, which can be done by following the instructions here: https://developers.cardano.org/docs/portal-contribute#i-committed-yarnlock-to-my-pr-branch-what-do-i-do

Thanks for the feedback.
I've added the link to the project's documentation page and also removed the yarn.lock file

**Comment by rphair** [comment]
thanks @StarkOsae - though the documentation seems to confirm this is Ethereum centred, with all the examples being given for Solidity.  Since the documentation doesn't explain much of how the system works, or what the expectations of Cardano / Plutus users would be (particularly regarding security or verification of smart contracts), I'd have to follow the feedback of other reviewers who work more with smart contract programming.

In the meantime, you may have removed `yarn.lock` from some environment you are using, but it's still present in the branch for this pull request.  One again I would suggest you try the instructions that the link I sent you above, which will work.  When you've removed it properly you'll see that `yarn.lock` will be gone from this page: https://github.com/cardano-foundation/developer-portal/pull/1111/files

**Comment by StarkOsae** [comment]
> thanks @StarkOsae - though the documentation seems to confirm this is Ethereum centred, with all the examples being given for Solidity. Since the documentation doesn't explain much of how the system works, or what the expectations of Cardano / Plutus users would be (particularly regarding security or verification of smart contracts), I'd have to follow the feedback of other reviewers who work more with smart contract programming.
> 
> In the meantime, you may have removed `yarn.lock` from some environment you are using, but it's still present in the branch for this pull request. One again I would suggest you try the instructions that the link I sent you above, which will work. When you've removed it properly you'll see that `yarn.lock` will be gone from this page: https://github.com/cardano-foundation/developer-portal/pull/1111/files

Thanks for the recommendations.
As suggested, we have added Plutus examples in the documentation to make the application more user-friendly for the Cardano community. 
Also, the yarn.lock has been removed and is no longer in the pull request as you directed.

**Comment by rphair** [comment]
@rdlrt @katomm @os11k @fill-the-fill @gitmachtl how could we possibly go about vetting something like this?  There is some building interest in this field (e.g. https://forum.cardano.org/t/nlp-driven-smart-contracts-and-knowledge-tools/120224) but how do we know something built for Solidity just hasn't been resurfaced for Plutus?  And how much would this matter? 🤔

**Review by rphair — APPROVED** [review]
@StarkOsae that's good enough for me.  This needs approval from 2 other reviewers who will all bring their own point of view & I'll tag them to have a look at this. 😎

**Comment by fill-the-fill** [comment]
@StarkOsae I've noticed the link to documentation doesn't work sometimes

**Review by os11k — APPROVED** [review]

**Pull request merged**
