### PR TITLE
NFTdot.io project addition

### PR DESCRIPTION
**Pull request by nftdot**
Adding NFTdot.io project to Cardano Developer Portal.

### CODE REVIEW

**Review by katomm — CHANGES_REQUESTED** [review]
Thank you for the contribution. Please add your project at the end of the array.

**Comment by nftdot** [comment]
Entry added to the end of the file as requested by @katomm

**Review by nftdot — COMMENTED** [review]
I have added the entry at the end of the file as per latest requirements received.

**Comment by katomm** [comment]
Did you close it by accident?

**Comment by nftdot** [comment]
Hi,
No. I was told by another reviewer I need to change the order of the new
entry in the list, so I acted accordingly and closed the request and
resubmitted a new pull with the new entry at the end. Isn't it the correct
process?

Thank you.

**Pull request closed without merging**
