### PR TITLE
Add Pigy Token to the Showcase

### PR DESCRIPTION
**Pull request by PrinzMonty**

### CODE REVIEW

**Review by katomm — APPROVED** [review]
LGTM

**Comment by PrinzMonty** [comment]
Hi! Do you want to know something else? Does anything miss? We have also developed a game where you can swap Pigys for unique Pigys. Currently, still off-chain but hopefully soon with Alonzo Update also on-chain. So we will build more services over time. E.g. a Service (Smart Contract) for SPOs and Delegators to claim the Pigy rewards and for distribution.

Our Pigy Game:
https://pigy.functionally.live/

We chose "Tokens" as our category, we would classify ourselves as a "Community driven Token Project"

Best regards :)

**Comment by katomm** [comment]
Thanks for asking. This project was not yet merged because it got only one approval but it needs three.

**Comment by PrinzMonty** [comment]
> Thanks for asking. This project was not yet merged because it got only one approval but it needs three.

Yes, I had seen that, but I thought I would still ask if everything is ok. But no problem, I can wait ;)

**Review by tweakch — APPROVED** [review]

**Comment by katomm** [comment]
Hello,
this PR has been open for more than 2 weeks and I would like to give you a little feedback about it here. It probably didn't get enough "traction" among reviewers. Please note that showcase projects need to provide a unique value from existing showcase items and need to have enough community reputation.

**My personal suggestions:**  
Close this PR, try to improve it, try to get more traction in the community and come back later. Maybe you could also find other parts in the portal where you can contribute.

**References:**
The current guidelines: https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/showcases.js

Discussions about guidelines: https://github.com/cardano-foundation/developer-portal/discussions

**Review by MarcelKlammer — APPROVED** [review]

**Pull request merged**
