### PR TITLE
Add Carda Station to showcase

### PR DESCRIPTION
**Pull request by cardadev**
Our virtual world is live with users already building, interacting and playing games.

Find out more on our website https://cardastation.com/

### CODE REVIEW

**Comment by cardadev** [comment]
Name: Carda Station
Description: Explore this virtual world on the moon with an in game avatar, and interact with other players through hangouts, games or events.
Link: https://cardastation.com/
Tags: game, nft

**Comment by rphair** [comment]
@katomm perhaps we can use this as a case study to further develop an answer to:

- https://github.com/cardano-foundation/developer-portal/issues/818

- https://github.com/cardano-foundation/developer-portal/discussions/243#discussioncomment-3828268

@cardadev to read you into this discussion (note I'm only one of several reviewers and this is only my assessment): it's proposed that we list only the top 10 NFT projects by commercial activity as ranked on [opencnft.io](https://opencnft.io) (I can see 2 of your mints ranked there currently at # 226 and # 526) but I suggested we also include projects with automated & interactive features of their NFTs: something that could be called a "token economy" rather than just deliberate actions like sale, trading and dialogue.

In case other reviewers agree this special consideration for inclusion: Can you make a case that you _currently_ have this economy?  Based on my own survey of your material, you have a community of people collecting the minted assets with perhaps improvised interaction by the human NFT owners.  If you have built anything automated around these NFTs then I hope you will describe it here.

**Comment by cardadev** [comment]
@rphair Thanks for your comments. I'll respond here, but let me know if I should contribute to the discussion and/or the open issue about the discussion.

I think listing the top 10 NFT projects on opencnft is a good way to start out. But it also leaves out a majority of projects that are contributing in unique ways to Cardano's ecosystem. Your second point about tokens with utility should catch these unique cases that are missed, and perhaps this is where we can make our case to be considered as suggested.

Carda Station's ultimate goal is to build a virtual world where players can interact with each other and play games. Unlike traditional gaming platforms, we store all user assets on the blockchain. This was/is the goal of our mints. They represent a player's inventory within the game.

It's currently live and you can access the virtual world using this link https://www.cardastation.com/play/

If you connect your wallet and you own our NFTs (and some NFTs from other projects as well), you gain access to in game inventory such as rovers, jetpack, companions, etc. If you own a land NFT, you can build your own models and upload them in the world. We have over 1000 builds deployed already from our NFT holders.

The latest video on our twitter page gives a better idea of what you can do in the world at the moment https://twitter.com/Carda_station/status/1577822452998086659?s=20&t=5EW1Ajd8na9DHgliglftAg

If you have any further questions, do let me know.

**Review by rphair — APPROVED** [review]
Thanks @cardadev for the further detail.  Other reviewers: this satisfies my own working definition of "utiltity" - as well as "economy", given that not all economies are based on currency.  Looking forward to hearing what other reviewers think about:
1) whether this project in particular demonstrates NFT "utility" beyond commonplace game mechanics
2) whether "utility" (as defined here & in related threads) should in general be considered a substitute for popularity in qualifying for Showcase listing.

**Review by katomm — APPROVED** [review]
Ok, interesting, LGTM, was playable, I also had some fun on the Hoskinson Loop Track (or similar name)

**Review by rdlrt — APPROVED** [review]

**Pull request merged**
