### PR TITLE
Revamp stake pool course

### PR DESCRIPTION
**Pull request by sanskys**
Issue

Fixes https://github.com/cardano-foundation/developer-portal/issues/641
Description of the change

Adding Chapter -Why Cardano?
Updating Chapter - Introduction.
Resolved merge issues
Please review/ comment/ merge

### CODE REVIEW

**Review by katomm — COMMENTED** [review]
If you move around things, please also create redirects and delete the duplicates. Otherwise it will get messy once we merge it. Please also give your opinions here: #737

**Comment by sanskys** [comment]
Thanks for the comment. My idea was to completely replace the "Operate a stake pool" menu with "stake pool guide" (or whatever we call it finally). So in the end all the relevant content of "Operate a stake pool" will be incorporated inside the "stake pool guide" and the obsolete content will not be taken over. 
Since i am not big fan of deleting stuff, my idea was when "stake pool guide" is ready, merge to "staging" and at the same time disable the menu "operate a stake pool". After some time if everything looks good then we can delete "operate a stake pools". 
Does that make sense, or am i making things too complicated?

**Comment by sanskys** [comment]
Thanks for the hint..will review #737 today

**Review by rphair — COMMENTED** [review]
Using the title *Why Cardano?* has a long precedent in IOHK/IOG marketing but the question is dysfunctional here.  As I understand it (@katomm please correct me if I'm wrong) the phrase *Why Cardano?* is presumed by some unknown third party considering Cardano vs. other blockchains as a home for their application or token.  It's not an appropriate question for someone who's already decided to run a stake pool & nodes on Cardano's PoS network.

The content in this article is very helpful for potential or pending SPO's who haven't yet learned enough about how Cardano works, or what makes Cardano unique, to be effective at provisioning, building, or running their pool.  Therefore I would propose a title explaining literally what's in the document; something like: 

|title|description|
|---|---|
|Stake Pool basics|Why Stake Pools are needed on Cardano & how they work|

**Comment by sanskys** [comment]
> Using the title _Why Cardano?_ has a long precedent in IOHK/IOG marketing but the question is dysfunctional here. As I understand it (@katomm please correct me if I'm wrong) the phrase _Why Cardano?_ is presumed by some unknown third party considering Cardano vs. other blockchains as a home for their application or token. It's not an appropriate question for someone who's already decided to run a stake pool & nodes on Cardano's PoS network.
> 
> The content in this article is very helpful for potential or pending SPO's who haven't yet learned enough about how Cardano works, or what makes Cardano unique, to be effective at provisioning, building, or running their pool. Therefore I would propose a title explaining literally what's in the document; something like:
> title 	description
> Stake Pool basics 	Why Stake Pools are needed on Cardano & how they work

I agree. I will rename to Stake Pool basics

**Comment by sanskys** [comment]
updated the content in new structure from #737 . Please review and merge.

**Review by rphair — APPROVED** [review]

**Pull request merged**
