### PR TITLE
Add dapps-on-cardano showcase

### PR DESCRIPTION
**Pull request by katomm**
This adds https://dappsoncardano.com to showcase

### CODE REVIEW

**Review by rdlrt — APPROVED** [review]

**Review by rphair — APPROVED** [review]

**Review by fill-the-fill — APPROVED** [review]

**Comment by nilscodes** [comment]
Unfortunately, this is using the wrong preview image ^^

**Comment by rphair** [comment]
@nilscodes the existing image is a complete shot of the front page, with all major features... what kind of image would you suggest?

**Comment by katomm** [comment]
Sorry, this was clearly a copy and paste mistake from me.

**Comment by nilscodes** [comment]
We all love copypasta, and I didn't mind seeing the HAZELnet logo twice 😉 Teamwork 🙌

**Pull request merged**
