### PR TITLE
Add Chainport to Showcase

### PR DESCRIPTION
**Pull request by eserilev**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have read the [Showcase Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/showcases.js)
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Showcase addition

* Title: *Chainport*
* Description: *ChainPort is a next-gen hard-security blockchain bridge that lets you hop across EVM chains to Cardano at a click.*
* Website:   [Chainport](https://www.chainport.io/)
* Source: null
* Tags:
  * `bridge`

### CODE REVIEW

**Comment by rphair** [comment]
@katomm @rdlrt @fill-the-fill and other veterans: How come there isn't a tag for _Bridges_... is there a historical reason or content decision behind this?  Could we have this project on the portal without also having Milkomeda?

This project looks legitimate, active and secure for a number of reasons as I see it.  Generally I don't see that it really says anything about Cardano, but since there are still only a handful or bridges supporting Cardano it might make sense to have it here: if we could determine a category in which to list it.

**Comment by fill-the-fill** [comment]
> @katomm @rdlrt @fill-the-fill and other veterans: How come there isn't a tag for _Bridges_... is there a historical reason or content decision behind this? Could we have this project on the portal without also having Milkomeda?
> 
> This project looks legitimate: active and safe according to what I've seen. Generally I don't see that it really says anything about Cardano, but since there are still only a handful or bridges currently supporting Cardano it might make sense to have it here... if we could determine a category in which to list it.



> @katomm @rdlrt @fill-the-fill and other veterans: How come there isn't a tag for _Bridges_... is there a historical reason or content decision behind this? Could we have this project on the portal without also having Milkomeda?
> 
> This project looks legitimate: active and safe according to what I've seen. Generally I don't see that it really says anything about Cardano, but since there are still only a handful or bridges currently supporting Cardano it might make sense to have it here... if we could determine a category in which to list it.

Good suggestion, I agree with creating bridge tag, I could take care of it if everyone is on board

**Comment by rphair** [comment]
Will keep an eye on this & add the new `bridge` tag and approve as soon as https://github.com/cardano-foundation/developer-portal/pull/880 is merged.

**Review by rphair — APPROVED** [review]
Verified locally it works with new `bridge` tag. ✔️

**Review by fill-the-fill — APPROVED** [review]

**Comment by katomm** [comment]
Hello, what type of Cardano wallets are you supporting? For me, it does not seem to work with any of the installed ones.

**Comment by katomm** [comment]
Thanks for the clarification.

**Comment by eserilev** [comment]
we support eternl, nami and yoroi. we are currently working on supporting more cardano wallets

**Comment by rphair** [comment]
@eserilev thanks for supporting Yoroi ⛩

**Review by os11k — APPROVED** [review]

**Pull request merged**
