### PR TITLE
Added cf_CardanoWallet builder tool and programming language tag "coldfusion"

### PR DESCRIPTION
**Pull request by fangio10**
- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have read the [Builder Tool Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/builder-tools.js)
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

* Title: cf_CardanoWallet
* Description: An API wrapper of the official Cardano Wallet written in CFML for ColdFusion / Lucee applications, facilitates communication between a ColdFusion server and the Cardano blockchain via the official cardano-wallet
* Website: https://github.com/fangio10/cf_cardanowallet
* Getstarted: null
* Tags: coldfusion, wallet

### CODE REVIEW

**Comment by rdlrt** [comment]
Not sure what the aim of this PR is, it's a 2 commit repo against cardano-wallet from over a year ago - makes 0 sense or context to add basic cardano-wallet wrapper to dev portal (also, that `cf_` prefix sounds misleading)

**Comment by fangio10** [comment]
really? number of commits and age is irrelevant - it's a tool for cardano and coldfusion developers to facilitate ada payments and other wallet functions on coldfusion based apps.

why would you unilaterally close this without discussion or opinions from others?

**Comment by rdlrt** [comment]
> why would you unilaterally close this without discussion or opinions from others?

Fair enough - have it re-opened now...will let others take the decision 👍🏻

**Review by rphair — CHANGES_REQUESTED** [review]
I think the reservations raised by @rdlrt  are significant.  @fangio10 there will come a day when improvised integrations between Cardano & many proprietary platforms will be floating around and we won't be able to preview all of them here: or a least only the most supported & popular ones.  I agree the linked repository does look pretty thin from the usual signs of maintenance (commits, issues, stars, forks).

Also, since security is a major theme on the Dev Portal documentation & in review criteria, I would not want to "open the can of worms" of endorsing `cardano-wallet` installation on a closed source web server (therefore having `2` security strikes against this configuration).

**Pull request closed without merging**
