### PR TITLE
NFT Update Proposal

### PR DESCRIPTION
**Pull request by katomm**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## NFT Update Proposal

This pull request is my proposal to address NFT category issues that were discussed for example in #243 and #818, but also on the forum and in Discord. In short, this PR: 

1... removes every "NFT project"
2... adds all winners from CNFT awards 2022
3... adds a few handpicked NFTs because of their unique nature/success 

You can just read further for all details and reasoning. Full disclosure: I don't own any of the touched NFT projects. I do own one of the Summit 2023 NFTs from Turf and one from Veritree (they also occur in this pull request but were already in the portal)

## Problem

It was not clear [how to deal with the NFT showcase](https://github.com/cardano-foundation/developer-portal/issues/818). We need clear guidelines, there were several discussions in #243, #818, the forum and discord about this. It goes back to April 2021.

Consider this pull request as my proposal for a solution as we need to move. 

## Discussed Solutions

In the above-linked discussions, these possible solutions were discussed:

- Allow everything, we would soon end up with a huge list and entries that get old pretty fast. We agreed that we don't want to "map out the (NFT) ecosystem". In the end, this is a showcase. (you don't put everything in the showcase)
- Remove everyone but use the X highest ranked NFT on [OpenCNFT](https://opencnft.io/?t=all) or a similar space. (I still think this is interesting, but for now it leads to a lot of open questions, and we would have to adjust it regularly, besides, it was unclear whether most of the volume would actually bring up enough different categories to justify a showcase)
- Add NFT in specific categories that add, from a developer perspective, something interesting or showcase (I worked on this for a while, but I had to drop it because, in the end, people would need to decide again who should win in which category, and who should decide?)
- CNFT Award winners (promising idea, please see below)

## What I did

After playing around with the other options, taking the CNFT award winners sounded most promising: it takes care of [own categories](https://twitter.com/theCNFTawards/status/1485885159329128451), it includes a community voting that is not connected from developer portal reviewers, you would have to update it only once a year and there would be even a future plan. 

Unfortunately the website https://cnft-awards.io seems down now for some reason but the winners are still visible here: https://cnftnews.com/725/, and there is a full video show of the Awards available here: https://www.youtube.com/watch?v=5VjZ8yxpJhM 

To be specific winners are:
- Best digital art: Aeoniumsky - https://twitter.com/aeoniumsky (added)
- Best generative Art: ClayMates - https://twitter.com/The_ClayMates (was already in the portal)
- Best Collectable: SpaceBudz: https://twitter.com/spacebudzNFT (was already in the portal)
- Best Longterm Utility: ViFinance https://twitter.com/VyFiOfficial (added)
- Zeitgeist: Universe.25: https://twitter.com/unv_25 (added)
- Best Community Driven: also ClayMates (ignored as ClayMates are already in)
- Most Innovative: Unsigned Algorithms https://twitter.com/unsigned_algo (added, the interesting case here: it was in the developer portal but the owner wanted it to be removed in #264. I talked to @alexanderwatanabe  on the Summit about this, and I'm confident he is fine with this.
- Most impactful: Hosky  https://twitter.com/hoskytoken  (no comment on this, I'm fine to obey the results of the CNFT awards) (added)
- CNFT of the year 2021: SpaceBuds (ignored as already in)

In addition to the CNFT awards, I handpicked based on what was popular/unique/in the portal:
- ada handle has clearly a use case and achieved a lot of wallet integrations (added)
- interesting generative NFT https://stellarhood.com/ (was already in the portal)
- Similar but with maps https://www.turfnft.com/ (was already in the portal) 
- Veritree, impact challenge https://veritree.com/  (was already in the portal)  
- Cardano Idols for the art/uniqueness
- Cardano Kids, for the sake of history
- Jes Art, due to its uniqueness
- Dead PXL due to its interactives
- 4 Games that were playable, active and created some buzz: Cardano Warriors, Adazoo, Pavia and Cardastation (all 4 were already in the portal)

Remove everything else that is a.) not a category winner and b.) does not fit in the handpicks. To be specific:
- ada monsters
- Canuckz NFTs
- Cardacitiy (the site was no longer available anyway)
- Cardano Gods
- Cardanobits
- Cardinos (the site was no longer responding anyway)
- Cicada Tactics (seems no longer active anyway)
- Crypto Doggies
- Crypto Knitties
- Crypto Mage (project paused anyway)
- H.Y.P.E. Skulls
- Jetchicken
- Kryptoids  (the site was no longer available anyway)
- Politikoz
- The Galgos (the site was no longer available anyway)
- The Hoskinsons (the site was no longer available anyway)

## Future Handling

One question that was often discussed was: if we found a solution how would we do updates in the future? With this CNFT award proposal, we could either add or replace the NFT showcase every year after the awards. (what we do in the future should not be connected with this PR and is open for discussion ofc)

If you've bothered to read this far, thank you, you seem to really care. Cheers!

### CODE REVIEW

**Review by rdlrt — APPROVED** [review]
Awesome to be able to move this, only bit pending IMO is perhaps contribution to portal guidelines, but that can be a seperate PR

**Comment by katomm** [comment]
Yes, I would take care of it and at the same time bring the guidelines from the comment of the *.Js files into the "real" docs and then only post a link to the guidelines in the *.Js files.

**Review by fill-the-fill — APPROVED** [review]

**Review by rphair — APPROVED** [review]
OK, with the latest comment addressed it looks like this is good to go 🤓 ... @katomm I appreciate how the main selection criteria avoids duplication of effort (i.e. between us and the strongly curated "CNFT awards")

**Comment by rphair** [comment]
> Yes, I would take care of it and at the same time bring the guidelines from the comment of the *.Js files into the "real" docs

yes @katomm & also link from the Pull Request template & modify the wording a bit (e.g. I can see from today's https://github.com/cardano-foundation/developer-portal/pull/1019 that this will be a big help)

**Pull request merged**
