### PR TITLE
Add DexoWorlds to the developer showcase

### PR DESCRIPTION
**Pull request by astrojarred**
* Name: DexoWorlds
* Description: DexoWorlds is a collection of pixel art planets created by a student in astrophysics. The concepts behind the art are based on the real cutting-edge field of exoplanet detection and characterization. Collecting all the planets in orbit around the same star will give access to a generative NFT of the star during the second phase of the project. Last month, the project was featured by [IOHK on their Twitter](https://twitter.com/InputOutputHK/status/1414220439937851396) as part of their community showcases. Thanks for the consideration!
* Link:   http://dexoworlds.com/
* Tags:
  * `nft`

### CODE REVIEW

**Comment by tweakch** [comment]
Are those actual Exoplanets or are they from a generated galaxy?

**Comment by astrojarred** [comment]
@tweakch great question! The galaxy is generated, but based off of a typical spiral galaxy like our Milky Way. Everything from the shape of spiral arms to the distribution of stellar types and planet sizes are based on peer-reviewed research papers. As a result, I went with the catchphrase "50% science, 50% art."

Let me know if I can clarify, provide citations, or if you have any other questions!

**Comment by katomm** [comment]
Hello @astrojarred,

thank you for your contribution and for building on Cardano. This PR has been open for more than 3 weeks and I would like to give you a little feedback. Projects need 3 reviewer approvals and it seems the project didn't get enough "traction" among the reviewers. 

Please note that showcase projects need to provide a unique value from existing showcase items - which is especially difficult with many tokens and NFT. Feel free to join the discussion here: #243

**Suggestions:**
* Close this PR, try to improve it, try to get more traction in the community and come back later. 
* Add your project to https://github.com/input-output-hk/essential-cardano as there is an attempt to generate a complete list instead of highlighting specific ones.
* Maybe you could also find other parts in the portal where you can contribute.

**Comment by katomm** [comment]
Closing due to not enough approvals for a long time. Please note that showcase projects need to provide a unique value from existing showcase items, feel free to join the discussion here: #243

**Pull request closed without merging**
