### PR TITLE
Add DCOne Telegram, Discord API to Builder Tools

### PR DESCRIPTION
**Pull request by DCOneCrypto**
### **Builder Tools**

- Name: **DCOne Crypto Telegram, Discord**
- Description: DCOne Crypto Allows users to connect via API to receive information on changes to the Cardano blockchain stake balance about Telegram and Discord
- Link: [click here](https://github.com/DCOneCrypto/StakeAddress-Tracking-Telegram-Discord/blob/main/README.md)
- Tags: `http` , `json`

### Image
- Thumbnail image size 2:1 (600x300)px

### Preview build
- Link: [click here](https://stake-address-tracking-telegram-discord.vercel.app/tools?tags=http&projects=LAST)

### CODE REVIEW

**Comment by rdlrt** [comment]
Not sure how this qualifies as a "builder tool"

**Comment by DCOneCrypto** [comment]
> Not sure how this qualifies as a "builder tool"

Your question is very interesting.

This tool we provide API method and specifically REST API it allows developer teams to connect with us via API & terminal will receive notification of change of stake address balance on Cardano blockchain

So we believe it is a tool & also a utility for users to connect & use and not spend a lot of time programming the function.

**Comment by rdlrt** [comment]
Exactly, it is more end-user facing product than a builder tool 🙂

**Comment by DCOneCrypto** [comment]
> Exactly, it is more end-user facing product than a builder tool 🙂

But we want to contribute to the community. Can you consider it?  😀

Because:
1. It saves time for the programming team
2. We also built APIs to provide
3. We realize our cardano ecosystem doesn't have this product yet.

Hope people have a way of seeing it as "a tool to get a change of stake address balance" 👍

**Comment by rdlrt** [comment]
It's a no-go for me to include very miniscule extension to utilities, furthermore - I strongly feel this is purely user-facing (not builder ), whichever way you decorate it 🙂. If instead it was an open-source discord bot library for interacting with blockchain (or even collection of scripts/tools in a folder) - it would have been a no-brainer.

For example, we dont include 12 different items for [ATADA SPO scripts](https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet) , even if they do different things. You might instead want to edit and generalise your [existing entry](https://github.com/cardano-foundation/developer-portal/blob/e971628f1b362fe175f51e693820dd39d62abe09/src/data/builder-tools.js#L984-L991) to cover your use-cases.

Ofcourse, that's just me - will let others share what they think

**Comment by DCOneCrypto** [comment]
> It's a no-go for me to include very miniscule extension to utilities, furthermore - I strongly feel this is purely user-facing (not builder ), whichever way you decorate it 🙂. If instead it was an open-source discord bot library for interacting with blockchain (or even collection of scripts/tools in a folder) - it would have been a no-brainer.
> 
> For example, we dont include 12 different items for [ATADA SPO scripts](https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet) , even if they do different things. You might instead want to edit and generalise your [existing entry](https://github.com/cardano-foundation/developer-portal/blob/e971628f1b362fe175f51e693820dd39d62abe09/src/data/builder-tools.js#L984-L991) to cover your use-cases.
> 
> Ofcourse, that's just me - will let others share what they think

Thanks for your comment. We'll listen to everyone else's opinions to see if it should be revised.

**Review by rphair — COMMENTED** [review]
@DCOneCrypto this comment says exactly what I was thinking when I saw yet another submission here:

> @rdlrt: For example, we dont include 12 different items for [ATADA SPO scripts](https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet) , even if they do different things.

Also this PR is unacceptable because it was submitted from a really old code base that includes commits from your previous PR's: as you can see above.  Therefore you can also see the "ecosystem map" duplicated again in this submission.

To fix this, you would have to sync your fork with the upstream `developer-portal`, pull in the changes to `staging` locally, and then create a new PR from a branch created from your updated `staging`.  

If you go through that trouble, please seriously consider consolidating your submissions as recommended in https://github.com/cardano-foundation/developer-portal/pull/999#issuecomment-1482253758 since I doubt I could approve it otherwise.

**Pull request closed without merging**
