### PR TITLE
Modify broken link

### PR DESCRIPTION
**Pull request by fill-the-fill**
Fix broken link to CIP mentioned in #689

### CODE REVIEW

**Review by rdlrt — APPROVED** [review]

**Comment by thenic95** [comment]
For me, the link is already working in the main branch. Please check via the link I provided below

https://developers.cardano.org/docs/get-started/technical-concepts

**Comment by fill-the-fill** [comment]
> For me, the link is already working in the main branch. Please check via the link I provided below
> 
> 
> 
> https://developers.cardano.org/docs/get-started/technical-concepts

It redirects to broken page

**Review by rphair — APPROVED** [review]

**Comment by katomm** [comment]
Happy to approve it but I believe it is again this issue #312 it is a problem when using relative links, it seems the only good way to rule this out is to write /docs/something

This seems to be an ongoing thing, also mentioned a few times now like in #628

**Comment by rphair** [comment]
thanks @katomm - I didn't know about the background on the relative pathnames & merged https://github.com/cardano-foundation/developer-portal/pull/687 without being aware of this. 😰

If I understand https://github.com/cardano-foundation/developer-portal/pull/312#issuecomment-924725013 correctly, links to markdown files should always be absolute pathnames beginning with `/docs` until some future version of Docusaurus makes this unnecessary?

- ... and that the correct `href` in the case of this PR would therefore be `/docs/governance/cardano-improvement-proposals/CIP-0001.md`?
- ... and that this qualification _only_ applies to markdown files?

**Comment by katomm** [comment]
@rphair Yes, that's my understanding (but I could be wrong)
More insights on linking to markdown files here: https://docusaurus.io/docs/markdown-features/links

**Comment by katomm** [comment]
@fill-the-fill any update here? Can we just link to /docs/governance/cardano-improvement-proposals/CIP-0001? I'm pretty sure this fixes it.

**Comment by fill-the-fill** [comment]
> @fill-the-fill any update here? Can we just link to /docs/governance/cardano-improvement-proposals/CIP-0001? I'm pretty sure this fixes it.

Works 👍

**Pull request merged**
