### PR TITLE
docs: small fixes and tweaks on CLI governance pages

### PR DESCRIPTION
**Pull request by Ryun1**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 
- [x] I have not committed any changes to `yarn.lock` (or have [removed these changes](https://developers.cardano.org/docs/portal-contribute/#i-committed-yarnlock-to-my-pr-branch-what-do-i-do)).

##### Governance actions page

- Substituting broken links (to my repo) for permalinks based on the CIPs repo
- Updated info around metadata standards, to take into consideration https://github.com/cardano-foundation/CIPs/pull/835
- Fixing typos on governance actions page
- Making the governance actions page more consistent
- Made code blocks use `shell` consistently

##### Other Governance CLI Pages

- Fixed typos
- Made code blocks use `shell` consistently
- Made cardano-cli command indentation consistent

#### Motivation

@gufmar spotted the CIP108 anchor errors and let me know!

### CODE REVIEW

**Comment by Ryun1** [comment]
Ready for review!

**Review by rphair — COMMENTED** [review]
Good to have the code sections with the proper syntax tagging 🤓 (not to mention those spell corrections)

In my own command documentation & scripts I leave the option lines (beginning with `--`) flush left with the command, since the code appears in legible blocks even without indentation.  But I can see the value in standardising on a 2-space indent since in some places here it's unindented and in other places 4 spaces.

So this will be fine with me as long as that typographical standard is imposed everywhere, since that appears to be your intention; though at the time of this posting, these deviations still remain in the branch:
```shell
$ grep "^    --" *
constitutional-committee.md:    --cold-verification-key-file cc-cold.vkey \
constitutional-committee.md:    --cold-signing-key-file cc-cold.skey
constitutional-committee.md:    --verification-key-file cc-cold.vkey > cc-key.hash
constitutional-committee.md:    --verification-key-file cc-hot.vkey \
constitutional-committee.md:    --signing-key-file cc-hot.skey
constitutional-committee.md:    --cold-verification-key-file cc-cold.vkey \
constitutional-committee.md:    --hot-verification-key-file cc-hot.vkey \
constitutional-committee.md:    --out-file cc-authorization.cert
constitutional-committee.md:    --cold-verification-key-file alice-cold.vkey \
constitutional-committee.md:    --cold-signing-key-file alice-cold.skey
constitutional-committee.md:    --cold-verification-key-file bob-cold.vkey \
constitutional-committee.md:    --cold-signing-key-file bob-cold.skey
constitutional-committee.md:    --cold-verification-key-file carol-cold.vkey \
constitutional-committee.md:    --cold-signing-key-file carol-cold.skey

$ grep -n "^--" * | grep -v :---
constitutional-committee.md:316:--cold-script-hash ad31d247bb2549db98020c5a6331732ebe559ad85b5768abbda3eb0d \
constitutional-committee.md:317:--hot-script-hash f5d42214cb2625cfc34e5c0cfb1daceee44a4a3c2e6807ab67cd6adb \
constitutional-committee.md:318:--out-file cc-authorization.cert
register-drep.md:185:--tx-file tx.signed
```

**Comment by Ryun1** [comment]
@rphair 

Good catches!
I have amended via [af07114](https://github.com/cardano-foundation/developer-portal/pull/1303/commits/af07114eadfdd5ee77f24255fd22d86f618af7c1).

> But I can see the value in standardising on a 2-space indent since in some places here it's unindented and in other places 4 spaces.

I just went with two, as it seemed that two was used the most
I don't have strong feelings on it, just wanted to be consistent

**Review by rphair — APPROVED** [review]

**Review by katomm — APPROVED** [review]
Great work @Ryun1

**Pull request merged**
