### PR TITLE
Add NFT Gift Card Creator showcase

### PR DESCRIPTION
**Pull request by minolinpwork**
* Name: Gift Card Creator
* Description: Personalize an NFT Gift Card
* Link:   https://card-creator.shop
* Source: None
* Tags:
  * `minting`
  * `nftsupport`

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
@minolinpwork I am in favour of adding this, but a complete pull request also includes adding your project to `src/data/showcases.js` as in this recent addition: https://github.com/cardano-foundation/developer-portal/pull/726/files

FYI our convention is for all new projects to be added at the end of this array, to make it easier to highlight new additions to the Showcase.

**Comment by fill-the-fill** [comment]
> I've updated the builder-tools.js

I believe you mixed up showcases and builder tools. Your project is a showcase.

Builder tools are tools that add value to Cardano developers and showcases are projects that are build on Cardano

**Comment by minolinpwork** [comment]
I've corrected

**Review by rphair — APPROVED** [review]
OK, looks good now

**Review by os11k — APPROVED** [review]

**Review by fill-the-fill — APPROVED** [review]

**Pull request merged**
