### PR TITLE
Add RoundTable showcase

### PR DESCRIPTION
**Pull request by thenic95**
* Name: RoundTable
* Description: RoundTable multi-signature DApp by ADAO community leverages native script multi-signature features by providing an interface that allows users to generate multi-signature addresses, build transactions in the users’ browsers, and coordinate the witnessing in a peer-to-peer way.
* Link:   https://roundtable.theadao.io/
* Source: https://github.com/ADAOcommunity/round-table
* Tags:
  * `opensource`
  * `wallet`

### CODE REVIEW

**Review by katomm — CHANGES_REQUESTED** [review]
Thank you for adding to the showcase. Please note if you are using the "open source" tag you need to provide the source in the array as well. (you linked the source in the description of the commit already)

(where it says: source: null)

**Review by thenic95 — COMMENTED** [review]
Thanks for letting me know and apolgies. I added the source in the array.

**Review by fill-the-fill — APPROVED** [review]

**Review by fill-the-fill — CHANGES_REQUESTED** [review]
Here is few things I believe you should change.

- Change the `open-source` tag to `opensource` (build doesn't go through since its the wrong tag)

- I propose you to replace the image with this one. The one you're using is too small.roundtable

**Review by thenic95 — COMMENTED** [review]
corrected the "opensource" tag and added an improved image

**Review by katomm — APPROVED** [review]

**Comment by katomm** [comment]
Closing this in favour of #677

**Pull request closed without merging**
