### PR TITLE
Add SCEZ to the project showcase

### PR DESCRIPTION
**Pull request by appiclogics**
## Showcase addition

* Name: Smart Contract Made Easy
* Description: SCEZ is a friendly tool to create Cardano blockchain smart contracts, NFT, native tokens. A complete REST api solution for crypto developers, enthusiasts and entrepreneurs.
* Link:   https://smartcontractsez.com
* Tags:
  * `featured`
  * `nft`
  * `educational`

### CODE REVIEW

**Comment by appiclogics** [comment]
Hello team, we're bringing first of it's kind in Cardano ecosystem the ability to create smart contracts using REST api. It would be awesome to get the project added to showcase

**Comment by katomm** [comment]
Hello and thank you. Besides registration is anything live on this site? (I think I was a little lost)

**Comment by appiclogics** [comment]
@katomm Thanks for checking. 
We've a menu link on the site "Documentation" that has links to mainnet and testnet api doc

documentation - https://doc.smartcontractsez.com/
mainnet - https://api.smartcontractsez.com/index.html
testnet -  https://api-test.smartcontractsez.com/index.html

code samples for the same api - https://github.com/slthomason/SCEZ_code_samples

**Comment by appiclogics** [comment]
@katomm Sorry for the confusion
Code samples is a proper example how to use the REST api

And following is the ui for the same (testnet): 

Currently the testnet and mainnet is for NFT, we're working on api smart contract. Will add the same in these docs and code samples

https://api-test.smartcontractsez.com/index.html
test email:  amit@smartcontractsez.com
pwd: 123456

We also have NFT viewer(for testnet and mainnet). That's helpful for the Cardano commnity since pool.pm  doesn't have testnet viewer
https://view.smartcontractsez.com/

**Comment by rdlrt** [comment]
> Currently the testnet and mainnet is for NFT, we're working on api smart contract

IMO - it's only fair to consider/welcome the PR when the primary feature mentioned on website is fully live on mainnet, as one of the prerequisites for merging any PR.

**Comment by appiclogics** [comment]
@katomm Thanks for checking. I'm sorry but you guys didn't check it. It's not just registration. It's fully live operational project. NFTs are smart contracts as well. We're simplifying it for developers. You can signup and we send api key and you can integrate those api anywhere! All of the cardano functionalities via REST api!

**Comment by appiclogics** [comment]
@katomm @rdlrt Hey guys, sorry for confusion you had but to put to let you know how awesome is it, could you please take a look here: 
https://www.youtube.com/watch?v=xz7KUPPjI-k
https://www.youtube.com/watch?v=xBaWBbQkDWk

We created Youtube videos to make it easy for develoepers.
Please consider to re-open the PR and add the project.

Thanks

**Pull request closed without merging**
