### PR TITLE
Automint - Python library

### PR DESCRIPTION
**Pull request by mcvetyty**
* Name: *Automint*
* Description: *A Python library that benefits the token & NFT communities. Scripts allow easy wallet management, automatic creation of unlocked and time-locked policy IDs, as well as the ability to quickly: build, sign, and submit transactions, and much more. Note: This library relies on wrapping cardano-cli.* (See [Showcase guidelines](CONTRIBUTING/#showcase))
* Link:   [<link_to_project>](https://github.com/creativequotient/automint/)
* Source: [<link_to_source_code>](https://github.com/creativequotient/automint/)
* Tags:
  * `opensource`
  * `nativetoken`
  * `nft`

### CODE REVIEW

**Comment by mcvetyty** [comment]
@katomm I believe I've successfully done what is needed here. Can you please take a look? Appreciate your help!

**Comment by katomm** [comment]
I assume that this replaces #415? Why not just commit to the old PR? :)) It would be easier to keep track of everything.

**Comment by mcvetyty** [comment]
Hi @katomm Yes - it does replace it. I am sorry, but as I mentioned I am newer to github and this was the only way I could figure out how to make it work. Is it OK? Can you remove pull request 415?

**Comment by mcvetyty** [comment]
Hi @katomm - Just checking in to see if there's anything further I need to do in order to get this merged?

**Comment by katomm** [comment]
@mcvetyty nothing further needed from what I can see. (resolving conflicts would be nice but not a requirement)

**Comment by mcvetyty** [comment]
> @mcvetyty nothing further needed from what I can see. (resolving conflicts would be nice but not a requirement)

Thank you @katomm! Can you tell me then the process for getting it merged? Do I just need to be patient, or do I need to actively try and seek other reviewers? Appreciate your help through all of this.

**Comment by mcvetyty** [comment]
@rdlrt Hi there - are you able to conduct your review on this and get it merged? Please let me know if I need to do anything further..

**Review by katomm — CHANGES_REQUESTED** [review]
Like @rdlrt raised in #415 it seems to have stopped support around cardano-node 1.27.0 and while I appreciate that you made a PR there at https://github.com/creativequotient/automint/pull/33, it doesn't look like it will be merged and the use is then questionable as a builder tool at the moment.

**Comment by mcvetyty** [comment]
> Like @rdlrt raised in #415 it seems to have stopped support around cardano-node 1.27.0 and while I appreciate that you made a PR there at [creativequotient/automint#33](https://github.com/creativequotient/automint/pull/33), it doesn't look like it will be merged and the use is then questionable as a builder tool at the moment.

I'm sorry, but I am not following. In response to @rdlrt's comments, my team submitted updates to the latest code 22 days ago (version 1.30.1) so that it is current with the Alonzo era and it works perfectly. You can see the updates at the repository:

https://github.com/creativequotient/automint

The pull request to make these updates was #34, not 33: https://github.com/creativequotient/automint/pull/34

Additionally in that update, detailed examples were added. Does that help clarify things?

**Comment by katomm** [comment]
Thanks for clarifying, and I apologize if I drew hasty conclusions here. I will look into it.

**Comment by mcvetyty** [comment]
> Thanks for clarifying, and I apologize if I drew hasty conclusions here. I will look into it.

Thank you, Tommy! And no need to apologize - I know you all are busy. Just hoping to get this listed before the next CF delegation change.

**Comment by rdlrt** [comment]
> my team submitted updates to the latest code 22 days ago (version 1.30.1) 

Sorry but release notes for 1.32.0 has now been consolidated with appropriate release notes (check breaking changes) - the examples in documentation will be invalid now.

In general tho, my hesitation as a reviewer, **especially for builder tools** :
1. The utility adds very narrow/specific scoped to be across builder community.
2. There was absence of activity for 7 months - _across a hard fork and breaking changes_ , this did not feel right - as changes required are very miniscule.

However, please note that my reluctance to give a thumbs up (in its current state as per above) does not prevent your PR from getting merged (as there are plenty of others who may approve if they feel it's appropriate) 👍🏻

All the best 🙂

**Pull request merged**
