### PR TITLE
Add @dotare/cardano-delegation to Builder Tools

### PR DESCRIPTION
**Pull request by DorienP**
👋 Hello there! Welcome. Please follow the steps below to tell us about your contribution.

1. Please complete a Checklist
2. Fill in all sections of the template
3. Click "Create pull request"

## Checklist

 <-- Please fill the boxes with [x] before submitting a pull request --> 

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have read the [Builder Tool Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/builder-tools.js)
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Builder Tool addition

<-- Provide information for every bullet in the list below. The tags you select must match the tags in your changes to the builder-tools.js -->

* Title: @dotare/cardano-delegation
* Description: A delegation button that uses cip30 to improve the quality of life for developers and delegators.
* Website:   [<link_to_project>](https://www.npmjs.com/package/@dotare/cardano-delegation)
* Getstarted: [<link_to_getstarted_page>](https://www.npmjs.com/package/@dotare/cardano-delegation)
* Tags:
  * `http`
  * `typescript`
  * `javascript`
  * `wallet`
  * `serialization`
  * `operatortool`

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
@DorienP I can't see how the link currently set as `website:` (https://github.com/adabox-aio/ogmios-java-client) contains what's in the `description:` ... can you explain that here or make any necessary changes to your listing if it's a mistake?

I am an average level developer & if I can't see how to apply the code there to create a delegation button, then it needs more explanation somehow: maybe in a separate `getstarted:` page if it's not on GitHub.

Also FYI the thumbnail images appear in a maximum of around 300px wide on the Dev Tools portfolio.  If a user displays one of those images alone in the browser (e.g. right-click > view image) it will be 640px wide.  Neither resolution is high enough to display the code that you have in the project image... so I would recommend replacing it with some kind of logo (or a _very_ concise code example).

**Review by rphair — COMMENTED** [review]
@DorienP after your last commit he link to the `npmjs` package page is more appropriate: but still the animated GIF there is the only documentation I can find on how this package is used... in my opinion this is not enough to endorse the highly sensitive & secure use case of wallet apps.

This is another reason to put more information in the `README` on `npmjs.com` (if you can) and/or make at least a short page here on the Dev Portal to link to your listing through the `getstarted:` field.

I am also very worried that the NPM package page currently points to a nonexistent software repository (the GitHub user exists but there is no repo by this name): https://github.com/dotareio/cardano-delegation

**Comment by DorienP** [comment]
@rphair Hey thank you for catching these. I've correct the issues regarding getting started, again the github repo will be public soon. The code is all visible in the dist folder.

**Comment by rphair** [comment]
thanks @DorienP - the code on the NPM page is helpful & I'll still be watching for when the actual GitHub repo becomes available to the public. It makes all the difference in my opinion for a security auditable project (very important for crypto wallet software) to have an easily visible GitHub issue queue.

I'm also checking to make sure all the category tags included are being used as the other projects here are using them.  Once both these issues seem OK then I can give my own approval to this.  I was kind of surprised & impressed to see that there are almost 5K downloads per week for the NPM package.

**Comment by rphair** [comment]
Note to other reviewers: I can see how all the record-setting number of 7 category terms could be applicable here but 2 or 3 of them seem like a stretch.  I don't want to be too critical here so I would be happy to see what other reviewers think about this.

**Comment by DorienP** [comment]
If I can add my own note or purpose for the tags. This tool is designed for SPOs or anyone who would like to add delegation to what ever app they are building specifically SPO websites, which we see today not have any delegation button.
http - uses https to gather current blockchain data
typescript - written in
javascript - transpiled to
wallet - anything that follows cip30
serialization - CSL and future CML 
operatortool - SPOs should have this kind of access for webdev

**Comment by rphair** [comment]
@DorienP that all sounds applicable to me... I'm just waiting for the repo & homepage links on https://www.npmjs.com/package/@dotare/cardano-delegation to become valid before I give my ✔️ on this 😎

**Comment by DorienP** [comment]
@rphair You run a hard bargain. Okay its open. Just be gentle with me community.

**Review by rphair — APPROVED** [review]
thanks for your flexibility @DorienP and for your contribution... looks like a great component for the community to have 🤓

**Review by os11k — APPROVED** [review]

**Review by fill-the-fill — APPROVED** [review]

**Comment by DorienP** [comment]
Hello @rphair,
Just curious when does staging merge with main?

**Comment by rphair** [comment]
I've asked this before with other members of the Dev Portal team: as far as I know, there is no set schedule for when these merges happen.

**Pull request merged**
