### PR TITLE
cardano-wallet-js

### PR DESCRIPTION
**Pull request by javiertc**
* Name: *cardano-wallet-js*
* Description: *a javascript/typescript SDK for Cardano Wallet with a several functionalities. You can use it as a client for the official cardano-wallet and also to create Native Tokens and NFTs.* 
* Link:  https://www.npmjs.com/package/cardano-wallet-js
* Source: https://github.com/tango-crypto/cardano-wallet-js
* Tags:
  * `opensource`
  * `metadata`
  * `nativetoken`
  * `nft`
  * `wallet`

### CODE REVIEW

**Comment by rdlrt** [comment]
>  a javascript/typescript SDK for Cardano with a several functionalities.

Sorry for knit-picking, but would you mind the description being changed from "SDK for Cardano" to "SDK for cardano-wallet" instead? Since this component is only for specific use cases (typically custodial/private) , the use cases depend accordingly.

**Comment by javiertc** [comment]
Hi @rdlrt the SDK has more functionalities, for example you can create native tokens and also NFTs, that's why we say SDK for Cardano. Also our plan is to keep adding functionalities.

**Comment by rdlrt** [comment]
> you can create native tokens and also NFTs
Yes I see that it builds on using serialisation-libs, and it is much cleaner solution.

> that's why we say SDK for Cardano
SDK for blockchain should/would not depend on intermediate layers like cardano-wallet. A very large core of the SDK here depends on cardano-wallet, where the primary disadvantage is user keys are saved on the instance(s) running the wallet. Any developers starting use of this library should fully understand this constrain, as it limits the applications.

**Comment by javiertc** [comment]
Hi @rdlrt is there anything else we need to do to publish this?

**Comment by javiertc** [comment]
Hi @katomm I closed the other one. Use this one

**Review by rdlrt — APPROVED** [review]

**Review by tweakch — APPROVED** [review]

**Comment by javiertc** [comment]
Hi @katomm can we have your approval? Thanks

**Comment by katomm** [comment]
@javiertc QQ: is it possible to resolve the merge conflicts on your side?

**Comment by javiertc** [comment]
Hi @katomm the conflict is resolved.

**Comment by katomm** [comment]
@javiertc it seems there is a problem with the build. You should be able to reproduce this on your local machine with "yarn build".

**Comment by rdlrt** [comment]
No updates in 22 days

**Pull request closed without merging**
