### PR TITLE
Add LodeWallet to Showcase

### PR DESCRIPTION
**Pull request by luigy**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have read the [Showcase Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/showcases.js)
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Showcase addition

* Title: LodeWallet
* Description: The functional Cardano wallet. LodeWallet exists to provide the simplest possible experience for Cardano deFi users and a familiar experience for deFi users from other ecosystems. We are the first native Haskell light wallet for Cardano, making direct use of existing open-source Cardano Haskell libraries.
* Website:  https://lodewallet.io/
* Source: null
* Tags:
  * `metadata`
  * `nftsupport`
  * `wallet`

### CODE REVIEW

**Comment by rdlrt** [comment]
Reasons for not approving for me:
- While they might be true, I am not sure if phrases `built with haskell` or `first native Haskell light wallet for Cardano, making direct use of existing open-source Cardano Haskell libraries` should be placed in description on showcase, these cannot be verified due to project being closed source. The [contributing guidelines](https://github.com/cardano-foundation/developer-portal/blob/staging/CONTRIBUTING.md#a-word-about-project-descriptions) certainly ask to stay clear of "first ABC"
- For a showcase addition - the overall UI feels a bit unpolished than minimalistic (compared to typhon/flint/nami/eternl..), but that might just be me personally.
- In case it does not get approvals, the wallet is already on [support-faq](https://cardano-community.github.io/support-faq/Wallets/list/) and may also be added to https://essentials.cardano.org instead

**Comment by chobbins** [comment]
> Reasons for not approving for me:
> 
> * While they might be true, I am not sure if phrases `built with haskell` or `first native Haskell light wallet for Cardano, making direct use of existing open-source Cardano Haskell libraries` should be placed in description on showcase, these cannot be verified due to project being closed source. The [contributing guidelines](https://github.com/cardano-foundation/developer-portal/blob/staging/CONTRIBUTING.md#a-word-about-project-descriptions) certainly ask to stay clear of "first ABC"

As an alternative for Description, how about:
"Produced by Obsidian Systems, LodeWallet exists to provide the simplest possible experience for Cardano deFi users and a familiar experience for deFi users from other ecosystems."

> * For a showcase addition - the overall UI feels a bit unpolished than minimalistic (compared to typhon/flint/nami/eternl..), but that might just be me personally.

Yes, seems too subjective to block inclusion or warrant further discussion.

Thanks.

**Review by rphair — COMMENTED** [review]
I can't get behind it either, mostly because of the reasons @rdlrt already pointed out.  If the "simplest possible experience" included anything that the other light wallets had missed, I would happily endorse it: but right now it just provides the same shell as other wallets like Nami but without the breadth of user-demanded features (these tend to be neither superfluous nor distracting).

One feature I'm waiting to see is a browser extension which gives users full web pages rather than a mobile screen translated into a browser popup (like Yoroi has had since the beginning).  The screenshots on the Google Play page tell yet another story of the entire UI being confined by whatever tools & libraries were used to generate the mobile app view.  _Yes_ this is the trend in crypto wallets but _no_ I don't have to like it, and objectively this is just another way in which this wallet fails to distinguish itself (and if did provide this feature, I would also be willing to endorse it).

Another reason I'd endorse it (which I don't see in this case) would be a more explicit, verifiable, _objective_ demonstration of how the wallet's "making direct use of existing open-source Cardano Haskell libraries" provides any benefit for the user.  Until proven otherwise, this is just an implementation detail & marketing premise which is separate from any aspect of the user experience (if only to inspire the user's confidence... _if and only if_ you can justify _why_ that is so).

> @chobbins: Yes, seems too subjective to block inclusion or warrant further discussion.

There is never going to be a case when a reviewer's subjective statement blocks discussion.  By the same token, if a reviewer comes forward with a subjective opinion it means they're prepared to justify it according to their understanding of industry best practice & the content guidelines for the Portal.  As I see it @rdlrt's statement was an _invitation_ to further discussion rather than a closure, as is my own review... and I'll tag a few more reviewers to ensure this opportunity. 😎

**Comment by chobbins** [comment]
> > @chobbins: Yes, seems too subjective to block inclusion or warrant further discussion.
> 
> There is never going to be a case when a reviewer's subjective statement blocks discussion. By the same token, if a reviewer comes forward with a subjective opinion it means they're prepared to justify it according to their understanding of industry best practice & the content guidelines for the Portal. As I see it @rdlrt's statement was an _invitation_ to further discussion rather than a closure, as is my own review... and I'll tag a few more reviewers to ensure this opportunity. 😎

Fair enough! I could have said what I meant better: I disagree with the general statement that LodeWallet lacks polish relative to all other light wallets currently included here. It is unclear what limiting principles would exist for such a conversation and how a fair/objective decision would be made.

In terms of the description, we're happy to change it. Though, it isn't clear how an 'aim to provide the simplest possible experience' (also subjective, to be fair) is different in kind from some of the existing entries including descriptions like:
"Aims to add features most requested by the Cardano community."
"The ultimate wallet experience for the Web, with native NFT and token features, powered by Cardano and third party applications."


Cheers

**Comment by katomm** [comment]
Hello, regarding "first this and that" there was a long discussion about this here: https://github.com/cardano-foundation/developer-portal/pull/167 and an extended discussion here: [https://github.com/cardano-foundation/developer-portal/discussions/176](https://github.com/cardano-foundation/developer-portal/discussions/176)  which ultimately resulted in the rule for adding projects:

> Describe what makes your project special, avoid phrases like "the first this and that". Granular details like which project was first is tribal attribute known to cause rift and conflicts.

Source: [Guidelines for adding showcase projects](https://developers.cardano.org/docs/portal-contribute#add-a-project-to-showcase)

**Review by katomm — CHANGES_REQUESTED** [review]
Description violates the "first this and that rule".: https://developers.cardano.org/docs/portal-contribute#add-a-project-to-showcase

**Pull request closed without merging**
