### PR TITLE
Added the .NET Wallet/Serialization Library to the Tools section.

### PR DESCRIPTION
**Pull request by nothingalike**

### CODE REVIEW

**Comment by Mercurial** [comment]
image
Should we add this to the Get Started  - Builder Tools  category as-well?

**Review by Mercurial — APPROVED** [review]

**Comment by katomm** [comment]
@nothingalike Awesome contribution, like Clark, suggested could you please add it to the sidebars.js file?

**Review by katomm — APPROVED** [review]
Great addition!

**Review by rdlrt — APPROVED** [review]

**Comment by nothingalike** [comment]
@katomm thanks for getting to the sidebar suggestion

**Pull request merged**
