### PR TITLE
Added The Galgos NFT project

### PR DESCRIPTION
**Pull request by thegalgos**

### CODE REVIEW

**Review by rdlrt — APPROVED** [review]

**Comment by katomm** [comment]
Hello,
this PR has been open for almost 2 weeks and I would like to give you a little feedback about it here. It probably didn't get enough "traction" among reviewers. Please note that showcase projects need to provide a unique value from existing showcase items and need to have enough community reputation.

**My personal suggestions:**
Close this PR, try to improve it, try to get more traction in the community and come back later. Maybe you could also find other parts in the portal where you can contribute.

**References:**
The current guidelines: https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/showcases.js

Discussions about guidelines: https://github.com/cardano-foundation/developer-portal/discussions

**Comment by thegalgos** [comment]
Hi @katomm, how you measure enough reputation from the community?

**Comment by katomm** [comment]
> Hi @katomm, how you measure enough reputation from the community?

Community reputation obviously cannot be measured in numbers.

**Review by katomm — APPROVED** [review]
LGTM

**Comment by thegalgos** [comment]
Here is Charles asking why this is not yet merged ;)

Anybody can help? The #CNFT community is asking for this. Thanks!

**Comment by thegalgos** [comment]
Our project is different from the rest as we are developing with smart-contracts to add functionality to our NFTs. Obviously we are waiting for the deployment on the main-net. But for example, these are galgos/dogs and they have a default given name. If you want, you could change its name to the one that you like, this way the NFT is updated based on holder preferences. We burn the token and we mint the same but with updated metadata. This will make them more unique. Another example, we are working a game so your galgo is something that will evolve based on your actions. You can think of a play-to-earn game. If you want more details please let me know, thanks!

**Review by Mercurial — APPROVED** [review]

**Pull request merged**
