### PR TITLE
Add Madax showcase

### PR DESCRIPTION
**Pull request by fill-the-fill**
* Name: *M141X (MADAX)*
* Description: *Cardano metaverse for gamers and businesses that provides you with best virtual world to express yourself and be creative.*
* Link:   [M141X (MADAX)](https://www.info.141x.io)
* Source: [Source](https://github.com/ggcaponetto/141x-game-authorizer)
* Tags:
  * `game`
  * `token`
  * `opensource`

### CODE REVIEW

**Review by rphair — APPROVED** [review]
Looks promising 🤔 ... @katomm the preview image here is 2832x1520 - big like the ones resized in https://github.com/cardano-foundation/developer-portal/pull/720 but size is less than 1MB so I assume it's OK.

**Comment by fill-the-fill** [comment]
> Looks promising 🤔 ... @katomm the preview image here is 2832x1520 - big like the ones resized in https://github.com/cardano-foundation/developer-portal/pull/720 but size is less than 1MB so I assume it's OK.

I compressed the image

**Comment by fill-the-fill** [comment]
Well, not happening.

Screenshot 2022-08-12 at 11 28 43

**Comment by katomm** [comment]
A great example of why we don't want to add projects in coming soon, pre-sale, or sale state. Best to just close the PR then.

**Pull request closed without merging**
