### PR TITLE
Add ADANATOR to Builder Tools

### PR DESCRIPTION
**Pull request by Godspeed-exe**
👋👋 Hello there! Welcome. Please follow the instruction below. 

Click the `Preview` tab and select a PR template:

Add ADANATOR

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
I don't see how we could possibly approve this to be placed among our existing `hosted` services, given that:
- there is no free tier
- there is no online documentation

@Godspeed-exe please post here if I am wrong about either of these observations.

**Comment by Godspeed-exe** [comment]
I wasn't aware of the requirements, I'll get on that! 😄

**Comment by rphair** [comment]
@Godspeed-exe neither of these are "requirements" but rather the ways in which the providers of these hosted services generally invite adoption... which is consistent with the Developer Portal's mission to promote Cardano adoption overall.

**Comment by Godspeed-exe** [comment]
@rphair I've added a free tier and linked to the GraphQL documentation. 
I'm also adding an embedded GraphiQL editor but this being a PITA. 

Let me know if you have any further suggestions or questions!

**Review by rphair — APPROVED** [review]
@Godspeed-exe thanks for adding the free tier: it's a good step forward.  I had been hoping to see some more documentation.  The button link just goes to a viewer for the DB schema rather than any description of your service itself works.

Other reviewers: I found it was possible to get through it in a couple minutes just signing up for the free tier & following the bouncing ball.  I think it's a help to have this on the Dev Portal because it gives people a `cardano-graphql` environment in which they can make 1000 requests per day as they are learning.

@Godspeed-exe do I remember correctly that the price was $50 per month when I did my last review (it's $100 now)?  If so, maybe this is considered to make up for the presentation of a free tier.  In either case, if I were considering one of your enterprise subscriptions I would be put off by the thin & somewhat buggy web site with no documentation about your back end or support commitments.

**Comment by rdlrt** [comment]
No-go for me to review, it's a simple graphql instance(s) served online - fail to see any value-add compared to what's already served via dandelion, the efforts taken (be it this PR itself, the website or documents) feel really discouraging to me

**Comment by rphair** [comment]
@rdlrt this also reflects my own feelings except that I'm also considering the importance of having something even lighter-weight than `dandelion` for educational purposes.  But there is also the issue of professional endorsement of the paid service to consider, which I'd be unwilling to do... but which might be implied by its appearance on the Dev Portal 🤔

**Comment by rphair** [comment]
p.s. @rdlrt now I see: I'd just been looking at Dandelion's Kerberos installation and not the free service referred to [here](https://gimbalabs.com/dandelion) via the [Get Started page for Dandelion](https://developers.cardano.org/docs/get-started/dandelion-apis).  So my assertion that this this service is beneficial based on the free tier was incorrect.

**Review by katomm — APPROVED** [review]
Feels a bit slow, but worked for me

**Pull request closed without merging**
