### PR TITLE
Add new filter to check latest showcases and builder tools 

### PR DESCRIPTION
**Pull request by fill-the-fill**
I'm currently working on a new feature for users to filter showcases and builder tools by latest projects. I would like to hear your opinion on it. 

Currently I'm displaying LAST 10 projects added in the filter. What do you think?

filter

### CODE REVIEW

**Comment by rdlrt** [comment]
It's awesome to add that in, only thing I'd wonder us are you intending it to be default filter?

**Comment by fill-the-fill** [comment]
> It's awesome to add that in, only thing I'd wonder us are you intending it to be default filter?

By default it's showing all of the projects

**Comment by rdlrt** [comment]
Cool, only thing I could think of is name (Last va Latest), but either works (esp. as Latest is 6 letters, mught be less consistent visibly)

**Comment by fill-the-fill** [comment]
> Cool, only thing I could think of is name (Last va Latest), but either works (esp. as Latest is 6 letters, mught be less consistent visibly)
A bit off imo, unless we come up with better design 

Screenshot 2022-08-29 at 11 38 56

**Comment by rdlrt** [comment]
Agree, let's leave it as you have it in PR

**Review by rdlrt — APPROVED** [review]

**Review by rphair — APPROVED** [review]
nice work 🤓

**Review by os11k — APPROVED** [review]

**Comment by thenic95** [comment]
Awesome @fill-the-fill 👍

**Pull request merged**
