### PR TITLE
Revamp stake pool course (up to date content merged) 

### PR DESCRIPTION
**Pull request by fill-the-fill**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Updating documentation or Bugfix

I've created a new branch and merged all of the progress from [Revamp stake pool course](https://github.com/cardano-foundation/developer-portal/tree/revamp-stake-pool-course) to make it up to date. Please take a look before we approve and merge it to staging. `Build` and `Start` works fine, I've checked all markdown files and they work, just making sure we're not missing any content. Thank you!

### CODE REVIEW

**Comment by rphair** [comment]
Could we consider waiting until the last page creation commit is merged into that branch & also include it here, as per @sanskys https://github.com/cardano-foundation/developer-portal/issues/737#issuecomment-1534631656?  Seems like the BP configuration would be an essential part of the new documentation.

**Comment by fill-the-fill** [comment]
> Could we consider waiting until the last page creation commit is merged into that branch & also include it here, as per @sanskys [#737 (comment)](https://github.com/cardano-foundation/developer-portal/issues/737#issuecomment-1534631656)? Seems like the BP configuration would be an essential part of the new documentation.

Shoot, haven't noticed that one

**Comment by fill-the-fill** [comment]
I've updated the target branch from staging to [Revamp stake pool course](https://github.com/cardano-foundation/developer-portal/tree/revamp-stake-pool-course). It makes more sense to continue working on that branch instead of staging.

**Comment by rphair** [comment]
OK @fill-the-fill I can't wait: merging now after checking that builds locally & works fine ✔️ ... it is just too cool to have all the old & new material in once place, even if only a few people can see it now 🤠 ... thanks for doing this

**Pull request merged**
