### PR TITLE
added drunken dragon NFT and game projects

### PR DESCRIPTION
**Pull request by FrancoAra**
---

## Showcase addition

* Name: Drunken Dragon: Inns & Quests
* Description: Drunken Dragon: Inns & Quests is a fantasy inn & tavern simulator. You manage a tavern to attract adventurers to send them into epic quests, every adventurer and furniture in the game is represented by a Cardano native token that you can trade with your friends.
* Link:   https://www.drunkendragon.games/
* Source: 
* Tags:
  * `nft`
  * `game`

### CODE REVIEW

**Comment by KayzerOne** [comment]
Great project with huge potential!!!

**Comment by Korasko** [comment]
This project has a solid roadmap for development, and a great community. The launch of its "Grandmaster Adventurer" NFT's went quite successfully with lot's of support. I believe this project has the potential to become an iconic NFT/Game of the Cardano blockchain.

**Comment by m1-nann** [comment]
Project so far has been quite fair and inclusive for users in terms of assets sales and distribution. It has promising gameplay mechanics with smart contracts in the future. Would be nice to see it added to Cardano projects

**Comment by travioli21** [comment]
I love this community and I cannot wait for this game to come out! Huge potential to become a great play to earn game

**Comment by rdlrt** [comment]
@travioli21 @m1-nann @KayzerOne  - Not a social media, if anything you're hurting the PR by shilling on github

@FrancoAra - At the very least , imo you should combine the two entries - as showcase category does not aim to be a large DB of all projects, but highlights as mentioned in showcase guidelines

**Comment by FrancoAra** [comment]
@rdlrt done :) sorry if my community is pushing this, they really want to see it showcased out of passion, and the PR was left without response for half a month.

**Comment by katomm** [comment]
Sorry @FrancoAra  I think the reviewers (myself included) don't know how to handle the wave of NFT projects without demotivating people. It needs to provide a unique value from existing showcase items. Best to join the discussion here: https://github.com/cardano-foundation/developer-portal/discussions/243

**Comment by katomm** [comment]
Closing due to not enough approvals for a long time. Please note that showcase projects need to provide a unique value from existing showcase items, feel free to join the discussion here: #243

**Pull request closed without merging**
