### PR TITLE
add Mesh SDK to showcase

### PR DESCRIPTION
**Pull request by jinglescode**
👋👋 Hello there! 

I would like to recommend adding [Mesh](https://meshjs.dev/) into Showcase, and tag as `favorite`.

We would like to showcase our interactive documentation (e.g. [smart contract transactions](https://meshjs.dev/apis/transaction/smart-contract) and 10+ more), live demo templates (e.g. [marketplace](https://marketplace-template.meshjs.dev/) and 5 more), UI components (e.g. [connect wallet](https://meshjs.dev/react/ui-components) and 3 more), and all the [guides](https://meshjs.dev/guides) that are onboarding developers daily to build on Cardano.

All the work shown is open source, and highly supported by the community, Cardano Foundation, IOG, and EMURGO.

Do let me know what you think about this PR!

### CODE REVIEW

**Comment by katomm** [comment]
Hello and thank you. Worth to mention that Mesh is already in the Builder Tools. (Which seem to be a better place than showcase section)

**Comment by rphair** [comment]
@jinglescode - given what @katomm said above, our precedent (last discussed for Cexplorer) is that tools candiates for both Showcase and Builder Tools have been included in Builder Tools: as you already are.

Given that, if still leaving this PR open: with the things you've mentioned, what would you consider the user-facing (not dev-specific) features that would make Mesh applicable for the Showcase?

**Comment by jinglescode** [comment]
Hey @rphair and @katomm. Something user-facing might be [Mesh AI](https://ai.meshjs.dev/). Its currently down due to a few changes to the service providers. I'm currently working on an update, maybe this might be a good candidate?

**Comment by katomm** [comment]
It's hard to judge from this search field. In my opinion, the site can be either a builder tool or a showcase. It is in the builder tools already and featured [on last month's dev blog](https://developers.cardano.org/blog/2023-03-21-march) ❤️

**Pull request closed without merging**
