### PR TITLE
Add DCOne Webhook API to Builder Tools

### PR DESCRIPTION
**Pull request by DCOneCrypto**
### **Builder Tools**

- Name: **DCOne Crypto Webhook API**
- Description: DCOne Crypto allows connecting webhook api for developers to receive information on changing stake addresses balance on Cardano blockchain
- Link: [click here](https://github.com/DCOneCrypto/StakeAddress-Tracking-Webhook-API)
- Tags: `webhook` , `api`

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
1 - The provided `website:` link lands on a page with a modal warning message (unless you're logged in before arriving there?):
> Current user did not login to the application!

It looks like this would best be solved by changing the `website:` link to your GitHub link above... users can then read more & be prepared for how your tool is used, rather than landing on an error message as their first impression.

2 - The project image in this PR is an image for _you_... it should be an image _for your tool_, especially since you have another tool submitted in #911 so the image here should represent the "Webhook API" specifically.

**Comment by rdlrt** [comment]
Also:
- remove dconecrypto tag
- stake address =/= wallet, this is wrong information that gets repeatedly passed on
- github link - Ideally, you should not be using source code management for binary objects, it seldom adds value

**Comment by DCOneCrypto** [comment]
> 1 - The provided `website:` link lands on a page with a modal warning message (unless you're logged in before arriving there?):
> 
> > Current user did not login to the application!
> 
> ... and then redirects away from your tool altogether. It looks like this would best be solved by changing the `website:` link to your GitHub link above... users can then read more & be prepared for how your tool is used, rather than landing on an error message as their first impression.
> 
> 2 - The project image in this PR is an image for _you_... it should be an image _for your tool_, especially since you have another tool submitted in #911 so the image here should represent the "Webhook API" specifically.

I have followed your suggestion. Thank you very much

**Comment by DCOneCrypto** [comment]
> Also:
> 
> * remove `dconecrypto` tag, it does not exist
> * stake address =/= wallet, this is wrong information that gets repeatedly passed on
> * github link - Ideally, you should not be using source code management for binary objects, it seldom adds value. The repo contains a single README and the rest are all images (that does not prevent your PR from getting approved, just a suggestion)

I removed the `dconecrypto` tag and edited the documentation as well as the github link (controversial to do Stake Address vs Wallet ) according to your suggestion. It's very good

**Comment by rphair** [comment]
Thanks for your improvements @DCOneCrypto - before we go over this again, can you select a project image other than a screenshot with detail that will never, ever be readable on the Dev Portal built web site?

This is one reason why we suggest that you do a local build (which would have caught the errors about the undefined tag(s))... so you can see what your project image looks like on the Builder Tools portfolio image page.  This image box is at a maximum around 280px wide so would you please pick an image which has at least some text readable at that size?

Not every current project has such an image, but I think that's because editorial preferences have changed over time.  As you can see, project logos work best there: or maybe highly focused screenshots, small enough to be readable.  This isn't a strict requirement but it will help me personally get to reviewing your project faster 🤓

**Review by rphair — COMMENTED** [review]
Thanks for your improvements @DCOneCrypto - before we go over this again, can you select a project image other than a screenshot with detail that will never, ever be readable on the Dev Portal built web site?

This is one reason why we suggest that you do a local build (which would also have caught the errors about the undefined tag(s))... so you can see what your project image looks like on the Builder Tools portfolio page.  This image box is at a maximum around 280px wide so would you please pick an image which has at least some text readable at that size?

Not every current project has such an image, but I think that's because editorial preferences have changed over time.  As you can see, project logos work best here: or maybe highly focused screenshots, small enough to be readable.  This isn't a strict requirement but it will help me personally get to reviewing your project faster 🤓

**Comment by rphair** [comment]
@DCOneCrypto it looks like you just merged in the branch from your other PR.  With all the extra, old commits above and now the extra image file included in this PR, as far as I'm concerned this PR is a write-off and should be closed with another clean PR opened for your submission.

The new logo is better, although given the greater than 2:1 aspect ratio of the thumbnail image boxes I would recommend trimming off the extra black & gold pattern at the bottom, whose only purpose therefore would be to clip your logo if the image doesn't align as you intend.

I've given all the guidance I can on this for now & feel we're going around in circles, so l'll wait to see what some of the other reviewers think before doing anything else on this.

**Review by rphair — CHANGES_REQUESTED** [review]
@DCOneCrypto it looks like you just merged in the branch from your other PR.  With all the extra, old commits above and now the extra image file and Showcases JS included in this PR, as far as I'm concerned this PR is a wipe-out and should be closed: with another clean PR opened for this submission.

The new logo is better, although given the greater than 2:1 aspect ratio of the thumbnail image boxes I would recommend trimming off the extra black & gold pattern at the bottom, whose only purpose therefore would be to clip your logo if the image doesn't align as you intend.

I've given all the guidance I can on this for now & feel we're going around in circles, so l'll wait to see what some of the other reviewers think before doing anything else on this.  I'll be happy to begin from scratch with a new review on a fresh PR, though.

**Comment by DCOneCrypto** [comment]
Close pull request and create new, pull request error from merging branch running internal environment. Thank you everyone and sorry

**Pull request closed without merging**
