### PR TITLE
August 2024 broken link fixes

### PR DESCRIPTION
**Pull request by gufmar**
initial opening commit (more to come)

### CODE REVIEW

**Comment by rphair** [comment]
looks brilliant so far 🤩 ... just please post again when done committing & ready for review.

**Comment by gufmar** [comment]
there is one last link with loading issues reported by our broken link crawler on https://developers.cardano.org/docs/get-started/cardano-cli/governance/create%20governance%20actions/#updating-the-constitution

the IPFS-link to the interim constitution file spinns a long time before timing out. 

Any idea what other link we could use, or how to solve it otherwise?

CC: @CarlosLopezDeLara

**Comment by CarlosLopezDeLara** [comment]
@gufmar it's an ipfs link, you need to use a gateway if you don't have ipfs installed.

**Comment by gufmar** [comment]
ouch right, the crawler does not have the gateway available. 
missed this. 
so let's add ipfs.io to the general ignore lis for the crawler

**Comment by gufmar** [comment]
> ready for review

now

**Review by rphair — APPROVED** [review]
A vast improvement, especially with https://github.com/cardano-foundation/developer-portal/pull/1302 included ⭐

**Review by rdlrt — APPROVED** [review]

**Review by katomm — APPROVED** [review]
Great

**Pull request merged**
