### PR TITLE
Add Book Token showcase

### PR DESCRIPTION
**Pull request by fill-the-fill**
* Name: *Book Token*
* Description: *An NFT marketplace for buying, reading, and selling eBooks and Audiobooks.*
* Link:   [Book Token](https://www.booktoken.io)
* Tags:
  * `marketplace`
  * `nftsupport`
  * `token`

### CODE REVIEW

**Review by rphair — APPROVED** [review]
I'd bookmarked this project a while ago; good to see it here 😎

**Review by os11k — APPROVED** [review]

**Review by rdlrt — APPROVED** [review]

**Comment by rphair** [comment]
@fill-the-fill we seem to be getting more merge conflicts now that all the project additions are getting merged in at exactly the same points in the showcase & builder-tools files (at the end of each array) :nerd_face:

**Comment by fill-the-fill** [comment]
> @fill-the-fill we seem to be getting more merge conflicts now that all the project additions are getting merged in at exactly the same points in the showcase & builder-tools files (at the end of each array) 🤓

Since we don't have build previews anymore it's recommended to run PR build locally before we approve it. I skip doing it sometimes too, but it seems to be the case since we run into a lot of failing this week.

**Comment by rphair** [comment]
yes, I also realised this was happening more & posted here about it (https://discord.com/channels/875366566944968785/875615135035707412/1016688192193314856) in hope there's a generally easier way to grab the PR submitter's commit before doing a test build with it.  Yes this question sounds "lazy" but I'm just trying to ensure I'm using GitHub efficiently & properly.

In any case, we could also say in each of our code reviews that we checked such a local build was successful with that commit on top of `staging` as it existed at that time.

I'm still getting work environment together after some heavy travelling & will plan to merge this + the few others that are outstanding, once I can do some more detailed computer work... I'm sure nobody wants to be the next person who hits the Merge button & breaks `staging` again 🤪

**Comment by rphair** [comment]
OK, my last question was never answered on Discord maybe because it's common knowledge how to create a test environment for a PR.  I didn't know that that GitHub creates a pseudo-branch for each PR and it took [this article](https://devdojo.com/chauhanraunaq878/how-to-fetch-a-pull-request-locally-and-test-it-out-before-merging) for me to figure it out:
- [`upstream` = `git@github.com:cardano-foundation/developer-portal.git`]
- `git fetch upstream pull/725/head:verify-build-725`
- `git checkout verify-build-725`
- [`yarn build` & browser preview]

To update that testing branch from the same PR (I had to do this a couple times in fixing a merge conflict):
- `git pull upstream pull/725/head`

My last question @fill-the-fill: why we aren't doing a test build & preview (re: https://github.com/cardano-foundation/developer-portal/pull/725#issuecomment-1240328169) as part of the CI process, which already has a couple of validation steps.  I would bet there is a history behind this which I don't know as a latecomer but I'd like to see that discussion. 🤓

**Pull request merged**
