### PR TITLE
Adding FabulArt project in projects showcase [2nd attempt]

### PR DESCRIPTION
**Pull request by matteocoppola**
## Showcase addition

* Name: FabulArt
* Description: We are the leading luxury NFTs brand on Cardano Blockchain. We offer exclusive events and fine digital art such as our worldwide-known Roleggs collection: 2000 unique and 3D interactive Fabergè-inspired Eggs.
* Link: https://fabul.art
* Tags:
  * `nft`

### CODE REVIEW

**Comment by matteocoppola** [comment]
@rdlrt @katomm may we ask what's the average approval time? We just want to be sure the pull request is fine this time :)

**Review by SavvasSacheshChandrangathan — APPROVED** [review]

**Comment by rdlrt** [comment]
> @rdlrt @katomm may we ask what's the average approval time? We just want to be sure the pull request is fine this time :)

Yes, PR structure (syntaxially) is fine this time (y) .

Typically unanimous approvals are pretty quick (within few days), but judging NFT/marketplace projects is a very opinionated topic, please check out the discussion [here](https://github.com/cardano-foundation/developer-portal/discussions/243). The lesser the claims on showcase description (eg: first of ABC, leading DEF, etc), the less is hesitation with approval. Note that there are over 20 independent community approvers - not affiliated to any federation entities - who could potentially approve a PR, while the PR itself just needs 3 🙂 

For me personally - what stops me from approving PR to have approvals (and yes, these are very difficult to judge - and might depend on perspective, hence the linked discussion):

- It has to have enough community reputation.
- The GitHub account must have a history/or already be known in the Cardano community.

Besides, for quality on showcase entry:
- site performance makes it difficult to browse swiftly

**Comment by matteocoppola** [comment]
> 
> 
> > @rdlrt @katomm may we ask what's the average approval time? We just want to be sure the pull request is fine this time :)
> 
> Yes, PR structure (syntaxially) is fine this time 👍🏻 .
> 
> Typically unanimous approvals are pretty quick (within few days), but judging NFT/marketplace projects is a very opinionated topic, please check out the discussion [here](https://github.com/cardano-foundation/developer-portal/discussions/243). The lesser the claims on showcase description (eg: first of ABC, leading DEF, etc), the less is hesitation with approval. Note that _there are over 20 independent community approvers_ - not affiliated to any federation entities - who could potentially approve a PR, while the PR itself just needs 3 🙂
> 
> For me personally - what stops me from approving PR to have approvals (and yes, these are very difficult to judge - and might depend on perspective, hence the linked discussion):
> 
>     * It has to have enough community reputation.
> 
>     * The GitHub account must have a history/or already be known in the Cardano community.
> 
> 
> Besides, for quality on showcase entry:
> 
>     * site performance makes it difficult to browse swiftly

Hello rdlrt, thanks for your answer!
For the community reputation you may check our Twitter account or our Discord, we have already an amazing community.
Regarding the GitHub account, the account I'm using doesn't have much interaction with Cardano codebase but I've given a hand on the Cardano Telegram Devs Group about stateful smart contracts last October :)

For the last point, are you having problems browsing our website? If so, please let me know which pages don't load properly, we'll fix them asap!

**Comment by matteocoppola** [comment]
Hello @rdlrt @katomm, is there any other approver that we could tag to get the approving reviews needed? Thank you!

**Comment by katomm** [comment]
Sorry, I can only refer again to #243.

**Comment by matteocoppola** [comment]
> 
> 
> Sorry, I can only refer again to #243.

Hey @katomm , I've read the discussion. It's correct that you want projects that showcase what you can do on Cardano. In fact we are the first luxury NFTs project on Cardano. Considering that some famous style brands are going to do that, it would be cool to show that you can adopt Cardano for this purpose.
Maybe we can change the project image with a cool HD render of a luxury Roleggs?
For example this one: https://fabul.art/wp-content/uploads/elementor/thumbs/Rend_01-pcqi3447xvza1tcozr0qcl2itfool8ot531ipusafg.png

**Comment by katomm** [comment]
Closing due to not enough approvals for a long time. Please note that showcase projects need to provide a unique value from existing showcase items, feel free to join the discussion here: #243

**Pull request closed without merging**
