### PR TITLE
Revamp stake pool course | Adding Register Stake Pool

### PR DESCRIPTION
**Pull request by sanskys**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Updating documentation or Bugfix
Revamp stake pool course | Adding Register Stake Address

### CODE REVIEW

**Comment by fill-the-fill** [comment]
I assume this can be merged?

**Comment by rphair** [comment]
@fill-the-fill it can be merged but I haven't had a chance to proofread or edit it yet (email sitting tagged in my Inbox), which I've been doing for the other pages in this branch... just stuck in 2 day personal project for 1 more day 😬

**Review by rphair — COMMENTED** [review]
Thanks @fill-the-fill & @sanskys for waiting for me to catch up.

Last commit was the usual edit for English language usage and formatting as with other Dev Portal pages.  There was also an inconsistency between the names `params.json` and `protocol.json` which I fixed but you can double-check.

Mainly, why are we still using `--testnet-magic 1` on all the commands here?  I thought the target for the documentation in this branch has consistently been `mainnet`. 🤔

**Comment by sanskys** [comment]
> Thanks @fill-the-fill & @sanskys for waiting for me to catch up.
> 
> Last commit [0285fd9](https://github.com/cardano-foundation/developer-portal/commit/0285fd93cfbaec3160ff5ab7107abf819e152510) was the usual edit for English language usage and formatting as with other Dev Portal pages. There was also an inconsistency between the names `params.json` and `protocol.json` which I fixed but you can double-check.
> 
> Mainly, why are we still using `--testnet-magic 1` on all the commands here? I thought the target for the documentation in this branch has consistently been `mainnet`. 🤔

thanks for the changes..all looks good 👍 
the tutorial is for Production Testnet - Please review the following text in relay-configuration
"The focus of this tutorial is on learning how to setup a stake pool. So we will go through the steps of configuring the relay on a [testnet network] and not the Mainnet."

**Review by rphair — APPROVED** [review]

**Pull request merged**
