### PR TITLE
Update acca project image

### PR DESCRIPTION
**Pull request by matiwinnetou**

### CODE REVIEW

**Review by rphair — COMMENTED** [review]
I can understand why you need to get rid of the Aiken logo but in a couple ways this is the first request of its type:

- it's the only photographic image among 200 screenshots and vector images/logos
- although currently consistent with what's on the GitHub repo, it seems ultimately chosen for its anatomical significance 😵‍💫

If this is a placeholder for another image while a logo is designed I would personally prefer to wait for that logo rather than approve this right away.  Or even `acca` in a courier font, and maybe the Aiken colours, would do better than what's here.

I'm not a member of the Aiken culture so I hope I'm not spoiling any inside jokes by not going along with this just yet 😆 ... but I'll approve if the other people on the team think it's OK.

**Comment by rdlrt** [comment]
I looked up and it seems to be a reference to the fruit [Feijoa](https://en.m.wikipedia.org/wiki/Feijoa_sellowiana) also known as 'acca' , tho I do agree about the resemblance - without the context 😄 

I will wait for a confirmation from @matiwinnetou

**Comment by rphair** [comment]
yes, I also looked it up when the listing was originally added & noted its comparisons to the Guava of the same significance in the computer field... so no worries over the similarities between these two fruits 😅

**Comment by matiwinnetou** [comment]
Guava is a popular library in the java ecosystem, acca is a tribute to it. Acca's project homepage already has this fruit.

**Comment by rphair** [comment]
@matiwinnetou this last comment just states what we already knew (and mentioned above in earlier comments) and doesn't address the reservations in

**Comment by matiwinnetou** [comment]
@rphair this, this is the logo, I am not planning any other logo for it.

**Review by gufmar — APPROVED** [review]
interesting logo choice. LGTM

**Comment by rdlrt** [comment]
> I can change logo if people think this is Not Safe For Work a bit but it has to be acca fruit.

That'd be much easier to approve (not attract controversy) 😄

**Comment by matiwinnetou** [comment]
If I change the picture, will PR be merged?

**Comment by matiwinnetou** [comment]
@rphair - I changed the project image.

**Review by rdlrt — APPROVED** [review]

**Review by katomm — APPROVED** [review]

**Comment by matiwinnetou** [comment]
Please merge and release if possible.

**Comment by matiwinnetou** [comment]
It is merged but when will it be released, wasn't that master is automatically releasable?

**Comment by katomm** [comment]
@matiwinnetou it is now in staging, that means live on https://staging-dev-portal.netlify.app, we will push to main branch later this week.

**Pull request merged**
