### PR TITLE
Add Cardano ecosystem interface on DCOne

### PR DESCRIPTION
**Pull request by DCOneCrypto**
### **Checklist**

☑️ Explore over 200+ projects and view the cardano ecosystem interface map and keep growing ([click here](https://dconecrypto.finance/ecosystem-map.html))

### **Builder**

- Name: **DCOne Crypto**
- Description: Cardano ecosystem interface map showing all projects and dapps on the Cardano blockchain (ADA)
- Link: [click here](https://dconecrypto.finance/ecosystem-map.html)
- Tags: `ecosystem`

### CODE REVIEW

**Comment by rphair** [comment]
This is a re-submission of https://github.com/cardano-foundation/developer-portal/pull/911 which was closed for reasons given in https://github.com/cardano-foundation/developer-portal/pull/911#issuecomment-1482928938: not accepted by the required 3 reviewers.

**Comment by DCOneCrypto** [comment]
> This is a re-submission of #911 which was closed for reasons given in [#911 (comment)](https://github.com/cardano-foundation/developer-portal/pull/911#issuecomment-1482928938): not accepted by the required 3 reviewers.

How can I get feedback from other reviewers, or get the other 2 approved reviews. We'd love to know the specifics of everyone else in the review

**Comment by rphair** [comment]
@DCOneCrypto they will all see this new PR and the fact that it was closed.  The specifics are that if they thought this was appropriate for the Developer Portal they would have approved it in #911.  You've already listed yourself on "essential Cardano" so maybe try posting something on the [Cardano Forum](https://forum.cardano.org/) to get some more engagement with your site.

**Comment by DCOneCrypto** [comment]
> @DCOneCrypto they will all see this new PR and the fact that it was closed. The specifics are that if they thought this was appropriate for the Developer Portal they would have approved it in #911. You've already listed yourself on "essential Cardano" so maybe try posting something on the [Cardano Forum](https://forum.cardano.org/) to get some more engagement with your site.

If #911 has been closed, can people come back to approve it later? The product is currently getting a lot of attention, but we don't get reviews that approve feedback from everyone. We're asking people to reconsider? Thank you @rphair

**Comment by rphair** [comment]
@DCOneCrypto I'll ping some other reviewers in case they choose to post anything more explicit here.  As @katomm said in the previous thread, thanks again for your effort and for your submission.

**Comment by DCOneCrypto** [comment]
> @DCOneCrypto I'll ping some other reviewers in case they choose to post anything more explicit here. As @katomm said in the previous thread, thanks again for your effort and for your submission.

Thank you very much  @rphair . Hope everyone reviews help us with the tag "ecosystem". We are working hard you can find it at [https://twitter.com/DCOneCrypto](https://twitter.com/DCOneCrypto) . Thank you everyone @all

**Comment by DCOneCrypto** [comment]
Heya @all

We have finished closing the project and approved all. Please consider our project to be displayed and introduced to the cardano community
https://docs.google.com/spreadsheets/d/1bfnWFa94Y7Zj0G7dtpo9W1nAYGovJbswipxiHT4UE3g/edit?usp=sharing

Thanks all
View complate link and project id 900078 at

**Comment by DCOneCrypto** [comment]
Heya @rphair @rphair @os11k @fill-the-fill 

DCOne Crypto added to the project by Catalyst good reports & good examples of PoA completion for the cardano community

<h1 align="center">

</h1>


You can see it here: https://docs.google.com/document/d/17TvVe5nnzvZgOHFR2GQjnhUWjUwBxIA9Iebld9u0RN0/edit?pli=1#heading=h.z772tp79u0gz

I hope everyone considers our project

**Pull request closed without merging**
