### PR TITLE
Add DCOne Telegram, Discord API to Builder Tools

### PR DESCRIPTION
**Pull request by DCOneCrypto**
### **Builder Tools**

- Name: **DCOne Crypto Telegram, Discord**
- Description: DCOne Crypto Allows users to connect via API to receive information on changes to the Cardano blockchain stake balance about Telegram and Discord
- Link: [click here](https://github.com/DCOneCrypto/StakeAddress-Tracking-Telegram-Discord/blob/main/README.md)
- Tags: `http` , `json`

### Image
- Thumbnail image size 2:1 (600x300)px

### Preview build
- Link: [click here](https://stake-address-tracking-telegram-discord.vercel.app/tools?tags=http&projects=LAST)

### CODE REVIEW

**Comment by DCOneCrypto** [comment]
We have created a new PR @rphair @rdlrt 

Old PR info at: https://github.com/cardano-foundation/developer-portal/pull/999

Thank you for your patience. Come back to us. 🙂

**Review by rphair — COMMENTED** [review]
All the reasons not to approve this that were mentioned in https://github.com/cardano-foundation/developer-portal/pull/999#issuecomment-1482253758 and https://github.com/cardano-foundation/developer-portal/pull/999#pullrequestreview-1356262879 still apply here, since neither the submission or its scope have changed from the older PR as we suggested.

Also I am not tagging this as a `Builder Tool` for the reason @rdlrt already mentioned in https://github.com/cardano-foundation/developer-portal/pull/999#issuecomment-1482236095.

**Comment by katomm** [comment]
In addition to what the others said it's the best to keep updates in one pull request. (#999)

**Comment by DCOneCrypto** [comment]
> All the reasons not to approve this that were mentioned in [#999 (comment)](https://github.com/cardano-foundation/developer-portal/pull/999#issuecomment-1482253758) and [#999 (review)](https://github.com/cardano-foundation/developer-portal/pull/999#pullrequestreview-1356262879) still apply here, since neither the submission or its scope have changed from the older PR as we suggested.
> 
> Also I am not tagging this as a `Builder Tool` for the reason @rdlrt already mentioned in [#999 (comment)](https://github.com/cardano-foundation/developer-portal/pull/999#issuecomment-1482236095).

Thanks for your comment. We will develop a library of telegram bots, discord for it to interact directly and this is also a good idea

**Comment by DCOneCrypto** [comment]
> In addition to what the others said it's the best to keep updates in one pull request. (#999)

Thank you for your comment, Because pull request #999 contains an old pull request #911 (ecosystem) so we have to create a new one, it's unintentional

**Pull request closed without merging**
