### PR TITLE
Add PinkSale project

### PR DESCRIPTION
**Pull request by pinkmoonfinance**
* Name: *Project name*
* Description: *PinkSale is a protocol aiming to provide users with the capabilities to launch their own token and create their own initial token sale. No code is required, simply navigate through our terminal and design your own token and token launch with just a few clicks.*
* Link:   https://www.pinksale.finance/
* Source: https://github.com/pinkmoonfinance/pinksale-contracts
* Tags:
  * `pooltool`

### CODE REVIEW

**Comment by rdlrt** [comment]
You cannot set featured tag yourself

**Comment by pinkmoonfinance** [comment]
> You cannot set featured tag yourself, nor is the linked site related to pools (to use pooltool tag)

Edited, please review my request

**Comment by katomm** [comment]
Hello @pinkmoonfinance ,

thank you for your contribution and for building on Cardano. This PR has been open for more than 3 weeks and I would like to give you a little feedback. Projects need 3 reviewer approvals and it seems the project didn't get enough "traction" among the reviewers. 

Please note that showcase projects need to provide a unique value from existing showcase items - which is especially difficult with many tokens and NFT. Feel free to join the discussion here: #243

**Suggestions:**
* Close this PR, try to improve it, try to get more traction in the community and come back later. 
* Add your project to https://github.com/input-output-hk/essential-cardano as there is an attempt to generate a complete list instead of highlighting specific ones.
* Maybe you could also find other parts in the portal where you can contribute.

**Comment by pinkmoonfinance** [comment]
hi there, please approve my PR

**Comment by katomm** [comment]
Closing due to not enough approvals for a long time. Please note that showcase projects need to provide a unique value from existing showcase items, feel free to join the discussion here: #243

**Pull request closed without merging**
