### PR TITLE
Add Cardano Signer builder tool

### PR DESCRIPTION
**Pull request by fill-the-fill**
* Name: *Cardano Signer*
* Description: *Tool to sign data with a Cardano-Secret-Key and verify data with a Cardano-Public-Key*
* Link:  [Cardano Signer](https://github.com/gitmachtl/cardano-related-stuff/tree/master/cardano-signer)
* Source: [Cardano Related Stuff](https://github.com/gitmachtl/cardano-related-stuff)
* Tags:
  * `operatortool`

### CODE REVIEW

**Review by rdlrt — APPROVED** [review]

**Review by rphair — COMMENTED** [review]
@fill-the-fill nice little tool but `staging` doesn't build with this PR because the image filename itself is spelled wrong (`singer` instead of `signer`), though it's been corrected in the source code...
```
Module not found: Error: Can't resolve './builder-tools/cardano-signer.png' in '/home/rphair/archive/build/developer-portal/src/data'
[ERROR] Client bundle compiled with errors therefore further build is impossible.
```

**Comment by fill-the-fill** [comment]
> @fill-the-fill nice little tool but `staging` doesn't build with this PR because the image filename is spelled wrong (`singer` instead of `signer`)...
> 
> ```
> 
> Module not found: Error: Can't resolve './builder-tools/cardano-signer.png' in '/home/rphair/archive/build/developer-portal/src/data'
> 
> [ERROR] Client bundle compiled with errors therefore further build is impossible.
> 
> ```

Ahh my bad, didn't test after latest commit, on it

**Review by rphair — APPROVED** [review]
builds properly with current `staging` ✔️

**Review by katomm — APPROVED** [review]

**Comment by katomm** [comment]
Always happy to approve tools from @gitmachtl , but why is the source NULL as it is clearly there? https://github.com/gitmachtl/cardano-related-stuff

**Comment by fill-the-fill** [comment]
> Always happy to approve tools from @gitmachtl , but why is the source NULL as it is clearly there? @fickevics-makor https://github.com/gitmachtl/cardano-related-stuff

Done

**Comment by gitmachtl** [comment]
hi guys, would it be possible that you update the screenshot with the new version? just released 1.4.0 which brings a lot of updates, new syntax and CIP-8 support. thx!

**Pull request merged**
