### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jbarros35**
add cheff.png

### CODE REVIEW

**Comment by jbarros35** [comment]
HI, I need to add my NFT explorer project
https://apps.apple.com/us/app/cheff-nft-explorer/id1572987723
its in AppStore already.
thanks

**Review by katomm — CHANGES_REQUESTED** [review]
Thank you for participating here. Unfortunately, this pull request can not be merged because of:

* Project does not follow the showcase guidelines. In particular: website

**Comment by jbarros35** [comment]
I don't understand the rule for websites, this is the official appstore link. I changed anyway. please explain if it is acceptable.

**Comment by jbarros35** [comment]
> Thank you for participating here. Unfortunately, this pull request can not be merged because of:
> 
> * Project does not follow the showcase guidelines. In particular: website

changed already

**Comment by katomm** [comment]
Hello,
this PR has been open for more than 2 weeks and I would like to give you a little feedback about it here. It probably didn't get enough "traction" among reviewers. Please note that showcase projects need to provide a unique value from existing showcase items and need to have enough community reputation.

**My personal suggestions:**  
Close this PR, try to improve it, try to get more traction in the community and come back later. Maybe you could also find other parts in the portal where you can contribute.

I would also like to point out that the pull request does not pass the automated checks (indicated by a red X not a green tick).

**References:**
The current guidelines: https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/showcases.js

Discussions about guidelines: https://github.com/cardano-foundation/developer-portal/discussions

**Comment by katomm** [comment]
I am closing this PR as there seems to be no progress.

**Pull request closed without merging**
