### PR TITLE
add project PS Max Zaxster

### PR DESCRIPTION
**Pull request by PSMaxZaxster**
Showcase addition
Name: PS Max Zaxster
Description: We are painting studio and transforming our painters work into NFT. Finishing our special crypto collection, cards of famous painters in 2k collection.
Link: (https://www.maxzaxster.com/)
Source:
Tags:
educational
nftproject
token
nft

### CODE REVIEW

**Review by PSMaxZaxster — COMMENTED** [review]
Correct one.

**Review by PSMaxZaxster — COMMENTED** [review]
ok

**Comment by PSMaxZaxster** [comment]
@katomm i need to do anything else?

**Comment by katomm** [comment]
Thank you for your contribution and for building on Cardano. This PR has been open for quite a while and I would like to give you a little feedback. Projects need 3 reviewer approvals and it seems the project didn't get enough "traction" among the reviewers. 

Please note that showcase projects need to provide a unique value from existing showcase items - which is especially difficult with many tokens and FT/NFT or FT/NFT platforms. Feel free to join the discussion here: #243 (or in case you prefer to discuss this not in GitHub please join https://discord.gg/Exe6XmqKDx)

Suggestion: you can add your project to https://github.com/input-output-hk/essential-cardano

**Pull request closed without merging**
