### PR TITLE
Add showcase Sake Pool

### PR DESCRIPTION
**Pull request by fill-the-fill**
* Name: Wallet Analytics
* Description: Helpful tool that displays number of wallets that hold specific amount of ada.
* Link:   [SakePool](https://sakepool.com/onChainData/)
* Tags:
  * `analytics`

### CODE REVIEW

**Review by rdlrt — COMMENTED** [review]
have to ask, what is the unique value ( drop token in addition to pool rewards isnt ) with this one?

**Review by os11k — APPROVED** [review]

**Review by os11k — CHANGES_REQUESTED** [review]
Agree with @rdlrt

**Comment by fill-the-fill** [comment]
@rdlrt @os11k Thank you for the feedback. I've made a mistake by uploading a completely wrong information, I've made some new changes now.

**Comment by katomm** [comment]
Closing this because of too few approvals.

**Pull request closed without merging**
