### PR TITLE
Add Aiken as smart contract language 

### PR DESCRIPTION
**Pull request by OlofBlomqvist**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Updating documentation

This PR adds a new page for the Aiken smart contract toolchain to the "Create smart contracts" category.
I've tried to keep the page pretty short since Aiken is still in early days so much of the details are subject to change and
have also checked with the txpipe team who were ok with adding the page.

### CODE REVIEW

**Comment by nielstron** [comment]
@Aiken-lang 👀

**Review by rdlrt — APPROVED** [review]

**Review by rphair — APPROVED** [review]
Nice touch to add the language syntax. 🤓 Just changed the caution about production use to an admonition in keeping with other styles (@rdlrt please feel free to double check after your own review).

**Comment by nielstron** [comment]
Just tagging @Hyperion-BT, @plutonomicon, @harmonicLabs and @nau . Maybe these projects are also willing to contribute pages for their projects, speeding up the additional pages :)

**Comment by rphair** [comment]
sure, all the of the above please just wait until question https://github.com/cardano-foundation/developer-portal/pull/927#issuecomment-1383604076 is answered before submitting similar PR's 😎

**Comment by OlofBlomqvist** [comment]
> Note before final review: #929 adds Eopsin to this list: https://developers.cardano.org/docs/smart-contracts/#programming-languages
> 
> ... and I believe if we are adding one we should also add the other. Or neither: but we would have to consider the point made in [#927 (comment)](https://github.com/cardano-foundation/developer-portal/pull/927#issuecomment-1383604076) about "two tiers" of endorsement not serving the community's interests.
> 
> @rdlrt I know adding this change (I'll made if if @OlofBlomqvist agrees, or he can add it) changes the parameters of your earlier review so maybe you could let us know what you think.

I actually just forgot to add it there - please go ahead and make the change :)

**Comment by rphair** [comment]
OK, that's done: probably setting the precedent that all smart contract languages added to the Dev Portal should also be on this list (unless consensus suggests otherwise).

**Comment by rdlrt** [comment]
> I know adding this change (I'll made if if @OlofBlomqvist agrees, or he can add it) changes the parameters of your earlier review so maybe you could let us know what you think.

Is that wrt comment about demeter? If so, that was seperate (direct IaaS vs how-to followed by easy path, already addressed with what's doable for now). The adding of aforementioned community SC deployment languages are welcome IMO.

**Comment by rdlrt** [comment]
>  I know adding this change (I'll made if if @OlofBlomqvist agrees, or he can add it) changes the parameters of your earlier review so maybe you could let us know what you think.

I agree with the resultant changes 👍🏻

**Review by fill-the-fill — APPROVED** [review]

**Pull request merged**
