### PR TITLE
Revamp stake pool course

### LINKED ISSUE #641: SPO Sidebar navigation
I am updating the SPO part and will do it in several small steps. The first topic is:
-  to reorganize the Stake Pool section and integrate the content in the handbook into the course. The new sections could be 
1) Introduction 
2) Pre-requisites 
3) Installing & Configuring Cardano Nodes 
4) Registering a Pool 
5) Pool Maintenance 
6) Tools and Links

SPO Sidebar

### PR DESCRIPTION
**Pull request by sanskys**
#### Issue

Fixes #641 

#### Description of the change

Just re-push from main to revamp-stake-pool-course. No changes. See Issue #723

### CODE REVIEW

**Comment by rphair** [comment]
thanks @sanskys - @katomm this seems exactly what was planned in https://github.com/cardano-foundation/developer-portal/pull/723#issue-1325881799 👍

**Comment by katomm** [comment]
Thanks @sanskys and @rphair. Good that we now have it separately in its own branch, but I still don't see the point of adding "coming soon" pages. (maybe I'm missing something, who is building this out and is there a plan?)

**Comment by sanskys** [comment]
> Thanks @sanskys and @rphair. Good that we now have it separately in its own branch, but I still don't see the point of adding "coming soon" pages. (maybe I'm missing something, who is building this out and is there a plan?)

My understanding from the discussion in #641 and Discord working-on-pages is that many in the community would like to support the revamp of SPO Course. First step was to agree on the new structure which we did in the previous discussions. The result was the new sidebar structure tree with chapter titles. So that we can work in parallel, I merged these pages with the place holder "coming soon". I am working on the chapters Intro and Pre-requisites at the moment. @rphair is working on security review. 
I am not aware whether others are also working on any topics, maybe could be due to the holiday season in Europe. I would continue working on the chapters on by one and any help is highly welcome!

**Comment by katomm** [comment]
@sanskys It's really not a big deal. Just, in my opinion, this PR could have just been an issue/discussion post with a suggestion of a menu structure. PR should be in itself "complete".

**Comment by sanskys** [comment]
> @sanskys It's really not a big deal. Just, in my opinion, this PR could have just been an issue/discussion post with a suggestion of a menu structure. PR should be in itself "complete".

ok. now i understand your point. Just revert the changes and i will PR for each chapter once they are ready

**Comment by katomm** [comment]
No need to revert it

**Pull request merged**
