### PR TITLE
On-Chain Polls: Fix verify-poll parameter

### PR DESCRIPTION
**Pull request by weebl2000**
It's --tx-file, not --signed-tx-file

## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Updating documentation or Bugfix

image

### CODE REVIEW

**Review by rphair — APPROVED** [review]
True enough, thanks 🤓
```
$ cardano-cli-8.0.0 governance verify-poll
Usage: cardano-cli-8.0.0 governance verify-poll --poll-file FILE
            --tx-file FILE
            [--out-file FILE]
```

**Comment by weebl2000** [comment]
I spot a Nijntje!

**Comment by rphair** [comment]
correct, it's from the cover of _Miffy Learns to Paint_ (English title); I edited out the paintbrush 🐰

**Comment by rphair** [comment]
@katomm @os11k @rdlrt getting some traffic from https://forum.cardano.org/t/entering-voltaire-on-chain-poll-for-spos/117330/38 so will have to push this out soon.

**Review by rdlrt — APPROVED** [review]

**Review by os11k — APPROVED** [review]

**Comment by rphair** [comment]
I figured out how this error came about... the option was `--signed-tx-file` in the backport.  I guess since `8.0.0` uses the more canonically named option, and will completely supersede the backport in time, there's no point complicating the instructions by explaining how the backport works differently.  @rdlrt @os11k @fill-the-fill @katomm maybe let me know if you think otherwise & I'll update the instructions for both cases.
```
$ cardano-cli-8.0.0 governance verify-poll --poll-file poll.json --tx-file vote.signed
Found valid poll answer with 1 signatories
[
    "c94e6fe1123bf111b77b57994bcd836af8ba2b3aa72cfcefbec2d3d4"
]
```
```
$ cardano-cli-1.35.7+cip-0094 governance verify-poll --poll-file poll.json --tx-file vote.signed
Invalid option `--tx-file'

Usage: cardano-cli-1.35.7+cip-0094 governance verify-poll --poll-file FILE
            --signed-tx-file FILE

  Verify an answer to a given SPO poll
```

**Pull request merged**
