### PR TITLE
added cardano-tools.io

### PR DESCRIPTION
**Pull request by wutzebaer**
## Showcase addition

* Name: cardano-tools.io
* Description: The most advanced CNFT maker. You just pay network fees.
* Link:   https://cardano-tools.io
* Source: https://github.com/wutzebaer/cardano-tools
* Tags:
  * `opensource`
  * `nativetoken`
  * `nft`

### CODE REVIEW

**Review by rdlrt — APPROVED** [review]

**Review by katomm — APPROVED** [review]
👍 nice @wutzebaer. Thanks

**Comment by gufmar** [comment]
Tbh I struggle a bit with the "most advanced" wording.
Who defined/classified this? And how long will it remain valid?
I would recommend to change it in something like "an advanced CNFT maker' please.

**Comment by wutzebaer** [comment]
@gufmar thank you for the feedback. I've changed the wording.

**Review by gufmar — APPROVED** [review]
LGTM

**Pull request merged**
