### PR TITLE
Add Yaci DevKit into builder tools

### PR DESCRIPTION
**Pull request by fill-the-fill**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have read the [Builder Tool Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/builder-tools.js)
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Builder Tool addition

* Title: *Yaci DevKit*
* Description: *Create your own local Cardano devnet with ease! It includes an Indexer, minimal Explorer interface, and support for Cardano Client Lib or Lucid JS library's Blockfrost provider.*
* Website:  [Yaci DevKit](https://github.com/bloxbean/yaci-devkit)
* Getstarted: null
* Tags:
  * `cli`
  * `testing`

### CODE REVIEW

**Review by rphair — APPROVED** [review]
Looks like a really good thing 🤓

I wonder about the best criterial for scaling these logos into the image box.  Currently it's rather small compared to the frame & could be increased a bit.  But also would be good if it's "magnified" no more than other logos... yet I think making the logos larger on solid colour backgrounds would provide more clarity & uniqueness for the projects.

@fill-the-fill you are scaling these according to your own impressions & know well how the logos all look in groups, so what are your feelings are about this? 🤔

**Comment by fill-the-fill** [comment]
> Looks like a really good thing 🤓
> 
> I wonder about the best criterial for scaling these logos into the image box. Currently it's rather small compared to the frame & could be increased a bit. But also would be good if it's "magnified" no more than other logos... yet I think making the logos larger on solid colour backgrounds would provide more clarity for the projects & presentation quality for the Portal pages.
> 
> @fill-the-fill you are scaling these according to your own impressions & know well how the logos all look in groups, so what are your feelings are about this? 🤔

I've scaled the logo for it to fit in the preview image. Since I didn't find any other picture that represents the project I used this one and scaled a bit. But I'm more than open for changes 😊

**Comment by fill-the-fill** [comment]
> IMHO we should MAKE ALL THE THINGS BIGGER 😂 unless there is some typographic usefulness for the white space surrounding web site features 🤓

I could look into that and spend some time adjusting other logos. Maybe you could open an issue (suggestion) and I will take into my hands =)

**Comment by rphair** [comment]
sure, I'll have a look next time browsing the listings.  There were 1 or 2 contributions where the logo was _too_ small (this is not one of them), or detail in a screenshot was illegible (and therefore also needed to be "zoomed in" somehow), and in my experience we've addressed them in the PRs.  If I detect a potential improvement I'll open an issue and maybe GIMP them myself. 😎

**Review by rdlrt — APPROVED** [review]

**Review by os11k — APPROVED** [review]

**Pull request merged**
