### PR TITLE
Update register-stake-pool.md, lets use protocol.json everywhere

### PR DESCRIPTION
**Pull request by os11k**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Updating documentation or Bugfix

Update register-stake-pool.md, lets use protocol.json here as everywhere else instead of params.json, this will introduces a bit more consistency.

### CODE REVIEW

**Review by rphair — APPROVED** [review]
I also wanted to update that at the last review of this document, but was of a mixed mind about it.  I think avoiding potential questions like "how are these files different?" is more important than the license to assign an arbitrary name for this file.

**Comment by os11k** [comment]
Sorry, @rphair , for those multiple commits even after I marked this PR as ready for review. I just found a bit more time today than expected and decided to add those bits too. It is still, in my opinion, work in progress, but I will leave it as it is for now. Maybe later I will get a bit more time, but then it will go in a separate PR. Again, sorry for this mess. Cheers!

**Comment by rphair** [comment]
> multiple commits even after I marked this PR as ready for review

😎 no problem, still looks good ✔️

**Review by rdlrt — APPROVED** [review]

**Comment by os11k** [comment]
this is a lost one, I promise.... I removed * from IF in UTXP script. I had * for my environment, where * is necessary, because after redirecting output from Docker to local files, it seems to add a /r at the end of the fullUtxo.out file. This is not necessary here, as most users will not be using Docker.

**Comment by rphair** [comment]
fine with me ✔️ and I also realised it would drive me crazy if not removing the `-` (from the machine readable command option) from the human readable English expression "protocol parameters" 🤓

**Pull request merged**
