### PR TITLE
Correct grammar and spelling for Mainnet and testnets (staging)

### PR DESCRIPTION
**Pull request by rphair**
As per resolutions in https://github.com/cardano-foundation/developer-portal/pull/983#issuecomment-1469457031 (for the Style Guide) and https://github.com/cardano-foundation/developer-portal/pull/983#issuecomment-1469684918 (for these terms applied all through the Dev Portal).  This was a lot of review & modifies many files all over the place, but we will never have proper documentation submitted in the future without correcting what's already here.

I also corrected _**only** the use of these terms_ in obsolete documentation, so that the documentation repurposed from it doesn't propagate the incorrect spelling & grammar.  If documentation appeared obsolete or incorrect I didn't necessarily correct those parts (notably when `preview` and `preprod` testnets might need to be disambiguated).

- For several of these potentially obsolete pages, for the first use of the term "testnets" (as a requirement to continue) I linked it to the article that explains the usage of both networks.  Hopefully that will reduce the consequences of this ambiguity or incorrect syntax as it currently appears.

Note I will have to submit a second PR for the pending material in revamp-stake-pool-course because the baseline is different (cc @sanskys).

@katomm you have always been the style guy (in my observation) so I hope you will have a look at this first.

### CODE REVIEW

**Comment by rphair** [comment]
Last CI `yarn build` failure online looks like a result of merging https://github.com/cardano-foundation/CIPs/pull/421.  Will check out & fix on back end if necessary.

**Comment by rphair** [comment]
OK, this is a coincidental build problem: looks like these recently merged CIPs (having common header syntax, since produced concurrently from same author & just merged in last 24 hours), produce filenames like this when downloaded by `yarn build`:
```
-rw-rw-r-- 1 rphair rphair   367 2023-03-20 17:21 'CIP-0075)<.md'
-rw-rw-r-- 1 rphair rphair   367 2023-03-20 17:21 'CIP-0082)<.md'
```
The basis for this error must begin there; above filenames make it look like a non-terminated string?
```
[ERROR] Error while parsing Markdown front matter.
This can happen if you use special characters in front matter values (try using double quotes around that value).
[ERROR] Loading of version failed for version current
[ERROR] Unable to build website for locale en.
[ERROR] Error: Can't process doc metadata for doc at path path=/home/rphair/archive/build/developer-portal/docs/governance/cardano-improvement-proposals/CIP-0075)<.md in version name=current
    at processDocMetadata (/home/rphair/archive/build/developer-portal/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:200:15)
    at async Promise.all (index 124)
```
Will open up an issue for this unless it turns out to be a simple fix.  I'm cabbaged from detailed work now & wouldn't be able to dive into the build code for some time.  Maybe @os11k @Mercurial @oversize @fill-the-fill something jumps out at you?

**Comment by fill-the-fill** [comment]
> OK, this is a coincidental build problem: looks like these recently merged CIPs (having common header syntax, since produced concurrently from same author & just merged in last 24 hours), produce filenames like this when downloaded by `yarn build`:
> 
> ```
> -rw-rw-r-- 1 rphair rphair   367 2023-03-20 17:21 'CIP-0075)<.md'
> -rw-rw-r-- 1 rphair rphair   367 2023-03-20 17:21 'CIP-0082)<.md'
> ```
> 
> The basis for this error must begin there; above filenames make it look like a non-terminated string?
> 
> @KtorZ I can't find anything non-compliant or unique (other than ordering of headers) in the front matter; can you?
> 
> ```
> [ERROR] Error while parsing Markdown front matter.
> This can happen if you use special characters in front matter values (try using double quotes around that value).
> [ERROR] Loading of version failed for version current
> [ERROR] Unable to build website for locale en.
> [ERROR] Error: Can't process doc metadata for doc at path path=/home/rphair/archive/build/developer-portal/docs/governance/cardano-improvement-proposals/CIP-0075)<.md in version name=current
>     at processDocMetadata (/home/rphair/archive/build/developer-portal/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:200:15)
>     at async Promise.all (index 124)
> ```
> 
> Will open up an issue for this unless it turns out to be a simple fix. I'm cabbaged from detailed work now & wouldn't be able to dive into the build code for some time. Maybe @os11k @Mercurial @oversize @fill-the-fill something jumps out at you?

Yeah seems like there is a problem with the script, I'm on it

**Comment by rphair** [comment]
local `yarn build` works fine again, thanks to @fill-the-fill & merging https://github.com/cardano-foundation/developer-portal/pull/992 🤩

**Review by fill-the-fill — APPROVED** [review]

**Comment by sanskys** [comment]
> As per resolutions in [#983 (comment)](https://github.com/cardano-foundation/developer-portal/pull/983#issuecomment-1469457031) (for the Style Guide) and [#983 (comment)](https://github.com/cardano-foundation/developer-portal/pull/983#issuecomment-1469684918) (for these terms applied all through the Dev Portal). This was a lot of review & modifies many files all over the place, but we will never have proper documentation submitted in the future without correcting what's already here.
> 
> I also corrected _**only** the use of these terms_ in obsolete documentation, so that the documentation repurposed from it doesn't propagate the incorrect spelling & grammar. If documentation appeared obsolete or incorrect I didn't necessarily correct those parts (notably when `preview` and `preprod` testnets might need to be disambiguated).
> 
> * For several of these potentially obsolete pages, for the first use of the term "testnets" (as a requirement to continue) I linked it to the article that explains the usage of both networks.  Hopefully that will reduce the consequences of this ambiguity or incorrect syntax as it currently appears.
> 
> Note I will have to submit a second PR for the pending material in revamp-stake-pool-course because the baseline is different (cc @sanskys).
> 
> @katomm you have always been the style guy (in my observation) so I hope you will have a look at this first.

you need not correct the Stake Pool Course as after my next pull i would like to merge the complete branch to staging and the stake pool course would then be moved to obsolete.

**Review by os11k — APPROVED** [review]

**Review by rdlrt — APPROVED** [review]

**Pull request merged**
