### PR TITLE
use hex for asset names

### PR DESCRIPTION
**Pull request by shawnim**
---

#### Description of the change

cardano-cli version 1.32.1 now requires asset names to be specified in hex rather than ascii.
This PR fixes the minting instructions for native assets and NFTs to use hex asset names.

### CODE REVIEW

**Review by rdlrt — APPROVED** [review]

**Comment by katomm** [comment]
Thank you @shawnim. We might want to solve the conflicts as all checks are failing.

**Comment by shawnim** [comment]
There were no conflicts when I submitted the PR.
I'll take a look and see what has changed.

**Comment by shawnim** [comment]
Resolved conflicts and checks are passing now.

**Review by katomm — APPROVED** [review]
Thank you @shawnim, I appreciate it.

**Pull request merged**
