### PR TITLE
Add extra DCOneCrypto utilities to Showcase

### PR DESCRIPTION
**Pull request by DCOneCrypto**
- Name: **Send Multiple Tokens and NFT Builder, Mint, Burn**
- Description: Users send multiple ADA addresses, tokens and create your own NFT, Mint, Burn with just a few clicks
- Link: [click here](https://cardano.dconecrypto.finance/)
- Tags: `minting`, `token`, `nftsupport`

### CODE REVIEW

**Comment by rphair** [comment]
@DCOneCrypto so we can at least read this, why don't you please edit (or re-edit) `showcases.js` in this branch so it doesn't include all the quotation-mark, indentation and white space changes... showing just the thing(s) you are adding?

Note: unless showcase submissions are _intimately_ related (I can't tell for sure if there are in fact 2 of them with all the noise in this diff), each PR should only for 1 addition.

**Comment by DCOneCrypto** [comment]
> @DCOneCryptođể ít nhất chúng ta có thể đọc được nội dung này, tại sao bạn không vui lòng chỉnh sửa (hoặc chỉnh sửa lại) nội dung của mình `showcases.js`để nó không bao gồm tất cả các thay đổi về dấu ngoặc kép, thụt đầu dòng và khoảng trắng thừa... chỉ hiển thị (các) nội dung bạn đang thêm?
> 
> Lưu ý: trừ khi các bài gửi giới thiệu có liên quan _mật thiết với nhau_ (tôi không thể chắc chắn liệu thực tế có 2 bài trong số đó gây ồn ào ở điểm khác biệt này hay không), mỗi bài PR chỉ nên dành cho 1 bài bổ sung.



> @DCOneCrypto so we can at least read this, why don't you please edit (or re-edit) your `showcases.js` so it doesn't include all the superfluous quotation-mark, indentation and white space changes... showing just the thing(s) you are adding?
> 
> Note: unless showcase submissions are _intimately_ related (I can't tell for sure if there are in fact 2 of them with all the noise in this diff), each PR should only for 1 addition.

We have updated again as the information you mentioned. You review. Thank you 😁

**Comment by rphair** [comment]
@DCOneCrypto thanks for clearing up your submission to make it readable as a single change.  We can now see it points to a microsite (subdomained away from [dconecrypto.finance](https://dconecrypto.finance/) where most of your credibility is established) with the 2 mentioned utilities on it.

There is no documentation link in the submission, with no documentation pages in the navigation bar on that microsite.  Only (if not connecting with a wallet) it displays the invitation "Connect your wallet and start exploring" which I could not imagine doing in a tool with no online documentation or vetting.

If anyone could make this tool suitable for the Dev Portal, I would suggest at least they include a page in the site navigation saying what this does that stock features of other wallets (like Eternl with its Transaction Builder) don't do.

We probably could figure that out by trial & error, but in our role as editors we are better suited to establish that submitted tools are trustworthy, well-documented and useful... if not unique.  In my opinion we are not seeing any of that here, so @DCOneCrypto if you are going to keep submitting tools here then please keep that in mind from both the editors' and your potential users' perspective.

**Comment by DCOneCrypto** [comment]
> @DCOneCrypto thanks for clearing up your submission to make it readable as a single change. We can now see it points to a microsite (subdomained away from [dconecrypto.finance](https://dconecrypto.finance/) where most of your credibility is established) with the 2 mentioned utilities on it.
> 
> There is no documentation link in the submission, with no documentation pages in the navigation bar on that microsite. Only (if not connecting with a wallet) it displays the invitation "Connect your wallet and start exploring" which I could not imagine doing in a tool with no online documentation or vetting.
> 
> If anyone could make this tool suitable for the Dev Portal, I would suggest at least they include a page in the site navigation saying what this does that stock features of other wallets (like Eternl with its Transaction Builder) don't do.
> 
> We probably could figure that out by trial & error, but in our role as editors we are better suited to establish that submitted tools are trustworthy, well-documented and useful... if not unique. In my opinion we are not seeing any of that here, so @DCOneCrypto if you are going to keep submitting tools here then please keep that in mind from both the editors' and your potential users' perspective.

Hello @rphair 

We have added tool information, function descriptions, how-to videos... Users can find the information in the "How It Work?" navigation?

We'll take note of the issue you raised when we have the next tool contribution

Thank you for your input & comments.

**Review by rphair — COMMENTED** [review]
@DCOneCrypto I can see you've added an FAQ page to your navigation, which could be helpful although the answers are not very detailed.  Still I don't think it matches the calibre of other tools in the NFT utility class here on the Developer Portal, but I will go along with the opinion of other reviewers if they think otherwise.

**Comment by DCOneCrypto** [comment]
> @DCOneCrypto I can see you've added an FAQ page to your navigation, which could be helpful although the answers are not very detailed. Still I don't think it matches the calibre of other tools in the NFT utility class here on the Developer Portal, but I will go along with the opinion of other reviewers if they think otherwise.

Thank you. We will wait for the votes of other reviewers. Great

**Comment by DCOneCrypto** [comment]
Hii everyone!

After researching information in the Developer Portal, we found and summarized the comparison as follows:

**Our team tool is now all-in-one:** Send $ADA & tokens to **many different wallet addresses in the same txid transaction** (many applications currently do not support this function) and if there is support support (e.g. Eternl has support for sending native assets to multiple wallet addresses but they don't have an NFT, Token generator). If other developer tools have NFT, Token generation tools, most of the time they don't have built in functionality to send native assets to multiple wallet addresses.

In addition to creating tokens, NFT is currently most of the time through intermediaries and does not manage policy id by themselves, on the contrary, if the community uses our tool, they can **automatically manage policy id and burn assets**.

Here is our summary. Thank you to everyone who took the time to join and comment with us

**Pull request closed without merging**
