### PR TITLE
Open graph images patch

### PR DESCRIPTION
**Pull request by katomm**
This PR will fix issues introduced with PR #788 and update more pages to use a specific open graph image instead of the default one, that only shows the start page of the developer portal.

Screenshot 2022-09-22 at 13 08 52

### CODE REVIEW

**Review by fill-the-fill — APPROVED** [review]

**Review by rphair — APPROVED** [review]
great 😍 ... @katomm does the previewer screenshotted in the OP work on locally served web pages? (re: https://github.com/cardano-foundation/developer-portal/pull/788#issuecomment-1254652544)

Builds OK with current `staging` ✔️

**Comment by katomm** [comment]
@rphair it depends, ofc not with tools like https://www.opengraph.xyz because they can not access the site. And other local tools will run into issues trying to find the new open graph image because it looks on developers.cardano.org domain even if we put in the link relative and not absolute. It would work locally if the image is already in the img/og/ folder, then it just fetches the image from the cardano.org domain.

It is some hassle but we should go through it because the sharing experience for users on socials is so much better.

**Comment by rphair** [comment]
@katomm from your comments in both PR's, and the official looking screenshot you have above, I'm guessing you're using [ngrok](https://ngrok.com) or equivalent to set up a web accessible version of the localhost site?  Especially if that equivalent will map `developers.cardano.org` to the domain name of the copied site, according to your last comment?

**Review by rdlrt — APPROVED** [review]

**Comment by katomm** [comment]
> and the official looking screenshot you have above, I'm guessing you're using [ngrok](https://ngrok.com) or equivalent to set up a web accessible version of the localhost site?

Not at all. That is a real screenshot. Might be a little bit misleading because this change was already done in PR #788, it was not meant to visualize the changes in this PR :)) But ofc they are similar.

**Pull request merged**
