### PR TITLE
Add builder tool: Stakepool Block Counter

### PR DESCRIPTION
**Pull request by mcvetyty**
## Checklist

- [x] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [x] I have read the [Builder Tool Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/builder-tools.js)
- [x] I have run `yarn build` after adding my changes **without getting any errors**. 

## Builder Tool addition

* Title: *Stakepool Block Counter*
* Description: *A Python script that can be placed on a Cardano Block Producer node to extract block data (scheduled/minted/missed/etc) and writes updates to a file and/or submits them to an API endpoint.* 
* Website:   [<link_to_project>](https://github.com/YeppleInc/pool-block-counter)
* Getstarted: [<link_to_getstarted_page>](https://github.com/YeppleInc/pool-block-counter)
* Tags:
  * `operatortool`
  * `python`

### CODE REVIEW

**Comment by mcvetyty** [comment]
The yarn build appears to be failing due to several .md files not associated with my pull request. Are reviewers still able to conduct their review?

**Comment by rphair** [comment]
> several .md files not associated with my pull request

@fill-the-fill so far we haven't been able to get @KtorZ on the horn to approve this fix upstream (https://github.com/cardano-foundation/CIPs/pull/565/); but was some pathname massaging done in one of your recent script changes?

@mcvetyty I don't think we'll wait long for a green light from the build process.  If this isn't fixed by Monday just ping again & maybe we can find some other way of confirming just the changes that you have made.  (We can't just edit the upstream files because they _always_ have to be _all_ be downloaded _all_ over again every time the Portal builds; the files in the CIP repo can't be trumped by local versions dated the same or more recently, which would be nice.)

**Comment by mcvetyty** [comment]
> In the current state of repo, it is a very simple codebase, reading code from sqlite DB from guild tools combined with conversion of few functions internally used within `env` file into python (and using hard-coded values at that, instead of reading from configs).
> 
> Do you have future plans that makes this a builder tool that's unique and noticeable to list on developer portal?
> 
> (PS: Apologies- I might be coming across a bit mechanical, not a guy that's good with words. I do not mean to discourage nor underestimate your efforts, purely thinking of value proposition from each builder tool entry)

Thank you, @rdlrt and certainly no offense taken. I also questioned whether this would be a good submission or not, but in the end decided it was worthwhile to submit it as this tool is intended to grow as we scale our services, constantly adapting to the requests and needs of our clients. 

Rather than approaching the functionality through a purely technical lens, we are deriving feature requests directly from the stake pool owners themselves. We feel this will give the codebase an inherent value beyond the technical scope, and will give the developer community the simplistic building blocks needed to meet the practical growth/analytics demands of stake pool owners actively involved in the community.

**Review by rphair — COMMENTED** [review]
@mcvetyty looks like the build is failing because you put your project's thumbnail image in the `/showcase` directory while the preview pathname field points (as it should) to the `/builder-tools` directory.

**Comment by mcvetyty** [comment]
> @mcvetyty looks like the build is failing because you put your project's thumbnail image in the `/showcase` directory while the preview pathname field points (as it should) to the `/builder-tools` directory.

Doh.. My bad. Fixing now.

**Review by rphair — APPROVED** [review]
I agree with @rdlrt about the simplicity of the tool being somewhat below the bar for the Developer Portal, but also feel it's justifiable since some SPOs will come here specificaly looking for something like this and it would be helpful to offer them a lightweight solution.  Effectively @mcvetyty this leaves it to 2 other reviews to decide that the implementation is substantial enough to be included here. 🧐

**Comment by mcvetyty** [comment]
Thanks @rphair, and that was my thought. There's likely a desire for a collection of simpler scripts/tools that stakepool operators who aren't developers or that tech savvy could use to help grow their pools and communities. For example, this script could easily be modified to post block counts to Discord via a Discord bot which would be useful for many small stake pool operators.

**Comment by katomm** [comment]
The pull request has not received the required approvals and is closed. However, it can be opened again. Details on: https://developers.cardano.org/docs/portal-contribute/#how-are-pull-requests-reviewed

In any case, the discussion can be continued here.

**Pull request closed without merging**
