### PR TITLE
Update showcases.js

### PR DESCRIPTION
**Pull request by jonathanfishbein1**
## Showcase addition

* Name: *Cardania*
* Description: Cardania is a scifi fantasy metaverse gaming ecosystem project being built on the Cardano blockchain. Welcome to the most rad destination in the metaverse.
* Link:  https://cardania.com
* Source: <link_to_source_code>
* Tags:
  * `game`
  * `nft`

### CODE REVIEW

**Review by katomm — CHANGES_REQUESTED** [review]
Site does not seem to work. "...This site can’t be reached. www.cardania.com’s DNS address could not be found. Diagnosing the problem. DNS_PROBE_POSSIBLE.."

**Comment by jonathanfishbein1** [comment]
ooo that is a problem.  I'm sorry about that, let me fix that

**Comment by jonathanfishbein1** [comment]
Updated!

**Comment by katomm** [comment]
@jonathanfishbein1 looks good, but is this live or a preview? It doesn't look like anything can be done.

**Comment by jonathanfishbein1** [comment]
The development is iterative but already has network connectivity - We most recently ran a very popular NFT sale utilizing our website for the front end and NFT Maker Pro for the backend. Delegators are also able to stake to SUMN directly from the site. Users will see a lot more game interaction in the coming months which we're very excited for.

**Comment by katomm** [comment]
Thank you for your contribution and for building on Cardano. This PR has been open for quite a while and I would like to give you a little feedback. Projects need 3 reviewer approvals and it seems the project didn't get enough "traction" among the reviewers. 

Please note that showcase projects need to provide a unique value from existing showcase items - which is especially difficult with many tokens and FT/NFT or FT/NFT platforms. Feel free to join the discussion here: #243 (or in case you prefer to discuss this not in GitHub please join https://discord.gg/Exe6XmqKDx)

Suggestion: you can add your project to https://github.com/input-output-hk/essential-cardano

**Pull request closed without merging**
